-- SQL for table: EDW_FXF_OBUCIF_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CIFKEY,
CORPNO,
CNAME,
CCADDR,
OBUPASSNO,
CONAME,
JOB,
COAREA,
COTELNO,
COEXTNO,
EXPDAT,
REGNO,
MAINZIP,
MAINADR,
MAINADR2,
MAINADR3,
MAINADR4,
MAINADR5,
DBUID,
REVERIFY,
PASNOEXP,
CELLPHNO,
REGAGENT,
MNATION,
BILLZIP,
BILLADR1,
BILLADR2,
BILLADR3,
BILLADR4,
BILLADR5,
MULTIAC,
REVENUE,
CAPITALAMT,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASE WHEN LENGTH(CIFKEY) = 8 THEN SDG.UFN_MASK_BAN(CIFKEY) WHEN LENGTH(CIFKEY) = 10 THEN SDG.UFN_MASK_IDN(CIFKEY) END,
CORPNO,
SDG.UFN_MASK_NM(CNAME),
SDG.UFN_MASK_ADDR(CCADDR),
SDG.UFN_MASK_PNO(OBUPASSNO),
SDG.UFN_MASK_NM(CONAME),
SDG.UFN_MASK_INFO(JOB),
COAREA,
SDG.UFN_MASK_TEL(COTELNO),
COEXTNO,
EXPDAT,
REGNO,
MAINZIP,
SDG.UFN_MASK_ADDR(MAINADR),
SDG.UFN_MASK_ADDR(MAINADR2),
SDG.UFN_MASK_ADDR(MAINADR3),
SDG.UFN_MASK_ADDR(MAINADR4),
SDG.UFN_MASK_ADDR(MAINADR5),
SDG.UFN_MASK_BAN(DBUID),
REVERIFY,
PASNOEXP,
SDG.UFN_MASK_TEL(CELLPHNO),
SDG.UFN_MASK_NM(REGAGENT),
MNATION,
BILLZIP,
SDG.UFN_MASK_ADDR(BILLADR1),
SDG.UFN_MASK_ADDR(BILLADR2),
SDG.UFN_MASK_ADDR(BILLADR3),
SDG.UFN_MASK_ADDR(BILLADR4),
SDG.UFN_MASK_ADDR(BILLADR5),
MULTIAC,
REVENUE,
CAPITALAMT,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
