-- SQL for table: EDW_WMS_ORGEMPDATE_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
EMP_ID,
AO_BRCH,
AO_TYPE,
ON_BOARD_DATE,
OFF_BOARD_DATE,
IS_EXCLUSIVE,
AO_TENURE,
AO_TENURE_M,
AO_TENURE_Q,
MARK_4_DEL,
REMARK,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
EMP_ID,
AO_BRCH,
AO_TYPE,
ON_BOARD_DATE,
OFF_BOARD_DATE,
IS_EXCLUSIVE,
AO_TENURE,
AO_TENURE_M,
AO_TENURE_Q,
MARK_4_DEL,
REMARK,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
