-- SQL for table: EDW_FC_FCCHG_PRESTAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Prestage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Stage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_FC_FCCHG_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_FC_FCCHG_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_FC_FCCHG_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_FC_FCCHG_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_FC_FCCHG_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_FC_FCCHG_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
