-- SQL for table: EDW_ELN_CRNEWCASE_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CASEID,
IDBAN,
BRID,
CASE_DATE,
REASON,
STAFFID,
REVIEW3,
APPROVEDATE,
ITEM_TYPE,
INDUNO,
INITDATE,
ENDDATE,
CREVALUE,
CURUNIT,
IND_GAP,
IND_IFRS,
SWSINGLE,
SWSIMINC,
SWJOIN,
ACCRPTVER,
GRADEYEAR,
APPNAME,
CHGMANID,
CHGMANNA,
TEL_ZIP,
TEL,
TELEXT,
FACINDUNO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASEID,
CASE WHEN LENGTH(IDBAN) = 8 THEN SDG.UFN_MASK_BAN(IDBAN) WHEN LENGTH(IDBAN) = 10 THEN SDG.UFN_MASK_IDN(IDBAN) END,
BRID,
CASE_DATE,
REASON,
STAFFID,
REVIEW3,
APPROVEDATE,
ITEM_TYPE,
INDUNO,
INITDATE,
ENDDATE,
CREVALUE,
CURUNIT,
IND_GAP,
IND_IFRS,
SWSINGLE,
SWSIMINC,
SWJOIN,
ACCRPTVER,
GRADEYEAR,
SDG.UFN_MASK_NM(APPNAME),
SDG.UFN_MASK_IDN(CHGMANID),
SDG.UFN_MASK_NM(CHGMANNA),
TEL_ZIP,
SDG.UFN_MASK_TEL(TEL),
SDG.UFN_MASK_ACCT_SN(TELEXT),
FACINDUNO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
