-- SQL for table: EDW_ELN_CRACOMPLPSNLN_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CASEID,
CRRPTNO,
QRYIDBAN,
LPSN_DATE,
LPSN_DEPART,
LPSN_PID,
LPSN_BRNO,
LPSN_POSNO,
LPSN_NAME,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASEID,
CRRPTNO,
CASE WHEN LENGTH(QRYIDBAN) = 8 THEN SDG.UFN_MASK_BAN(QRYIDBAN) WHEN LENGTH(QRYIDBAN) = 10 THEN SDG.UFN_MASK_IDN(QRYIDBAN) END,
LPSN_DATE,
LPSN_DEPART,
CASE WHEN LENGTH(LPSN_PID) = 8 THEN SDG.UFN_MASK_BAN(LPSN_PID) WHEN LENGTH(LPSN_PID) = 10 THEN SDG.UFN_MASK_IDN(LPSN_PID) END,
LPSN_BRNO,
SDG.UFN_MASK_INFO(LPSN_POSNO),
SDG.UFN_MASK_NM(LPSN_NAME),
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
