-- SQL for table: EDW_CF_CIFACT_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
ACTKIND,
ACTCLS,
CHARCD,
CIFKEY,
FLAG,
ACTADDR,
OPDATE,
CLDATE,
LASTDT,
TXCD,
MIDAY,
OPGOAL,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ME10.銀行帳號,
ACTKIND,
ACTCLS,
CHARCD,
若為8碼則使用ME2.統一編號, 若為10碼則使用ME3.身分證號,
FLAG,
ME6.地址,
OPDATE,
CLDATE,
LASTDT,
TXCD,
MIDAY,
OPGOAL,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
