-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Prestage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Stage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
