-- SQL for table: EDW_AROBO_IPMSETRBL_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
RBL_LOG_ID,
CUS_CODE,
IPMSET_CODE,
ORDER_DATE,
TRAN_STATUS,
RBL_TYPE_CD,
DATA_DATE,
RBL_DUE_DATE,
ADJ_REASON,
ADJ_DESC,
RANK_CODE,
PREFERENCE_CODE,
EFFECTIVE_YN,
ADJ_TYPE_CODE,
ORG_RANK_CODE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
RBL_LOG_ID,
SDG.UFN_MASK_IDN(CUS_CODE),
IPMSET_CODE,
ORDER_DATE,
TRAN_STATUS,
RBL_TYPE_CD,
DATA_DATE,
RBL_DUE_DATE,
ADJ_REASON,
ADJ_DESC,
RANK_CODE,
PREFERENCE_CODE,
EFFECTIVE_YN,
ADJ_TYPE_CODE,
ORG_RANK_CODE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
