-- SQL for table: EDW_ELN_CRIRBSCORE_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BATCH_DT,
BATCH_ID,
CASEID,
TXNO,
SCORE_TIME,
CASEITEMID,
APPNAME,
BRID,
RATING_SEQ,
GRADE_SCORE,
GRADE_RANK,
GRADE_PD,
GRADE_TIME,
NON_ONE_YEAR,
MISSING_VALUE_EXCEED30,
CR_MAINEFILE_SWJCICQRY,
CR_HRSTDENSU_SWJCICQRY,
BAD_OWNER,
R0401CD,
SUGGEST_SCORE,
SUGGEST_RANK,
SUGGEST_PD,
ACARD_PRE_SCORE_DT,
ACARD_PRE_SCORE,
ACARD_PRE_RANK,
ACARD_PRE_PD,
ACARD_TOT_RANK,
ACCOUNT,
BCARD_PRE_SCORE_DT,
BCARD_PRE_SCORE,
BCARD_PRE_RANK,
BCARD_PRE_PD,
BCARD_TOT_RANK,
LOANCURRAMT,
MISSING_JCIC,
MODEL_TYPE,
ERROR_CODE,
DEFAULT_FLAG,
FDD,
ACARD_PRE_CASEID,
ACARD_PRE_CASEITEMID,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BATCH_DT,
BATCH_ID,
CASEID,
TXNO,
SCORE_TIME,
CASEITEMID,
ME1.姓名/名稱,
BRID,
RATING_SEQ,
GRADE_SCORE,
GRADE_RANK,
GRADE_PD,
GRADE_TIME,
NON_ONE_YEAR,
MISSING_VALUE_EXCEED30,
CR_MAINEFILE_SWJCICQRY,
CR_HRSTDENSU_SWJCICQRY,
BAD_OWNER,
R0401CD,
SUGGEST_SCORE,
SUGGEST_RANK,
SUGGEST_PD,
ACARD_PRE_SCORE_DT,
ACARD_PRE_SCORE,
ACARD_PRE_RANK,
ACARD_PRE_PD,
ACARD_TOT_RANK,
ME10.銀行帳號,
BCARD_PRE_SCORE_DT,
BCARD_PRE_SCORE,
BCARD_PRE_RANK,
BCARD_PRE_PD,
BCARD_TOT_RANK,
LOANCURRAMT,
MISSING_JCIC,
MODEL_TYPE,
ERROR_CODE,
DEFAULT_FLAG,
FDD,
ACARD_PRE_CASEID,
ACARD_PRE_CASEITEMID,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
