-- SQL for table: EDW_NCARD_ACQSTOREINFEX_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACQ_BU,
MER_NBR,
MER_BAR_FLAG,
MER_QRC_DTE,
MER_BAR_DTE,
MER_EX_USER_CHAR_1,
MER_EX_USER_CHAR_2,
MER_EX_USER_CHAR_3,
MER_EX_USER_CHAR_4,
MER_EX_USER_CHAR_5,
MER_EX_USER_CHAR_6,
MER_EX_USER_CHAR_7,
MER_EX_USER_CHAR_8,
MER_EX_USER_CHAR_9,
MER_EX_USER_CHAR_10,
MER_EX_USER_DTE_1,
MER_EX_USER_DTE_2,
MER_EX_USER_DTE_3,
MER_EX_USER_DTE_4,
MER_EX_USER_DTE_5,
MER_EX_USER_DTE_6,
MER_EX_USER_DTE_7,
MER_EX_USER_DTE_8,
MER_EX_USER_DTE_9,
MER_EX_USER_DTE_10,
MER_EX_USER_AMT_1,
MER_EX_USER_AMT_2,
MER_EX_USER_AMT_3,
MER_EX_USER_AMT_4,
MER_EX_USER_AMT_5,
MER_EX_USER_AMT_6,
MER_EX_USER_AMT_7,
MER_EX_USER_AMT_8,
MER_EX_USER_AMT_9,
MER_EX_USER_AMT_10,
POST_RESULT,
CREATE_DT,
CREATE_USER,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ACQ_BU,
MER_NBR,
MER_BAR_FLAG,
MER_QRC_DTE,
MER_BAR_DTE,
MER_EX_USER_CHAR_1,
SDG.UFN_MASK_BAN(MER_EX_USER_CHAR_2),
MER_EX_USER_CHAR_3,
MER_EX_USER_CHAR_4,
MER_EX_USER_CHAR_5,
MER_EX_USER_CHAR_6,
MER_EX_USER_CHAR_7,
MER_EX_USER_CHAR_8,
MER_EX_USER_CHAR_9,
MER_EX_USER_CHAR_10,
MER_EX_USER_DTE_1,
MER_EX_USER_DTE_2,
MER_EX_USER_DTE_3,
MER_EX_USER_DTE_4,
MER_EX_USER_DTE_5,
MER_EX_USER_DTE_6,
MER_EX_USER_DTE_7,
MER_EX_USER_DTE_8,
MER_EX_USER_DTE_9,
MER_EX_USER_DTE_10,
MER_EX_USER_AMT_1,
MER_EX_USER_AMT_2,
MER_EX_USER_AMT_3,
MER_EX_USER_AMT_4,
MER_EX_USER_AMT_5,
MER_EX_USER_AMT_6,
MER_EX_USER_AMT_7,
MER_EX_USER_AMT_8,
MER_EX_USER_AMT_9,
MER_EX_USER_AMT_10,
POST_RESULT,
CREATE_DT,
CREATE_USER,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
