-- SQL for table: EDW_CF_CIFACT_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
ACTKIND,
ACTCLS,
CHARCD,
CIFKEY,
FLAG,
ACTADDR,
OPDATE,
CLDATE,
LASTDT,
TXCD,
MIDAY,
OPGOAL,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_MASK_ACCT(ACTNO),
ACTKIND,
ACTCLS,
CHARCD,
CASE WHEN LENGTH(CIFKEY) = 8 THEN SDG.UFN_MASK_BAN(CIFKEY) WHEN LENGTH(CIFKEY) = 10 THEN SDG.UFN_MASK_IDN(CIFKEY) END,
FLAG,
SDG.UFN_MASK_ADDR(ACTADDR),
OPDATE,
CLDATE,
LASTDT,
TXCD,
MIDAY,
OPGOAL,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
