-- SQL for table: EDW_NCARD_ACCTLINK_PRESTAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Prestage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Stage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_NCARD_ACCTLINK_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_NCARD_ACCTLINK_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_NCARD_ACCTLINK_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_NCARD_ACCTLINK_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_NCARD_ACCTLINK_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_NCARD_ACCTLINK_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
