-- SQL for table: EDW_IFRS9_GRBRN_PRESTAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Prestage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Stage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_IFRS9_GRBRN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_IFRS9_GRBRN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_IFRS9_GRBRN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_IFRS9_GRBRN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_IFRS9_GRBRN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_IFRS9_GRBRN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YM,
BRN_ID,
BRN_NM,
GUAR_AMT,
STAGE1_AMT,
STAGE1_IA_AMT,
STAGE1_IA_RATE,
STAGE2_AMT,
STAGE2_IA_AMT,
STAGE2_IA_RATE,
STAGE3_AMT,
STAGE3_IA_AMT,
STAGE3_IA_RATE,
IA_TOTAL_AMT,
IA_RATE,
LS_MON_IA_TOTAL_AMT,
IA_BAL_DIFF,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
