-- SQL for table: EDW_WMS_RPTORGDEFNHSM_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YYYYMM,
DATA_DATE,
TERRITORY_ID,
DESCR,
BRCH_CLS,
LEVEL_ID,
ORG_SEQ,
PAR_TERRITORY_ID,
VIRTUAL_FLAG,
CLS_FLAG,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YYYYMM,
DATA_DATE,
TERRITORY_ID,
DESCR,
BRCH_CLS,
LEVEL_ID,
ORG_SEQ,
PAR_TERRITORY_ID,
VIRTUAL_FLAG,
CLS_FLAG,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
