-- SQL for table: EDW_WMS_SFAORGMEMBER_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
EMP_ID,
EMP_NAME,
EMP_PID,
TERRITORY_ID,
TEL_NUM,
E_MAIL,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
EMP_ID,
ME1.姓名/名稱,
ME3.身份證號,
TERRITORY_ID,
ME7.電話,
ME8.電子郵件,
TITLE_ID,
TITLE_NAME,
SA_JOB_TITLE_ID,
SUB_TITLE_ID_1,
SUB_TITLE_ID_2,
BRANCH_DEPT,
FIN_FLAG,
MARK_4_DEL,
MARK_DATE,
SIGN_AG_YN,
SIGN_AG_DATE,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
