-- SQL for table: EDW_AROBO_CUSTRANS_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
INV_TYPE,
TRAN_CODE,
CHANNEL,
TRAN_TYPE,
TXN_NO,
IPMSET_CODE,
CUS_CODE,
PRO_CODE,
TRAN_CUR_CODE,
FX_RATE,
TRAN_DATE,
ORDER_DATE,
DISTRIBUTE_DATE,
SETTLE_DATE,
UNIT,
PRICE_DATE,
PRICE,
TRAN_AMT_FC,
TRAN_AMT_LC,
TRAN_AMT_NOFEE_FC,
TRAN_AMT_NOFEE_LC,
INV_AMT_FC,
INV_AMT_LC,
INV_AMT_NOFEE_FC,
INV_AMT_NOFEE_LC,
TRAN_FEE_FC,
TRAN_FEE_LC,
TRUST_FEE_RATE,
TRUST_FEE_FC,
SHORTERM_RATE,
SHORTTERM_FEE_FC,
PL_FC,
PL_LC,
RETURN_FC,
RETURN_LC,
REDEM_TYPE,
WITHDRAW_AC_NO,
REDEM_AC_NO,
TRAN_STATUS,
RBL_YN,
ROBOT_TX_DATE,
TXN_NO_2,
IPM_INVEST_AMT,
BRAN_CODE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
INV_TYPE,
TRAN_CODE,
CHANNEL,
TRAN_TYPE,
TXN_NO,
IPMSET_CODE,
SDG.UFN_MASK_IDN(CUS_CODE),
PRO_CODE,
TRAN_CUR_CODE,
FX_RATE,
TRAN_DATE,
ORDER_DATE,
DISTRIBUTE_DATE,
SETTLE_DATE,
UNIT,
PRICE_DATE,
PRICE,
TRAN_AMT_FC,
TRAN_AMT_LC,
TRAN_AMT_NOFEE_FC,
TRAN_AMT_NOFEE_LC,
INV_AMT_FC,
INV_AMT_LC,
INV_AMT_NOFEE_FC,
INV_AMT_NOFEE_LC,
TRAN_FEE_FC,
TRAN_FEE_LC,
TRUST_FEE_RATE,
TRUST_FEE_FC,
SHORTERM_RATE,
SHORTTERM_FEE_FC,
PL_FC,
PL_LC,
RETURN_FC,
RETURN_LC,
REDEM_TYPE,
SDG.UFN_MASK_ACCT(WITHDRAW_AC_NO),
SDG.UFN_MASK_ACCT(REDEM_AC_NO),
TRAN_STATUS,
RBL_YN,
ROBOT_TX_DATE,
TXN_NO_2,
IPM_INVEST_AMT,
BRAN_CODE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
