-- SQL for table: EDW_WMS_SFACUSTAOTXN_PRESTAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Prestage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Stage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFACUSTAOTXN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFACUSTAOTXN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFACUSTAOTXN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFACUSTAOTXN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFACUSTAOTXN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
-- SQL for table: EDW_WMS_SFACUSTAOTXN_PRESTAGE
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

-- Trinity SQL Script
/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
