-- SQL for table: EDW_CF_ACTCMP_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
CMPNAME,
ADDR,
ZIPNO1,
ZIPNO2,
TLRNO,
LUDATE,
HENTPNO,
CZONE,
CSRNO,
CEXT,
CPHONE,
NMFLG,
ADRFLG,
LUBRNO,
NMDATE,
EXTCNT,
CPHONECF,
CPHONEDT,
CPHONETM,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_MASK_ACCT(ACTNO),
SDG.UFN_MASK_NM(CMPNAME),
SDG.UFN_MASK_ADDR(ADDR),
ZIPNO1,
ZIPNO2,
TLRNO,
LUDATE,
SDG.UFN_MASK_BAN(HENTPNO),
CZONE,
SDG.UFN_MASK_TEL(CSRNO),
SDG.UFN_MASK_TEL(CEXT),
SDG.UFN_MASK_TEL(CPHONE),
NMFLG,
ADRFLG,
LUBRNO,
NMDATE,
EXTCNT,
CPHONECF,
CPHONEDT,
CPHONETM,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
