-- SQL for table: EDW_WEB031000_STAFFMEMBERSEXT_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DEPARTMENT_ID,
EMPLOYEE_ID,
NOTE,
OFFICEPHONE1,
OFFICEPHONE2,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DEPARTMENT_ID,
EMPLOYEE_ID,
NOTE,
OFFICEPHONE1,
OFFICEPHONE2,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
