-- SQL for table: EDW_CF_CIFEXT_PRESTAGE
-- Trinity SQL Script
/* TRANSFORM_DATA */

/* 1.Truncate 目的表 */
TRUNCATE TABLE ${TARGET_SCHEMA}.${TARGET_TABLE};

/* 
2. 抽取 正式區Stage DATA_EXCH_DATE='#資料交換期別#' 之資料
3. 遮罩後寫入驗證區Prestage 
*/
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
KEY,
"TYPE",
SEQ,
NAME,
LUBRNO,
TLRNO,
LUDATE,
LUTIME,
FUNCD,
FLAG1,
FLAG2,
FLAG3,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
若為8碼則使用ME2.統一編號, 若為12碼則使用ME10.銀行帳號,
"TYPE",
SEQ,
ME1.姓名/名稱,
LUBRNO,
TLRNO,
LUDATE,
LUTIME,
FUNCD,
FLAG1,
FLAG2,
FLAG3,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE ${DATA_LIFE_BASE} = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
