-- SQL for table: EDW_FC_FCTTF
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
TRCNT,
ISDAY,
EDAY,
DWCNT,
IRTID,
INIRT,
IRDAY,
AXCNT,
IVDAY,
UDIAMT,
TUDIAMT,
UDTAMT,
TUDTAMT,
DIAMT,
TDIAMT,
DTAMT,
TDTAMT,
CIAMT,
TCIAMT,
PRIBAL,
CTBAL,
EXPER,
TXDAY,
NHIAMT,
TNHIAMT,
"199KIND",
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO ||APNO ||SRNO ||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
TRCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISDAY))='0' THEN NULL ELSE ISDAY END) AS ISDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY))='0' THEN NULL ELSE EDAY END) AS EDAY,
DWCNT,
IRTID,
INIRT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IRDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IRDAY))='0' THEN NULL ELSE IRDAY END) AS IRDAY,
AXCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IVDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IVDAY))='0' THEN NULL ELSE IVDAY END) AS IVDAY,
UDIAMT,
TUDIAMT,
UDTAMT,
TUDTAMT,
DIAMT,
TDIAMT,
DTAMT,
TDTAMT,
CIAMT,
TCIAMT,
PRIBAL,
CTBAL,
EXPER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXDAY))='0' THEN NULL ELSE TXDAY END) AS TXDAY,
NHIAMT,
TNHIAMT,
"199KIND",
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
