-- SQL for table: EDW_FXF_FBCTL
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXDRDY' AS DATA_CHK_COL,
TXDRDY AS DATA_VAL,
SDG.UFN_NUMCHECK(TXDRDY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BKINF' AS DATA_CHK_COL,
BKINF AS DATA_VAL,
SDG.UFN_NUMCHECK(BKINF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXDT' AS DATA_CHK_COL,
EXDT AS DATA_VAL,
SDG.UFN_NUMCHECK(EXDT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FFBAS' AS DATA_CHK_COL,
FFBAS AS DATA_VAL,
SDG.UFN_NUMCHECK(FFBAS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FXDCLCNT' AS DATA_CHK_COL,
FXDCLCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(FXDCLCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FXDCLCNT2' AS DATA_CHK_COL,
FXDCLCNT2 AS DATA_VAL,
SDG.UFN_NUMCHECK(FXDCLCNT2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXF_FBCTL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BRNO,
FXLVL,
ACBRNO,
FBRNO,
TAKFG_01,
TAKFG_02,
TAKFG_03,
TAKFG_04,
TAKFG_05,
TAKFG_06,
TAKFG_07,
TAKFG_08,
TAKFG_09,
TAKFG_10,
RELFG_01,
RELFG_02,
RELFG_03,
RELFG_04,
RELFG_05,
RELFG_06,
RELFG_07,
RELFG_08,
RELFG_09,
RELFG_10,
MANFG,
XCRFG,
TXDRDY,
HOLDFG,
MODYFG,
KINBR,
TLRNO,
BRNAME,
BRADDR1,
BRADDR2,
BRSWFCD,
BRTELEX,
ADAREA,
ADTEL,
ADAREA1,
ADTEL1,
BCURCD,
BRCODE,
INQCODE,
CLSCD,
SPLFG,
ONFG,
LBSDY,
BKINF,
EXDT,
FFBAS,
OBUREL,
FXDCLCNT,
AESON,
FXDCLCNT2,
ATMFG,
ATMBIO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO,
FXLVL,
ACBRNO,
FBRNO,
TAKFG_01,
TAKFG_02,
TAKFG_03,
TAKFG_04,
TAKFG_05,
TAKFG_06,
TAKFG_07,
TAKFG_08,
TAKFG_09,
TAKFG_10,
RELFG_01,
RELFG_02,
RELFG_03,
RELFG_04,
RELFG_05,
RELFG_06,
RELFG_07,
RELFG_08,
RELFG_09,
RELFG_10,
MANFG,
XCRFG,
TXDRDY,
HOLDFG,
MODYFG,
KINBR,
TLRNO,
BRNAME,
BRADDR1,
BRADDR2,
BRSWFCD,
BRTELEX,
ADAREA,
ADTEL,
ADAREA1,
ADTEL1,
BCURCD,
BRCODE,
INQCODE,
CLSCD,
SPLFG,
ONFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LBSDY))='0' THEN NULL ELSE LBSDY END) AS LBSDY,
BKINF,
EXDT,
FFBAS,
OBUREL,
FXDCLCNT,
AESON,
FXDCLCNT2,
ATMFG,
ATMBIO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
