-- SQL for table: EDW_FXE_FBPMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO' AS DATA_CHK_COL,
CORPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DDAMT_1' AS DATA_CHK_COL,
DDAMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(DDAMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TENOR_1' AS DATA_CHK_COL,
TENOR_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(TENOR_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PIDD_1' AS DATA_CHK_COL,
PIDD_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(PIDD_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DDAMT_2' AS DATA_CHK_COL,
DDAMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(DDAMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TENOR_2' AS DATA_CHK_COL,
TENOR_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(TENOR_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PIDD_2' AS DATA_CHK_COL,
PIDD_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(PIDD_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DDAMT_3' AS DATA_CHK_COL,
DDAMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(DDAMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TENOR_3' AS DATA_CHK_COL,
TENOR_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(TENOR_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PIDD_3' AS DATA_CHK_COL,
PIDD_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(PIDD_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BPAMT' AS DATA_CHK_COL,
BPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UBPAMT' AS DATA_CHK_COL,
UBPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(UBPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OCAMT' AS DATA_CHK_COL,
OCAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OCAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UOCAMT' AS DATA_CHK_COL,
UOCAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(UOCAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PAYCOM' AS DATA_CHK_COL,
PAYCOM AS DATA_VAL,
SDG.UFN_NUMCHECK(PAYCOM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PAYEXP' AS DATA_CHK_COL,
PAYEXP AS DATA_VAL,
SDG.UFN_NUMCHECK(PAYEXP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UPCOM' AS DATA_CHK_COL,
UPCOM AS DATA_VAL,
SDG.UFN_NUMCHECK(UPCOM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UPEXP' AS DATA_CHK_COL,
UPEXP AS DATA_VAL,
SDG.UFN_NUMCHECK(UPEXP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DEFEXP' AS DATA_CHK_COL,
DEFEXP AS DATA_VAL,
SDG.UFN_NUMCHECK(DEFEXP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BRAMT' AS DATA_CHK_COL,
BRAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BRAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FPAMT' AS DATA_CHK_COL,
FPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(FPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SBAL' AS DATA_CHK_COL,
SBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(SBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVRAMT' AS DATA_CHK_COL,
OVRAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OVRAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UOVRAMT' AS DATA_CHK_COL,
UOVRAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(UOVRAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FEXPB' AS DATA_CHK_COL,
FEXPB AS DATA_VAL,
SDG.UFN_NUMCHECK(FEXPB) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FEXPC' AS DATA_CHK_COL,
FEXPC AS DATA_VAL,
SDG.UFN_NUMCHECK(FEXPC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RVEXP' AS DATA_CHK_COL,
RVEXP AS DATA_VAL,
SDG.UFN_NUMCHECK(RVEXP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ULNAMT' AS DATA_CHK_COL,
ULNAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ULNAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ULNBAL' AS DATA_CHK_COL,
ULNBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ULNBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ELNAMT' AS DATA_CHK_COL,
ELNAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ELNAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USCRAT' AS DATA_CHK_COL,
USCRAT AS DATA_VAL,
SDG.UFN_NUMCHECK(USCRAT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USCRAT2' AS DATA_CHK_COL,
USCRAT2 AS DATA_VAL,
SDG.UFN_NUMCHECK(USCRAT2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USRATS' AS DATA_CHK_COL,
USRATS AS DATA_VAL,
SDG.UFN_NUMCHECK(USRATS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SRATS' AS DATA_CHK_COL,
SRATS AS DATA_VAL,
SDG.UFN_NUMCHECK(SRATS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BRATS' AS DATA_CHK_COL,
BRATS AS DATA_VAL,
SDG.UFN_NUMCHECK(BRATS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LTAMT' AS DATA_CHK_COL,
LTAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(LTAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BPINT' AS DATA_CHK_COL,
BPINT AS DATA_VAL,
SDG.UFN_NUMCHECK(BPINT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DSINT' AS DATA_CHK_COL,
DSINT AS DATA_VAL,
SDG.UFN_NUMCHECK(DSINT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ERDAY' AS DATA_CHK_COL,
ERDAY AS DATA_VAL,
SDG.UFN_NUMCHECK(ERDAY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BRDAY' AS DATA_CHK_COL,
BRDAY AS DATA_VAL,
SDG.UFN_NUMCHECK(BRDAY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BRDAY2' AS DATA_CHK_COL,
BRDAY2 AS DATA_VAL,
SDG.UFN_NUMCHECK(BRDAY2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BRDAY3' AS DATA_CHK_COL,
BRDAY3 AS DATA_VAL,
SDG.UFN_NUMCHECK(BRDAY3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BPCNT' AS DATA_CHK_COL,
BPCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(BPCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BPNO' AS DATA_CHK_COL,
BPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(BPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CLSCNT' AS DATA_CHK_COL,
CLSCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CLSCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CLSNO' AS DATA_CHK_COL,
CLSNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CLSNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRCCNT' AS DATA_CHK_COL,
TRCCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TRCCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RPCNT' AS DATA_CHK_COL,
RPCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RPCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LNSEQ' AS DATA_CHK_COL,
LNSEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(LNSEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO' AS DATA_CHK_COL,
TXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CN' AS DATA_CHK_COL,
CN AS DATA_VAL,
SDG.UFN_NUMCHECK(CN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXE_FBPMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
CIFKEY,
CORPNO,
EPNO,
LCNO,
INVOICE,
MAILBR,
ISUBK,
ISWFCD,
PAYBK,
PSWFCD,
CNTRYCD,
BKCUR,
BKSRNO,
OC_1,
DDAMT_1,
LCTYP_1,
TENOR_1,
EDAY_1,
PIDD_1,
ACPDT_1,
CLDATE_1,
ACTDT_1,
OC_2,
DDAMT_2,
LCTYP_2,
TENOR_2,
EDAY_2,
PIDD_2,
ACPDT_2,
CLDATE_2,
ACTDT_2,
OC_3,
DDAMT_3,
LCTYP_3,
TENOR_3,
EDAY_3,
PIDD_3,
ACPDT_3,
CLDATE_3,
ACTDT_3,
LCCUR,
BPAMT,
UBPAMT,
OCAMT,
UOCAMT,
PAYCOM,
PAYEXP,
UPCOM,
UPEXP,
DEFEXP,
BRAMT,
FPAMT,
SBAL,
OVRAMT,
UOVRAMT,
FEXPB,
FEXPC,
RVEXP,
ULNAMT,
ULNBAL,
ELNAMT,
USCRAT,
USCRAT2,
USRATS,
SRATS,
BRATS,
LTAMT,
BPINT,
DSINT,
LASTDT,
NGTDAY,
ISUDT,
CLODAY,
TRCDY,
ERDAY,
BRDAY,
BRDAY2,
BRDAY3,
BPCNT,
BPNO,
CLSCNT,
CLSNO,
ACTCLS,
REMCD,
MLTYP,
LNCD,
TBFG,
TRCCNT,
SPCIAL,
RPCNT,
LNSEQ,
LNCUR,
GNDHL,
REDHL,
LTAPTYP,
LTBRNO,
LTSRNO,
TXTNO,
WSNO,
TLRNO,
CUSTOM,
CN,
CNGOODS,
OVDUACT,
BKCODE,
BKSWFCD,
NTXDAY,
IRNSWFCD,
EXNAL,
IMNAL,
FXFG,
GRCD,
GRKIND,
ESGCD,
ESGKIND,
ESGCNL,
GRTXCD,
GRDAY,
SRLOAN,
SRTYP,
SRGROUP,
SRPID,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
CIFKEY,
CORPNO,
EPNO,
LCNO,
INVOICE,
MAILBR,
ISUBK,
ISWFCD,
PAYBK,
PSWFCD,
CNTRYCD,
BKCUR,
BKSRNO,
OC_1,
DDAMT_1,
LCTYP_1,
TENOR_1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY_1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY_1))='0' THEN NULL ELSE EDAY_1 END) AS EDAY_1,
PIDD_1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACPDT_1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACPDT_1))='0' THEN NULL ELSE ACPDT_1 END) AS ACPDT_1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLDATE_1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLDATE_1))='0' THEN NULL ELSE CLDATE_1 END) AS CLDATE_1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACTDT_1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACTDT_1))='0' THEN NULL ELSE ACTDT_1 END) AS ACTDT_1,
OC_2,
DDAMT_2,
LCTYP_2,
TENOR_2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY_2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY_2))='0' THEN NULL ELSE EDAY_2 END) AS EDAY_2,
PIDD_2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACPDT_2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACPDT_2))='0' THEN NULL ELSE ACPDT_2 END) AS ACPDT_2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLDATE_2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLDATE_2))='0' THEN NULL ELSE CLDATE_2 END) AS CLDATE_2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACTDT_2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACTDT_2))='0' THEN NULL ELSE ACTDT_2 END) AS ACTDT_2,
OC_3,
DDAMT_3,
LCTYP_3,
TENOR_3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY_3), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY_3))='0' THEN NULL ELSE EDAY_3 END) AS EDAY_3,
PIDD_3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACPDT_3), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACPDT_3))='0' THEN NULL ELSE ACPDT_3 END) AS ACPDT_3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLDATE_3), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLDATE_3))='0' THEN NULL ELSE CLDATE_3 END) AS CLDATE_3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACTDT_3), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACTDT_3))='0' THEN NULL ELSE ACTDT_3 END) AS ACTDT_3,
LCCUR,
BPAMT,
UBPAMT,
OCAMT,
UOCAMT,
PAYCOM,
PAYEXP,
UPCOM,
UPEXP,
DEFEXP,
BRAMT,
FPAMT,
SBAL,
OVRAMT,
UOVRAMT,
FEXPB,
FEXPC,
RVEXP,
ULNAMT,
ULNBAL,
ELNAMT,
USCRAT,
USCRAT2,
USRATS,
SRATS,
BRATS,
LTAMT,
BPINT,
DSINT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NGTDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NGTDAY))='0' THEN NULL ELSE NGTDAY END) AS NGTDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISUDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISUDT))='0' THEN NULL ELSE ISUDT END) AS ISUDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLODAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLODAY))='0' THEN NULL ELSE CLODAY END) AS CLODAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TRCDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TRCDY))='0' THEN NULL ELSE TRCDY END) AS TRCDY,
ERDAY,
BRDAY,
BRDAY2,
BRDAY3,
BPCNT,
BPNO,
CLSCNT,
CLSNO,
ACTCLS,
REMCD,
MLTYP,
LNCD,
TBFG,
TRCCNT,
SPCIAL,
RPCNT,
LNSEQ,
LNCUR,
GNDHL,
REDHL,
LTAPTYP,
LTBRNO,
LTSRNO,
TXTNO,
WSNO,
TLRNO,
CUSTOM,
CN,
CNGOODS,
OVDUACT,
BKCODE,
BKSWFCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
IRNSWFCD,
EXNAL,
IMNAL,
FXFG,
GRCD,
GRKIND,
ESGCD,
ESGKIND,
ESGCNL,
GRTXCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRDAY))='0' THEN NULL ELSE GRDAY END) AS GRDAY,
SRLOAN,
SRTYP,
SRGROUP,
SRPID,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
