-- SQL for table: EDW_ELN_CRENVALSCOREBR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BOTMARK' AS DATA_CHK_COL,
BOTMARK AS DATA_VAL,
SDG.UFN_NUMCHECK(BOTMARK) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OUTSIDEMARK' AS DATA_CHK_COL,
OUTSIDEMARK AS DATA_VAL,
SDG.UFN_NUMCHECK(OUTSIDEMARK) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_01' AS DATA_CHK_COL,
SCORE_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_02' AS DATA_CHK_COL,
SCORE_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_03' AS DATA_CHK_COL,
SCORE_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_04' AS DATA_CHK_COL,
SCORE_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_05' AS DATA_CHK_COL,
SCORE_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_06' AS DATA_CHK_COL,
SCORE_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_07' AS DATA_CHK_COL,
SCORE_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_08' AS DATA_CHK_COL,
SCORE_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_09' AS DATA_CHK_COL,
SCORE_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_10' AS DATA_CHK_COL,
SCORE_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_11' AS DATA_CHK_COL,
SCORE_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_12' AS DATA_CHK_COL,
SCORE_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_13' AS DATA_CHK_COL,
SCORE_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_14' AS DATA_CHK_COL,
SCORE_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_15' AS DATA_CHK_COL,
SCORE_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_16' AS DATA_CHK_COL,
SCORE_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_17' AS DATA_CHK_COL,
SCORE_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_18' AS DATA_CHK_COL,
SCORE_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_19' AS DATA_CHK_COL,
SCORE_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_20' AS DATA_CHK_COL,
SCORE_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_21' AS DATA_CHK_COL,
SCORE_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_22' AS DATA_CHK_COL,
SCORE_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_23' AS DATA_CHK_COL,
SCORE_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_24' AS DATA_CHK_COL,
SCORE_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_25' AS DATA_CHK_COL,
SCORE_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_26' AS DATA_CHK_COL,
SCORE_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_27' AS DATA_CHK_COL,
SCORE_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_28' AS DATA_CHK_COL,
SCORE_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_29' AS DATA_CHK_COL,
SCORE_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_30' AS DATA_CHK_COL,
SCORE_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_31' AS DATA_CHK_COL,
SCORE_31 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_31) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_32' AS DATA_CHK_COL,
SCORE_32 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_32) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_33' AS DATA_CHK_COL,
SCORE_33 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_33) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_34' AS DATA_CHK_COL,
SCORE_34 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_34) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_35' AS DATA_CHK_COL,
SCORE_35 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_35) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_36' AS DATA_CHK_COL,
SCORE_36 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_36) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_37' AS DATA_CHK_COL,
SCORE_37 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_37) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_38' AS DATA_CHK_COL,
SCORE_38 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_38) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_39' AS DATA_CHK_COL,
SCORE_39 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_39) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_40' AS DATA_CHK_COL,
SCORE_40 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_40) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_41' AS DATA_CHK_COL,
SCORE_41 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_41) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_42' AS DATA_CHK_COL,
SCORE_42 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_42) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_43' AS DATA_CHK_COL,
SCORE_43 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_43) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_44' AS DATA_CHK_COL,
SCORE_44 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_44) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCORE_45' AS DATA_CHK_COL,
SCORE_45 AS DATA_VAL,
SDG.UFN_NUMCHECK(SCORE_45) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_ELN_CRENVALSCOREBR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CASEID,
IDBAN,
CRRPTNO,
INDUNO,
GRADEYEAR,
REMARKS,
BOTMARK,
BOTRANK,
OUTSIDEMARK,
OUTSIDERANK,
SCORE_01,
SCORE_02,
SCORE_03,
SCORE_04,
SCORE_05,
SCORE_06,
SCORE_07,
SCORE_08,
SCORE_09,
SCORE_10,
SCORE_11,
SCORE_12,
SCORE_13,
SCORE_14,
SCORE_15,
SCORE_16,
SCORE_17,
SCORE_18,
SCORE_19,
SCORE_20,
SCORE_21,
SCORE_22,
SCORE_23,
SCORE_24,
SCORE_25,
SCORE_26,
SCORE_27,
SCORE_28,
SCORE_29,
SCORE_30,
SCORE_31,
SCORE_32,
SCORE_33,
SCORE_34,
SCORE_35,
SCORE_36,
SCORE_37,
SCORE_38,
SCORE_39,
SCORE_40,
SCORE_41,
SCORE_42,
SCORE_43,
SCORE_44,
SCORE_45,
CRRPTER,
CRRPTDATE,
ENDDATE,
ENVALFLAG,
IND_GI,
BREACH,
BCDATE,
ISTDT,
ODDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASEID,
IDBAN,
CRRPTNO,
INDUNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRADEYEAR), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRADEYEAR))='0' THEN NULL ELSE GRADEYEAR END) AS GRADEYEAR,
REMARKS,
BOTMARK,
BOTRANK,
OUTSIDEMARK,
OUTSIDERANK,
SCORE_01,
SCORE_02,
SCORE_03,
SCORE_04,
SCORE_05,
SCORE_06,
SCORE_07,
SCORE_08,
SCORE_09,
SCORE_10,
SCORE_11,
SCORE_12,
SCORE_13,
SCORE_14,
SCORE_15,
SCORE_16,
SCORE_17,
SCORE_18,
SCORE_19,
SCORE_20,
SCORE_21,
SCORE_22,
SCORE_23,
SCORE_24,
SCORE_25,
SCORE_26,
SCORE_27,
SCORE_28,
SCORE_29,
SCORE_30,
SCORE_31,
SCORE_32,
SCORE_33,
SCORE_34,
SCORE_35,
SCORE_36,
SCORE_37,
SCORE_38,
SCORE_39,
SCORE_40,
SCORE_41,
SCORE_42,
SCORE_43,
SCORE_44,
SCORE_45,
CRRPTER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CRRPTDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CRRPTDATE))='0' THEN NULL ELSE CRRPTDATE END) AS CRRPTDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ENDDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ENDDATE))='0' THEN NULL ELSE ENDDATE END) AS ENDDATE,
ENVALFLAG,
IND_GI,
BREACH,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BCDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BCDATE))='0' THEN NULL ELSE BCDATE END) AS BCDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISTDT))='0' THEN NULL ELSE ISTDT END) AS ISTDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ODDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ODDATE))='0' THEN NULL ELSE ODDATE END) AS ODDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
