-- SQL for table: EDW_FC_FCCHG
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MACTNO,
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
LTXDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO ||MAPNO ||MSRNO ||MCHKDG,
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(YYMM), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(YYMM))='0' THEN NULL ELSE YYMM END) AS YYMM,
CHGAMT,
CHGBAL,
CHGDIS,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTXDAY))='0' THEN NULL ELSE LTXDAY END) AS LTXDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
