-- SQL for table: EDW_CF_CIFCMP
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ENTPNO' AS DATA_CHK_COL,
ENTPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(ENTPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_CF_CIFCMP
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ENTPNO,
PIDNO,
NAME,
CMPNAME,
ACTADDR,
ZIPNO1,
ZIPNO2,
ADDR,
HENTPNO,
LUDATE,
LUACTNO,
BIRDAY,
"TYPE",
CZONE,
CSRNO,
CEXT,
OZONE,
OSRNO,
OEXT,
FZONE,
FSRNO,
NATION,
SPNO,
OPENDT,
TLRNO,
BRNO,
EMAIL,
ALLIANCE,
BIRTYPE,
TRADENO,
BKIND,
CPHONE,
CRDATE,
TAXCD,
BCODE,
FLAG,
CTTADDR,
CTTZIP1,
CTTZIP2,
CTTDATE,
CTTBRNO,
CTTTLRNO,
CTTSPNO,
NMDATE,
EMAILCD,
BTFLAG,
REGIST,
CTTZONE,
CTTSRNO,
CLASS,
EXTCNT,
CMPFLAG,
CPHONECF,
CPHONEDATE,
CPHONETIME,
EMAILCF,
EMAILDATE,
EMAILTIME,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ENTPNO,
PIDNO,
NAME,
CMPNAME,
ACTADDR,
ZIPNO1,
ZIPNO2,
ADDR,
HENTPNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LUDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LUDATE))='0' THEN NULL ELSE LUDATE END) AS LUDATE,
LUACTNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BIRDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BIRDAY))='0' THEN NULL ELSE BIRDAY END) AS BIRDAY,
"TYPE",
CZONE,
CSRNO,
CEXT,
OZONE,
OSRNO,
OEXT,
FZONE,
FSRNO,
NATION,
SPNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPENDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPENDT))='0' THEN NULL ELSE OPENDT END) AS OPENDT,
TLRNO,
BRNO,
EMAIL,
ALLIANCE,
BIRTYPE,
TRADENO,
BKIND,
CPHONE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CRDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CRDATE))='0' THEN NULL ELSE CRDATE END) AS CRDATE,
TAXCD,
BCODE,
FLAG,
CTTADDR,
CTTZIP1,
CTTZIP2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CTTDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CTTDATE))='0' THEN NULL ELSE CTTDATE END) AS CTTDATE,
CTTBRNO,
CTTTLRNO,
CTTSPNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NMDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NMDATE))='0' THEN NULL ELSE NMDATE END) AS NMDATE,
EMAILCD,
BTFLAG,
REGIST,
CTTZONE,
CTTSRNO,
CLASS,
EXTCNT,
CMPFLAG,
CPHONECF,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CPHONEDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CPHONEDATE))='0' THEN NULL ELSE CPHONEDATE END) AS CPHONEDATE,
CPHONETIME,
EMAILCF,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EMAILDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EMAILDATE))='0' THEN NULL ELSE EMAILDATE END) AS EMAILDATE,
EMAILTIME,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
