-- SQL for table: EDW_ATMP_CDLOG
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
REC,
SPDT,
ATMNO,
BRNO,
WSNO,
ATMNO_N,
TXDATE,
TIME2,
TMOUT,
TXCD,
TXSEQ,
BKNO,
ACTNO,
TXAMT,
ACCEPT,
RSFLG,
RJCD,
INBKKEY,
TEXT,
CARDNO,
TXCD_1,
CURCD,
NATIONAL,
CRDKIND,
TPAN,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
REC,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SPDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SPDT))='0' THEN NULL ELSE SPDT END) AS SPDT,
ATMNO,
BRNO,
WSNO,
ATMNO_N,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXDATE))='0' THEN NULL ELSE TXDATE END) AS TXDATE,
TIME2,
TMOUT,
TXCD,
TXSEQ,
BKNO,
ACTNO,
TXAMT,
ACCEPT,
RSFLG,
RJCD,
INBKKEY,
TEXT,
CARDNO,
TXCD_1,
CURCD,
NATIONAL,
CRDKIND,
TPAN,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
