-- SQL for table: EDW_IFRS9_LNIADTL
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DURATION' AS DATA_CHK_COL,
DURATION AS DATA_VAL,
SDG.UFN_NUMCHECK(DURATION) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PD' AS DATA_CHK_COL,
PD AS DATA_VAL,
SDG.UFN_NUMCHECK(PD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LGD' AS DATA_CHK_COL,
LGD AS DATA_VAL,
SDG.UFN_NUMCHECK(LGD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACC_CD_BAL' AS DATA_CHK_COL,
ACC_CD_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ACC_CD_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_AMORTIZE_DISC_AMT' AS DATA_CHK_COL,
NO_AMORTIZE_DISC_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_AMORTIZE_DISC_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_AMORTIZE_ADD_AMT' AS DATA_CHK_COL,
NO_AMORTIZE_ADD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_AMORTIZE_ADD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCT_AMT' AS DATA_CHK_COL,
ACCT_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCT_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DEAL_RATE' AS DATA_CHK_COL,
DEAL_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(DEAL_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EIR' AS DATA_CHK_COL,
EIR AS DATA_VAL,
SDG.UFN_NUMCHECK(EIR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL' AS DATA_CHK_COL,
IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_RATE' AS DATA_CHK_COL,
IA_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LS_MON_IA_BAL' AS DATA_CHK_COL,
LS_MON_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(LS_MON_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL_DIFF' AS DATA_CHK_COL,
IA_BAL_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FULL_COLL_AMT' AS DATA_CHK_COL,
FULL_COLL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(FULL_COLL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_COLL_AMT' AS DATA_CHK_COL,
NO_COLL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_COLL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NOT_RECVY_AMT' AS DATA_CHK_COL,
NOT_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NOT_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL1_LOAN_BAL' AS DATA_CHK_COL,
NPL1_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL1_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL2_LOAN_BAL' AS DATA_CHK_COL,
NPL2_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL2_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL3_LOAN_BAL' AS DATA_CHK_COL,
NPL3_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL3_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL4_LOAN_BAL' AS DATA_CHK_COL,
NPL4_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL4_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL5_LOAN_BAL' AS DATA_CHK_COL,
NPL5_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL5_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_BAL_AMT' AS DATA_CHK_COL,
NPL_BAL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_BAL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_RATIO' AS DATA_CHK_COL,
NPL_RATIO AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_RATIO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_BAL_AMT_DIFF' AS DATA_CHK_COL,
NPL_BAL_AMT_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_BAL_AMT_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_RECV_AMT' AS DATA_CHK_COL,
INT_RECV_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_RECV_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_IA_AMT' AS DATA_CHK_COL,
INT_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NOUSE_LMT_BAL' AS DATA_CHK_COL,
NOUSE_LMT_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NOUSE_LMT_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CCF' AS DATA_CHK_COL,
CCF AS DATA_VAL,
SDG.UFN_NUMCHECK(CCF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_COMMIT_AMT' AS DATA_CHK_COL,
CR_COMMIT_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_COMMIT_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_COMMIT_IA_AMT' AS DATA_CHK_COL,
CR_COMMIT_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_COMMIT_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ADV_PAY_AMT' AS DATA_CHK_COL,
ADV_PAY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ADV_PAY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ADV_PAY_IA_AMT' AS DATA_CHK_COL,
ADV_PAY_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ADV_PAY_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVDUE_MON' AS DATA_CHK_COL,
OVDUE_MON AS DATA_VAL,
SDG.UFN_NUMCHECK(OVDUE_MON) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVDUE_RECV_BAL' AS DATA_CHK_COL,
OVDUE_RECV_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(OVDUE_RECV_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAD_DEBT_AMT' AS DATA_CHK_COL,
BAD_DEBT_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BAD_DEBT_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LOAN_BAL' AS DATA_CHK_COL,
LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_IA_BAL' AS DATA_CHK_COL,
ORIG_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_IA_RATE' AS DATA_CHK_COL,
ORIG_IA_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_IA_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_INT_RECV_AMT' AS DATA_CHK_COL,
ORIG_INT_RECV_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_INT_RECV_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_ADV_PAY_IA_AMT' AS DATA_CHK_COL,
ORIG_ADV_PAY_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_ADV_PAY_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_IFRS9_LNIADTL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
VER_NO,
BRN_ID,
BRN_NM,
ACCT_NO,
CUST_ID,
CUST_NM,
BUS_TYP,
BUS_TYP_NM,
IS_SCHOOL_LOAN,
ACC_CD_ALL,
ACC_CD_TYP,
BKIND,
BCODE,
CHARCD,
COLL_TYP,
COLL_TYP_NM,
COLL_CATG_ID,
COLL_CATG_NM,
R0401CD,
DEAL_BEG_DATE,
DEAL_END_DATE,
ORIG_VERIFY_DATE,
ORIG_RANK_CATG,
ORIG_RANK_CATG_NM,
ORIG_RANK,
ORIG_IRB_RANK,
CUR_RANK_CATG,
CUR_RANK_CATG_NM,
CUR_RANK,
CUR_IRB_RANK,
IRB_RANK_CHG_AMT,
REVW_GRADE,
WARN_LEVEL,
RESN_CODE,
BAD_DEBT_MARK,
DURATION,
PD_GROUP_ID,
PD_GROUP_NM,
PD,
LGD_GROUP_ID,
LGD_GROUP_NM,
LGD,
ACC_CD_BAL,
NO_AMORTIZE_DISC_AMT,
NO_AMORTIZE_ADD_AMT,
ACCT_AMT,
DEAL_RATE,
EIR,
STAGE,
IA_BAL,
IA_RATE,
LS_MON_STAGE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
FULL_COLL_AMT,
NO_COLL_AMT,
NOT_RECVY_AMT,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
INT_RECV_AMT,
INT_IA_AMT,
CYCLE_MARK,
IS_CANCEL_MARK,
NOUSE_LMT_BAL,
CCF,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
ADV_PAY_AMT,
ADV_PAY_IA_AMT,
OVDUE_MON,
IA_DATE,
XFER_COLTN_DATE,
OVDUE_RECV_BAL,
XFER_BAD_DATE,
BAD_DEBT_AMT,
LOAN_BAL,
COLL_STS,
COLL_STS_NM,
ORIG_IA_BAL,
ORIG_IA_RATE,
ORIG_INT_RECV_AMT,
ORIG_ADV_PAY_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATA_YM), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATA_YM))='0' THEN '0001-01-01' ELSE DATA_YM END) AS DATA_YM,
VER_NO,
BRN_ID,
BRN_NM,
ACCT_NO,
CUST_ID,
CUST_NM,
BUS_TYP,
BUS_TYP_NM,
IS_SCHOOL_LOAN,
ACC_CD_ALL,
ACC_CD_TYP,
BKIND,
BCODE,
CHARCD,
COLL_TYP,
COLL_TYP_NM,
COLL_CATG_ID,
COLL_CATG_NM,
R0401CD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEAL_BEG_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEAL_BEG_DATE))='0' THEN NULL ELSE DEAL_BEG_DATE END) AS DEAL_BEG_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEAL_END_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEAL_END_DATE))='0' THEN NULL ELSE DEAL_END_DATE END) AS DEAL_END_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ORIG_VERIFY_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ORIG_VERIFY_DATE))='0' THEN NULL ELSE ORIG_VERIFY_DATE END) AS ORIG_VERIFY_DATE,
ORIG_RANK_CATG,
ORIG_RANK_CATG_NM,
ORIG_RANK,
ORIG_IRB_RANK,
CUR_RANK_CATG,
CUR_RANK_CATG_NM,
CUR_RANK,
CUR_IRB_RANK,
IRB_RANK_CHG_AMT,
REVW_GRADE,
WARN_LEVEL,
RESN_CODE,
BAD_DEBT_MARK,
DURATION,
PD_GROUP_ID,
PD_GROUP_NM,
PD,
LGD_GROUP_ID,
LGD_GROUP_NM,
LGD,
ACC_CD_BAL,
NO_AMORTIZE_DISC_AMT,
NO_AMORTIZE_ADD_AMT,
ACCT_AMT,
DEAL_RATE,
EIR,
STAGE,
IA_BAL,
IA_RATE,
LS_MON_STAGE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
FULL_COLL_AMT,
NO_COLL_AMT,
NOT_RECVY_AMT,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
INT_RECV_AMT,
INT_IA_AMT,
CYCLE_MARK,
IS_CANCEL_MARK,
NOUSE_LMT_BAL,
CCF,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
ADV_PAY_AMT,
ADV_PAY_IA_AMT,
OVDUE_MON,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IA_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IA_DATE))='0' THEN NULL ELSE IA_DATE END) AS IA_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(XFER_COLTN_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(XFER_COLTN_DATE))='0' THEN NULL ELSE XFER_COLTN_DATE END) AS XFER_COLTN_DATE,
OVDUE_RECV_BAL,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(XFER_BAD_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(XFER_BAD_DATE))='0' THEN NULL ELSE XFER_BAD_DATE END) AS XFER_BAD_DATE,
BAD_DEBT_AMT,
LOAN_BAL,
COLL_STS,
COLL_STS_NM,
ORIG_IA_BAL,
ORIG_IA_RATE,
ORIG_INT_RECV_AMT,
ORIG_ADV_PAY_IA_AMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CAL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CAL_DATE))='0' THEN NULL ELSE CAL_DATE END) AS CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
