-- SQL for table: EDW_FXB_FRCTR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
TRCNT,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CIFKEY,
CORPNO,
CLRCUR,
CLRSRNO,
CLODAT,
RECDAT,
RECAMT,
ADVDAT,
ACFLG,
COLAMT,
RECTYP,
SVCFEE,
XRATE,
NTEXP,
RECDOC,
RVSCOD,
THEIR,
TXTNO,
LASTDT,
TLRNO,
WSNO,
RTNDAT,
OTAMT,
COST,
USECD,
CUSTOM,
CN,
EXAMT,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
TRCNT,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CIFKEY,
CORPNO,
CLRCUR,
CLRSRNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLODAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLODAT))='0' THEN NULL ELSE CLODAT END) AS CLODAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RECDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RECDAT))='0' THEN NULL ELSE RECDAT END) AS RECDAT,
RECAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ADVDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ADVDAT))='0' THEN NULL ELSE ADVDAT END) AS ADVDAT,
ACFLG,
COLAMT,
RECTYP,
SVCFEE,
XRATE,
NTEXP,
RECDOC,
RVSCOD,
THEIR,
TXTNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
TLRNO,
WSNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RTNDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RTNDAT))='0' THEN NULL ELSE RTNDAT END) AS RTNDAT,
OTAMT,
COST,
USECD,
CUSTOM,
CN,
EXAMT,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
