-- SQL for table: EDW_AROBO_CUSTRANS
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FX_RATE' AS DATA_CHK_COL,
FX_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(FX_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UNIT' AS DATA_CHK_COL,
UNIT AS DATA_VAL,
SDG.UFN_NUMCHECK(UNIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRICE' AS DATA_CHK_COL,
PRICE AS DATA_VAL,
SDG.UFN_NUMCHECK(PRICE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRAN_AMT_FC' AS DATA_CHK_COL,
TRAN_AMT_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(TRAN_AMT_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRAN_AMT_LC' AS DATA_CHK_COL,
TRAN_AMT_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(TRAN_AMT_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRAN_AMT_NOFEE_FC' AS DATA_CHK_COL,
TRAN_AMT_NOFEE_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(TRAN_AMT_NOFEE_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRAN_AMT_NOFEE_LC' AS DATA_CHK_COL,
TRAN_AMT_NOFEE_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(TRAN_AMT_NOFEE_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INV_AMT_FC' AS DATA_CHK_COL,
INV_AMT_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(INV_AMT_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INV_AMT_LC' AS DATA_CHK_COL,
INV_AMT_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(INV_AMT_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INV_AMT_NOFEE_FC' AS DATA_CHK_COL,
INV_AMT_NOFEE_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(INV_AMT_NOFEE_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INV_AMT_NOFEE_LC' AS DATA_CHK_COL,
INV_AMT_NOFEE_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(INV_AMT_NOFEE_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRAN_FEE_FC' AS DATA_CHK_COL,
TRAN_FEE_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(TRAN_FEE_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRAN_FEE_LC' AS DATA_CHK_COL,
TRAN_FEE_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(TRAN_FEE_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRUST_FEE_RATE' AS DATA_CHK_COL,
TRUST_FEE_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(TRUST_FEE_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRUST_FEE_FC' AS DATA_CHK_COL,
TRUST_FEE_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(TRUST_FEE_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SHORTERM_RATE' AS DATA_CHK_COL,
SHORTERM_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(SHORTERM_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SHORTTERM_FEE_FC' AS DATA_CHK_COL,
SHORTTERM_FEE_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(SHORTTERM_FEE_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PL_FC' AS DATA_CHK_COL,
PL_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(PL_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PL_LC' AS DATA_CHK_COL,
PL_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(PL_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RETURN_FC' AS DATA_CHK_COL,
RETURN_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(RETURN_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RETURN_LC' AS DATA_CHK_COL,
RETURN_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(RETURN_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IPM_INVEST_AMT' AS DATA_CHK_COL,
IPM_INVEST_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(IPM_INVEST_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_AROBO_CUSTRANS
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
INV_TYPE,
TRAN_CODE,
CHANNEL,
TRAN_TYPE,
TXN_NO,
IPMSET_CODE,
CUS_CODE,
PRO_CODE,
TRAN_CUR_CODE,
FX_RATE,
TRAN_DATE,
ORDER_DATE,
DISTRIBUTE_DATE,
SETTLE_DATE,
UNIT,
PRICE_DATE,
PRICE,
TRAN_AMT_FC,
TRAN_AMT_LC,
TRAN_AMT_NOFEE_FC,
TRAN_AMT_NOFEE_LC,
INV_AMT_FC,
INV_AMT_LC,
INV_AMT_NOFEE_FC,
INV_AMT_NOFEE_LC,
TRAN_FEE_FC,
TRAN_FEE_LC,
TRUST_FEE_RATE,
TRUST_FEE_FC,
SHORTERM_RATE,
SHORTTERM_FEE_FC,
PL_FC,
PL_LC,
RETURN_FC,
RETURN_LC,
REDEM_TYPE,
WITHDRAW_AC_NO,
REDEM_AC_NO,
TRAN_STATUS,
RBL_YN,
ROBOT_TX_DATE,
TXN_NO,
IPM_INVEST_AMT,
BRAN_CODE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
INV_TYPE,
TRAN_CODE,
CHANNEL,
TRAN_TYPE,
TXN_NO,
IPMSET_CODE,
CUS_CODE,
PRO_CODE,
TRAN_CUR_CODE,
FX_RATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TRAN_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TRAN_DATE))='0' THEN NULL ELSE TRAN_DATE END) AS TRAN_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ORDER_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ORDER_DATE))='0' THEN NULL ELSE ORDER_DATE END) AS ORDER_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DISTRIBUTE_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DISTRIBUTE_DATE))='0' THEN NULL ELSE DISTRIBUTE_DATE END) AS DISTRIBUTE_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SETTLE_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SETTLE_DATE))='0' THEN NULL ELSE SETTLE_DATE END) AS SETTLE_DATE,
UNIT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRICE_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRICE_DATE))='0' THEN NULL ELSE PRICE_DATE END) AS PRICE_DATE,
PRICE,
TRAN_AMT_FC,
TRAN_AMT_LC,
TRAN_AMT_NOFEE_FC,
TRAN_AMT_NOFEE_LC,
INV_AMT_FC,
INV_AMT_LC,
INV_AMT_NOFEE_FC,
INV_AMT_NOFEE_LC,
TRAN_FEE_FC,
TRAN_FEE_LC,
TRUST_FEE_RATE,
TRUST_FEE_FC,
SHORTERM_RATE,
SHORTTERM_FEE_FC,
PL_FC,
PL_LC,
RETURN_FC,
RETURN_LC,
REDEM_TYPE,
WITHDRAW_AC_NO,
REDEM_AC_NO,
TRAN_STATUS,
RBL_YN,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ROBOT_TX_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ROBOT_TX_DATE))='0' THEN NULL ELSE ROBOT_TX_DATE END) AS ROBOT_TX_DATE,
TXN_NO,
IPM_INVEST_AMT,
BRAN_CODE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
