-- SQL for table: EDW_LNL_LNMON
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BUIAMT' AS DATA_CHK_COL,
BUIAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BUIAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ENDAMT' AS DATA_CHK_COL,
ENDAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ENDAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_LNL_LNMON
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
INDCD,
LLCD,
BPCD,
CURVCD,
BUILDCD,
BUILDDAY,
ACCD,
BYCD,
BYOTHER,
BNCD,
BNOTHER,
CLOSECD,
TURNCD,
FUNDUSE,
RENTCD,
APLBDAY,
CLOSEDAY,
ENDDATE,
LICENCE,
LICNO,
LICDATE,
LICFLG,
BUIAMT,
ENDAMT,
LASTDT,
LICAREA,
LANDFLG,
RBAREA,
APLBDAYUD,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
INDCD,
LLCD,
BPCD,
CURVCD,
BUILDCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BUILDDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BUILDDAY))='0' THEN NULL ELSE BUILDDAY END) AS BUILDDAY,
ACCD,
BYCD,
BYOTHER,
BNCD,
BNOTHER,
CLOSECD,
TURNCD,
FUNDUSE,
RENTCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APLBDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APLBDAY))='0' THEN NULL ELSE APLBDAY END) AS APLBDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLOSEDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLOSEDAY))='0' THEN NULL ELSE CLOSEDAY END) AS CLOSEDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ENDDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ENDDATE))='0' THEN NULL ELSE ENDDATE END) AS ENDDATE,
LICENCE,
LICNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LICDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LICDATE))='0' THEN NULL ELSE LICDATE END) AS LICDATE,
LICFLG,
BUIAMT,
ENDAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
LICAREA,
LANDFLG,
RBAREA,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APLBDAYUD), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APLBDAYUD))='0' THEN NULL ELSE APLBDAYUD END) AS APLBDAYUD,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
