-- SQL for table: EDW_FXB_FRCMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CURCD,
COLAMT,
COLDAT,
RECTYP,
TXCNT,
RJTSUM,
COLSUM,
RECSUM,
RJTAMT,
PAYAMT,
BALAMT,
MAILBK,
MSWFCD,
PRCLDAT,
TRCCNT,
TRCDAT,
RECCNT,
LRECDAT,
TRCNT,
TXTNO,
WSNO,
LASTDT,
TLRNO,
RJTCNT,
LRJTDAT,
NTXDAY,
RCKIND,
CIFKEY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CURCD,
COLAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(COLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(COLDAT))='0' THEN NULL ELSE COLDAT END) AS COLDAT,
RECTYP,
TXCNT,
RJTSUM,
COLSUM,
RECSUM,
RJTAMT,
PAYAMT,
BALAMT,
MAILBK,
MSWFCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRCLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRCLDAT))='0' THEN NULL ELSE PRCLDAT END) AS PRCLDAT,
TRCCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TRCDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TRCDAT))='0' THEN NULL ELSE TRCDAT END) AS TRCDAT,
RECCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRECDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRECDAT))='0' THEN NULL ELSE LRECDAT END) AS LRECDAT,
TRCNT,
TXTNO,
WSNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
TLRNO,
RJTCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRJTDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRJTDAT))='0' THEN NULL ELSE LRJTDAT END) AS LRJTDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
RCKIND,
CIFKEY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
