-- SQL for table: EDW_PB_PBTTR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
CALDY,
CALTM,
KINBR,
TRMSEQ,
FILLER1,
TRMTYP,
TXCODE,
TLRNO,
DSCPT,
CRDB,
TXAMT,
TAXAMT,
ENTDAY,
HCODE,
CDTX,
AFCLS,
CKNO,
RFINT,
RGBNO,
DSPTYPE,
DSPTKD,
DSPTEXT,
TXTYPE,
TRNMOD,
BDTXD,
COKEY,
COBKNO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO ||APNO ||SRNO ||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CALDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CALDY))='0' THEN NULL ELSE CALDY END) AS CALDY,
CALTM,
KINBR,
TRMSEQ,
FILLER1,
TRMTYP,
TXCODE,
TLRNO,
DSCPT,
CRDB,
TXAMT,
TAXAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ENTDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ENTDAY))='0' THEN NULL ELSE ENTDAY END) AS ENTDAY,
HCODE,
CDTX,
AFCLS,
CKNO,
RFINT,
RGBNO,
DSPTYPE,
DSPTKD,
DSPTEXT,
TXTYPE,
TRNMOD,
BDTXD,
COKEY,
COBKNO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
