-- SQL for table: EDW_IFRS9_GRIADTL
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DURATION' AS DATA_CHK_COL,
DURATION AS DATA_VAL,
SDG.UFN_NUMCHECK(DURATION) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PD' AS DATA_CHK_COL,
PD AS DATA_VAL,
SDG.UFN_NUMCHECK(PD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LGD' AS DATA_CHK_COL,
LGD AS DATA_VAL,
SDG.UFN_NUMCHECK(LGD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GUAR_AMT' AS DATA_CHK_COL,
GUAR_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(GUAR_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PREP_INCOME' AS DATA_CHK_COL,
PREP_INCOME AS DATA_VAL,
SDG.UFN_NUMCHECK(PREP_INCOME) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CCF' AS DATA_CHK_COL,
CCF AS DATA_VAL,
SDG.UFN_NUMCHECK(CCF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EVAL_CAN_USE_AMT' AS DATA_CHK_COL,
EVAL_CAN_USE_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EVAL_CAN_USE_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_COMMIT_AMT' AS DATA_CHK_COL,
CR_COMMIT_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_COMMIT_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_COMMIT_IA_AMT' AS DATA_CHK_COL,
CR_COMMIT_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_COMMIT_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EVAL_NOLOSS_AMT' AS DATA_CHK_COL,
EVAL_NOLOSS_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EVAL_NOLOSS_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GUAR_IA_BAL' AS DATA_CHK_COL,
GUAR_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(GUAR_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GUAR_IA_RATE' AS DATA_CHK_COL,
GUAR_IA_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(GUAR_IA_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL' AS DATA_CHK_COL,
IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_RATE' AS DATA_CHK_COL,
IA_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LS_MON_IA_BAL' AS DATA_CHK_COL,
LS_MON_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(LS_MON_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL_DIFF' AS DATA_CHK_COL,
IA_BAL_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FULL_COLL_AMT' AS DATA_CHK_COL,
FULL_COLL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(FULL_COLL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_COLL_AMT' AS DATA_CHK_COL,
NO_COLL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_COLL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NOT_RECVY_AMT' AS DATA_CHK_COL,
NOT_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NOT_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL1_LOAN_BAL' AS DATA_CHK_COL,
NPL1_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL1_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL2_LOAN_BAL' AS DATA_CHK_COL,
NPL2_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL2_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL3_LOAN_BAL' AS DATA_CHK_COL,
NPL3_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL3_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL4_LOAN_BAL' AS DATA_CHK_COL,
NPL4_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL4_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL5_LOAN_BAL' AS DATA_CHK_COL,
NPL5_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL5_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_BAL_AMT' AS DATA_CHK_COL,
NPL_BAL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_BAL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_RATIO' AS DATA_CHK_COL,
NPL_RATIO AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_RATIO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_BAL_AMT_DIFF' AS DATA_CHK_COL,
NPL_BAL_AMT_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_BAL_AMT_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PROFIT_RECV' AS DATA_CHK_COL,
PROFIT_RECV AS DATA_VAL,
SDG.UFN_NUMCHECK(PROFIT_RECV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PROFIT_ALOW_BAD_AMT' AS DATA_CHK_COL,
PROFIT_ALOW_BAD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PROFIT_ALOW_BAD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVDUE_MON' AS DATA_CHK_COL,
OVDUE_MON AS DATA_VAL,
SDG.UFN_NUMCHECK(OVDUE_MON) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_IFRS9_GRIADTL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
VER_NO,
BRN_ID,
BRN_NM,
ACCT_NO,
ACCT_SUBNO,
ASSET_ID,
CUST_ID,
CUST_NM,
BUS_TYP,
BUS_TYP_NM,
IS_SCHOOL_LOAN,
ACC_CD_ALL,
ACC_CD_TYP,
BKIND,
BCODE,
CHARCD,
COLL_TYP,
COLL_TYP_NM,
COLL_CATG_ID,
COLL_CATG_NM,
R0401CD,
DEAL_BEG_DATE,
DEAL_END_DATE,
ORIG_VERIFY_DATE,
ORIG_RANK_CATG,
ORIG_RANK_CATG_NM,
ORIG_RANK,
ORIG_IRB_RANK,
CUR_RANK_CATG,
CUR_RANK_CATG_NM,
CUR_RANK,
CUR_IRB_RANK,
IRB_RANK_CHG_AMT,
REVW_GRADE,
WARN_LEVEL,
RESN_CODE,
BAD_DEBT_MARK,
DURATION,
PD_GROUP_ID,
PD_GROUP_NM,
PD,
LGD_GROUP_ID,
LGD_GROUP_NM,
LGD,
GUAR_AMT,
PREP_INCOME,
CYCLE_MARK,
IS_CANCEL_MARK,
CCF,
EVAL_CAN_USE_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
EVAL_NOLOSS_AMT,
GUAR_IA_BAL,
GUAR_IA_RATE,
STAGE,
IA_BAL,
IA_RATE,
LS_MON_STAGE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
FULL_COLL_AMT,
NO_COLL_AMT,
NOT_RECVY_AMT,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
OVDUE_MON,
EVAL_BRN_ID,
EVAL_BRN_NM,
EVAL_DATE,
CASE_REL_DATE,
EVAL_DESCR,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATA_YM), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATA_YM))='0' THEN '0001-01-01' ELSE DATA_YM END) AS DATA_YM,
VER_NO,
BRN_ID,
BRN_NM,
ACCT_NO,
ACCT_SUBNO,
ASSET_ID,
CUST_ID,
CUST_NM,
BUS_TYP,
BUS_TYP_NM,
IS_SCHOOL_LOAN,
ACC_CD_ALL,
ACC_CD_TYP,
BKIND,
BCODE,
CHARCD,
COLL_TYP,
COLL_TYP_NM,
COLL_CATG_ID,
COLL_CATG_NM,
R0401CD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEAL_BEG_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEAL_BEG_DATE))='0' THEN NULL ELSE DEAL_BEG_DATE END) AS DEAL_BEG_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEAL_END_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEAL_END_DATE))='0' THEN NULL ELSE DEAL_END_DATE END) AS DEAL_END_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ORIG_VERIFY_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ORIG_VERIFY_DATE))='0' THEN NULL ELSE ORIG_VERIFY_DATE END) AS ORIG_VERIFY_DATE,
ORIG_RANK_CATG,
ORIG_RANK_CATG_NM,
ORIG_RANK,
ORIG_IRB_RANK,
CUR_RANK_CATG,
CUR_RANK_CATG_NM,
CUR_RANK,
CUR_IRB_RANK,
IRB_RANK_CHG_AMT,
REVW_GRADE,
WARN_LEVEL,
RESN_CODE,
BAD_DEBT_MARK,
DURATION,
PD_GROUP_ID,
PD_GROUP_NM,
PD,
LGD_GROUP_ID,
LGD_GROUP_NM,
LGD,
GUAR_AMT,
PREP_INCOME,
CYCLE_MARK,
IS_CANCEL_MARK,
CCF,
EVAL_CAN_USE_AMT,
CR_COMMIT_AMT,
CR_COMMIT_IA_AMT,
EVAL_NOLOSS_AMT,
GUAR_IA_BAL,
GUAR_IA_RATE,
STAGE,
IA_BAL,
IA_RATE,
LS_MON_STAGE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
FULL_COLL_AMT,
NO_COLL_AMT,
NOT_RECVY_AMT,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
PROFIT_RECV,
PROFIT_ALOW_BAD_AMT,
OVDUE_MON,
EVAL_BRN_ID,
EVAL_BRN_NM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EVAL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EVAL_DATE))='0' THEN NULL ELSE EVAL_DATE END) AS EVAL_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CASE_REL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CASE_REL_DATE))='0' THEN NULL ELSE CASE_REL_DATE END) AS CASE_REL_DATE,
EVAL_DESCR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CAL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CAL_DATE))='0' THEN NULL ELSE CAL_DATE END) AS CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
