-- SQL for table: EDW_ELN_CRACOMPLPSNLNBR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CASEID,
CRRPTNO,
QRYIDBAN,
LPSN_DATE,
LPSN_DEPART,
LPSN_PID,
LPSN_BRNO,
LPSN_POSNO,
LPSN_NAME,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASEID,
CRRPTNO,
QRYIDBAN,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LPSN_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LPSN_DATE))='0' THEN NULL ELSE LPSN_DATE END) AS LPSN_DATE,
LPSN_DEPART,
LPSN_PID,
LPSN_BRNO,
LPSN_POSNO,
LPSN_NAME,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
