-- SQL for table: EDW_LNL_LRESC
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SUBIRT' AS DATA_CHK_COL,
SUBIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(SUBIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_LNL_LRESC
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
SQNO,
DB_LRSEC_TYPE,
FUNCOD,
CREDATE,
LASTDT,
DOCUM,
APRVDAT,
EXSDAT,
EXEDAT,
SUBSDAT,
SUBEDAT,
SUBIRT,
GRSDAT,
GREDAT,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
SQNO,
DB_LRSEC_TYPE,
FUNCOD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREDATE))='0' THEN NULL ELSE CREDATE END) AS CREDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
DOCUM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APRVDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APRVDAT))='0' THEN NULL ELSE APRVDAT END) AS APRVDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EXSDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EXSDAT))='0' THEN NULL ELSE EXSDAT END) AS EXSDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EXEDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EXEDAT))='0' THEN NULL ELSE EXEDAT END) AS EXEDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SUBSDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SUBSDAT))='0' THEN NULL ELSE SUBSDAT END) AS SUBSDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SUBEDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SUBEDAT))='0' THEN NULL ELSE SUBEDAT END) AS SUBEDAT,
SUBIRT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRSDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRSDAT))='0' THEN NULL ELSE GRSDAT END) AS GRSDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GREDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GREDAT))='0' THEN NULL ELSE GREDAT END) AS GREDAT,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
