-- SQL for table: EDW_TEJ_CRMSTD
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'STK_AMT' AS DATA_CHK_COL,
STK_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(STK_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PARVAL' AS DATA_CHK_COL,
PARVAL AS DATA_VAL,
SDG.UFN_NUMCHECK(PARVAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_TEJ_CRMSTD
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CO_ID,
NAME8,
INVOICE,
MKT,
IND,
EMM,
PHONE,
FAX,
CHIEF,
PRESIDENT,
SPOKES1,
SPOKES2,
ESTB_DATE,
LIST_DATE,
LIST_DAY1,
TSE_DAY1,
OTC_DAY1,
REG_DAY1,
LIST_DAY2,
D_CAT4,
TEJIND,
TEJINDNM,
BTINDNM,
GOP_NA,
NAME_F_CHI,
NAME_F_ENG,
CHI_ADD,
STK_AMT,
PUB_DA2,
INDNM,
ISIN,
CRMTCRI,
AD_TCRI,
YYMM_TCRI,
CO_TYPE,
PUB_DA1,
END_DATE,
FG1,
BROK_STAT,
TSEIND,
TSEINDNM,
SFIID,
SICS,
SICSNM,
TDRFG,
PARVAL,
PAR_CUR,
JCIC,
TAIL,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CO_ID,
NAME8,
INVOICE,
MKT,
IND,
EMM,
PHONE,
FAX,
CHIEF,
PRESIDENT,
SPOKES1,
SPOKES2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ESTB_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ESTB_DATE))='0' THEN NULL ELSE ESTB_DATE END) AS ESTB_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LIST_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LIST_DATE))='0' THEN NULL ELSE LIST_DATE END) AS LIST_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LIST_DAY1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LIST_DAY1))='0' THEN NULL ELSE LIST_DAY1 END) AS LIST_DAY1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TSE_DAY1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TSE_DAY1))='0' THEN NULL ELSE TSE_DAY1 END) AS TSE_DAY1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OTC_DAY1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OTC_DAY1))='0' THEN NULL ELSE OTC_DAY1 END) AS OTC_DAY1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(REG_DAY1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(REG_DAY1))='0' THEN NULL ELSE REG_DAY1 END) AS REG_DAY1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LIST_DAY2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LIST_DAY2))='0' THEN NULL ELSE LIST_DAY2 END) AS LIST_DAY2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(D_CAT4), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(D_CAT4))='0' THEN NULL ELSE D_CAT4 END) AS D_CAT4,
TEJIND,
TEJINDNM,
BTINDNM,
GOP_NA,
NAME_F_CHI,
NAME_F_ENG,
CHI_ADD,
STK_AMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PUB_DA2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PUB_DA2))='0' THEN NULL ELSE PUB_DA2 END) AS PUB_DA2,
INDNM,
ISIN,
CRMTCRI,
AD_TCRI,
YYMM_TCRI,
CO_TYPE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PUB_DA1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PUB_DA1))='0' THEN NULL ELSE PUB_DA1 END) AS PUB_DA1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(END_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(END_DATE))='0' THEN NULL ELSE END_DATE END) AS END_DATE,
FG1,
BROK_STAT,
TSEIND,
TSEINDNM,
SFIID,
SICS,
SICSNM,
TDRFG,
PARVAL,
PAR_CUR,
JCIC,
TAIL,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
