-- SQL for table: EDW_LNL_LLCON
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONAMT' AS DATA_CHK_COL,
CONAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CONAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MSTLMT' AS DATA_CHK_COL,
MSTLMT AS DATA_VAL,
SDG.UFN_NUMCHECK(MSTLMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ULNLMT' AS DATA_CHK_COL,
ULNLMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ULNLMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTBAL' AS DATA_CHK_COL,
ACTBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ARVAMT' AS DATA_CHK_COL,
ARVAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ARVAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CPCNT' AS DATA_CHK_COL,
CPCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CPCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UPPRI' AS DATA_CHK_COL,
UPPRI AS DATA_VAL,
SDG.UFN_NUMCHECK(UPPRI) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SGAPER' AS DATA_CHK_COL,
SGAPER AS DATA_VAL,
SDG.UFN_NUMCHECK(SGAPER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PER' AS DATA_CHK_COL,
PER AS DATA_VAL,
SDG.UFN_NUMCHECK(PER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'"LIMIT"' AS DATA_CHK_COL,
"LIMIT" AS DATA_VAL,
SDG.UFN_NUMCHECK("LIMIT") AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OTHCHG' AS DATA_CHK_COL,
OTHCHG AS DATA_VAL,
SDG.UFN_NUMCHECK(OTHCHG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TFRATE' AS DATA_CHK_COL,
TFRATE AS DATA_VAL,
SDG.UFN_NUMCHECK(TFRATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTIRT' AS DATA_CHK_COL,
NTIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(NTIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CNIRT' AS DATA_CHK_COL,
CNIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(CNIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TFIRT' AS DATA_CHK_COL,
TFIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(TFIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INTTOT' AS DATA_CHK_COL,
INTTOT AS DATA_VAL,
SDG.UFN_NUMCHECK(INTTOT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ODITOT' AS DATA_CHK_COL,
ODITOT AS DATA_VAL,
SDG.UFN_NUMCHECK(ODITOT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DFTOT' AS DATA_CHK_COL,
DFTOT AS DATA_VAL,
SDG.UFN_NUMCHECK(DFTOT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGTOT' AS DATA_CHK_COL,
CHGTOT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGTOT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INTCD' AS DATA_CHK_COL,
INTCD AS DATA_VAL,
SDG.UFN_NUMCHECK(INTCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INTTM' AS DATA_CHK_COL,
INTTM AS DATA_VAL,
SDG.UFN_NUMCHECK(INTTM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRTM' AS DATA_CHK_COL,
PRTM AS DATA_VAL,
SDG.UFN_NUMCHECK(PRTM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ISTPRT' AS DATA_CHK_COL,
ISTPRT AS DATA_VAL,
SDG.UFN_NUMCHECK(ISTPRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRDTOT' AS DATA_CHK_COL,
PRDTOT AS DATA_VAL,
SDG.UFN_NUMCHECK(PRDTOT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CLSPRD' AS DATA_CHK_COL,
CLSPRD AS DATA_VAL,
SDG.UFN_NUMCHECK(CLSPRD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CNIRID' AS DATA_CHK_COL,
CNIRID AS DATA_VAL,
SDG.UFN_NUMCHECK(CNIRID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CNIXPR' AS DATA_CHK_COL,
CNIXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(CNIXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CNIXID' AS DATA_CHK_COL,
CNIXID AS DATA_VAL,
SDG.UFN_NUMCHECK(CNIXID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTIRID' AS DATA_CHK_COL,
NTIRID AS DATA_VAL,
SDG.UFN_NUMCHECK(NTIRID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTIXPR' AS DATA_CHK_COL,
NTIXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(NTIXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTIXID' AS DATA_CHK_COL,
NTIXID AS DATA_VAL,
SDG.UFN_NUMCHECK(NTIXID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TFIRID' AS DATA_CHK_COL,
TFIRID AS DATA_VAL,
SDG.UFN_NUMCHECK(TFIRID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TFIXPR' AS DATA_CHK_COL,
TFIXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(TFIXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TFIXID' AS DATA_CHK_COL,
TFIXID AS DATA_VAL,
SDG.UFN_NUMCHECK(TFIXID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MIDNO' AS DATA_CHK_COL,
MIDNO AS DATA_VAL,
SDG.UFN_NUMCHECK(MIDNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FILLER' AS DATA_CHK_COL,
FILLER AS DATA_VAL,
SDG.UFN_NUMCHECK(FILLER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCUBAL' AS DATA_CHK_COL,
ACCUBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCUBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCUAC' AS DATA_CHK_COL,
ACCUAC AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCUAC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCULN' AS DATA_CHK_COL,
ACCULN AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCULN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PERCENT' AS DATA_CHK_COL,
PERCENT AS DATA_VAL,
SDG.UFN_NUMCHECK(PERCENT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPIXPR' AS DATA_CHK_COL,
SPIXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(SPIXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UCHGRT' AS DATA_CHK_COL,
UCHGRT AS DATA_VAL,
SDG.UFN_NUMCHECK(UCHGRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UIXPR' AS DATA_CHK_COL,
UIXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(UIXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UFITIRT' AS DATA_CHK_COL,
UFITIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(UFITIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FITDIV' AS DATA_CHK_COL,
FITDIV AS DATA_VAL,
SDG.UFN_NUMCHECK(FITDIV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SEQNO' AS DATA_CHK_COL,
SEQNO AS DATA_VAL,
SDG.UFN_NUMCHECK(SEQNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSKAMT' AS DATA_CHK_COL,
RSKAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RSKAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GDCNT' AS DATA_CHK_COL,
GDCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(GDCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LMTGNT' AS DATA_CHK_COL,
LMTGNT AS DATA_VAL,
SDG.UFN_NUMCHECK(LMTGNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ULNFEE' AS DATA_CHK_COL,
ULNFEE AS DATA_VAL,
SDG.UFN_NUMCHECK(ULNFEE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MININT' AS DATA_CHK_COL,
MININT AS DATA_VAL,
SDG.UFN_NUMCHECK(MININT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LOVIXPR' AS DATA_CHK_COL,
LOVIXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(LOVIXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OTHCPPER' AS DATA_CHK_COL,
OTHCPPER AS DATA_VAL,
SDG.UFN_NUMCHECK(OTHCPPER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LOWCHARGE' AS DATA_CHK_COL,
LOWCHARGE AS DATA_VAL,
SDG.UFN_NUMCHECK(LOWCHARGE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRPER' AS DATA_CHK_COL,
PRPER AS DATA_VAL,
SDG.UFN_NUMCHECK(PRPER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SGADATE' AS DATA_CHK_COL,
SGADATE AS DATA_VAL,
SDG.UFN_NUMCHECK(SGADATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ELOANNO' AS DATA_CHK_COL,
ELOANNO AS DATA_VAL,
SDG.UFN_NUMCHECK(ELOANNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECYY' AS DATA_CHK_COL,
RECYY AS DATA_VAL,
SDG.UFN_NUMCHECK(RECYY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LKBKDAYS' AS DATA_CHK_COL,
LKBKDAYS AS DATA_VAL,
SDG.UFN_NUMCHECK(LKBKDAYS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTRURT' AS DATA_CHK_COL,
NTRURT AS DATA_VAL,
SDG.UFN_NUMCHECK(NTRURT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ODCD65' AS DATA_CHK_COL,
ODCD65 AS DATA_VAL,
SDG.UFN_NUMCHECK(ODCD65) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_LNL_LLCON
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
PIDNO,
PIDERR,
ENTPNO,
EIDERR,
SAPNO,
LNCUR,
CHARCD,
BCODE,
CONAMT,
MSTLMT,
ULNLMT,
ACTBAL,
ARVAMT,
SHARCD,
"USAGE",
"SOURCE",
LNTYP,
MANG,
PRM,
CYCLE,
LNDOC,
CPCNT,
CSDATE,
CEDATE,
RGDAY,
ODDATE,
LASTDT,
NUMEDT,
RATDT,
LUSPR,
ODCD,
EXDATE,
ACTCLS,
IPACTNO,
DMCD,
TRUCD,
TRUNO,
APIVCD,
ISTSCD,
UPPRI,
SGAPER,
SGAID,
SCOP,
PER,
"LIMIT",
APCD,
APACT,
PAYACT,
OACTNO,
TRPACT,
DLCCD,
OGNAME,
OTHCHG,
TFBRNO,
TFRATE,
CBCNO,
BSID,
BSCD,
APSQNO,
UNSQNO,
INTSQ,
NTIRT,
CNIRT,
TFIRT,
INTTOT,
ODITOT,
DFTOT,
CHGTOT,
INTCD,
INTTM,
NIDATE,
OIDATE,
IDATE,
PRCD,
PRTM,
NPRDT,
OPRDT,
PRDATE,
ISTPRT,
PRDTOT,
CLSPRD,
CNIRDT,
CNIRND,
CNIRCD,
CNIRID,
CNIXPR,
CNIXID,
NTIRDT,
NTIRND,
NTIRCD,
NTIRID,
NTIXPR,
NTIXID,
TFIRDT,
TFIRND,
TFIRCD,
TFIRID,
TFIXPR,
TFIXID,
MIDNO,
MAPCD,
MCURCD,
TELNO,
SHARID,
PLDOC,
NOIDT,
INTID,
PRID,
TFCURR,
SQICD,
APRCD,
DAY30,
FILLER,
APKIND,
ACCUBAL,
ACCUAC,
ACCULN,
ACCUDT,
PERCENT,
SPIXPR,
SIRND,
UIRTCD,
UCHGRT,
UIXPR,
UFITIRT,
PLCKIND,
NEWCD,
FINA,
FITDIV,
AGBRNO,
CONTYP,
IREVOCB,
DEPNO,
CBRNO,
YEAR,
CSRNO,
SEQNO,
RSKNAL,
IRATDT,
PRCD9,
INTCD9,
RSKAMT,
GDCNT,
CNFLG,
NTXDAY,
TWLODG,
LENTPNO,
LFILLER,
LMTGNO,
LMTGDT,
LMTGNT,
ULNFEE,
USECD,
MININT,
LOVENTP,
LOVSIXPR,
LOVIXPR,
DWELLING,
OTHCPPER,
PLCKIND2,
PLCKIND3,
PLCKIND4,
PLCKIND5,
PLCKIND6,
ULNPER,
TRANS,
FUNDUSE,
LOWCHARGE,
ABCPCNT,
MICRO,
PRPER,
BUILDCD,
BUILDDAY,
SGADATE,
CHANGECD,
REGION,
ELOANNO,
BKACT,
BYCD,
BYOTHER,
BNCD,
BNOTHER,
CTLFG,
AREA,
CNFLG2,
CNUSE,
CNGUAR,
LCOLLD,
NDSTR,
APPRV,
DEUSE,
RECYY,
MOEACODE,
LKBKDAYS,
COMPOUND,
NTRURT,
UACTNO,
TACTNO,
ODCD65,
LNSGCD,
JCICLS,
JCRGDT,
COMMIT,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
PIDNO,
PIDERR,
ENTPNO,
EIDERR,
SAPNO,
LNCUR,
CHARCD,
BCODE,
CONAMT,
MSTLMT,
ULNLMT,
ACTBAL,
ARVAMT,
SHARCD,
"USAGE",
"SOURCE",
LNTYP,
MANG,
PRM,
CYCLE,
LNDOC,
CPCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CSDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CSDATE))='0' THEN NULL ELSE CSDATE END) AS CSDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CEDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CEDATE))='0' THEN NULL ELSE CEDATE END) AS CEDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RGDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RGDAY))='0' THEN NULL ELSE RGDAY END) AS RGDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ODDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ODDATE))='0' THEN NULL ELSE ODDATE END) AS ODDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NUMEDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NUMEDT))='0' THEN NULL ELSE NUMEDT END) AS NUMEDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RATDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RATDT))='0' THEN NULL ELSE RATDT END) AS RATDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LUSPR), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LUSPR))='0' THEN NULL ELSE LUSPR END) AS LUSPR,
ODCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EXDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EXDATE))='0' THEN NULL ELSE EXDATE END) AS EXDATE,
ACTCLS,
IPACTNO,
DMCD,
TRUCD,
TRUNO,
APIVCD,
ISTSCD,
UPPRI,
SGAPER,
SGAID,
SCOP,
PER,
"LIMIT",
APCD,
APACT,
PAYACT,
OACTNO,
TRPACT,
DLCCD,
OGNAME,
OTHCHG,
TFBRNO,
TFRATE,
CBCNO,
BSID,
BSCD,
APSQNO,
UNSQNO,
INTSQ,
NTIRT,
CNIRT,
TFIRT,
INTTOT,
ODITOT,
DFTOT,
CHGTOT,
INTCD,
INTTM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NIDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NIDATE))='0' THEN NULL ELSE NIDATE END) AS NIDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OIDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OIDATE))='0' THEN NULL ELSE OIDATE END) AS OIDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IDATE))='0' THEN NULL ELSE IDATE END) AS IDATE,
PRCD,
PRTM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NPRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NPRDT))='0' THEN NULL ELSE NPRDT END) AS NPRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPRDT))='0' THEN NULL ELSE OPRDT END) AS OPRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRDATE))='0' THEN NULL ELSE PRDATE END) AS PRDATE,
ISTPRT,
PRDTOT,
CLSPRD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CNIRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CNIRDT))='0' THEN NULL ELSE CNIRDT END) AS CNIRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CNIRND), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CNIRND))='0' THEN NULL ELSE CNIRND END) AS CNIRND,
CNIRCD,
CNIRID,
CNIXPR,
CNIXID,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTIRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTIRDT))='0' THEN NULL ELSE NTIRDT END) AS NTIRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTIRND), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTIRND))='0' THEN NULL ELSE NTIRND END) AS NTIRND,
NTIRCD,
NTIRID,
NTIXPR,
NTIXID,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TFIRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TFIRDT))='0' THEN NULL ELSE TFIRDT END) AS TFIRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TFIRND), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TFIRND))='0' THEN NULL ELSE TFIRND END) AS TFIRND,
TFIRCD,
TFIRID,
TFIXPR,
TFIXID,
MIDNO,
MAPCD,
MCURCD,
TELNO,
SHARID,
PLDOC,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NOIDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NOIDT))='0' THEN NULL ELSE NOIDT END) AS NOIDT,
INTID,
PRID,
TFCURR,
SQICD,
APRCD,
DAY30,
FILLER,
APKIND,
ACCUBAL,
ACCUAC,
ACCULN,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACCUDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACCUDT))='0' THEN NULL ELSE ACCUDT END) AS ACCUDT,
PERCENT,
SPIXPR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SIRND), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SIRND))='0' THEN NULL ELSE SIRND END) AS SIRND,
UIRTCD,
UCHGRT,
UIXPR,
UFITIRT,
PLCKIND,
NEWCD,
FINA,
FITDIV,
AGBRNO,
CONTYP,
IREVOCB,
DEPNO,
CBRNO,
YEAR,
CSRNO,
SEQNO,
RSKNAL,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IRATDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IRATDT))='0' THEN NULL ELSE IRATDT END) AS IRATDT,
PRCD9,
INTCD9,
RSKAMT,
GDCNT,
CNFLG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
TWLODG,
LENTPNO,
LFILLER,
LMTGNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LMTGDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LMTGDT))='0' THEN NULL ELSE LMTGDT END) AS LMTGDT,
LMTGNT,
ULNFEE,
USECD,
MININT,
LOVENTP,
LOVSIXPR,
LOVIXPR,
DWELLING,
OTHCPPER,
PLCKIND2,
PLCKIND3,
PLCKIND4,
PLCKIND5,
PLCKIND6,
ULNPER,
TRANS,
FUNDUSE,
LOWCHARGE,
ABCPCNT,
MICRO,
PRPER,
BUILDCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BUILDDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BUILDDAY))='0' THEN NULL ELSE BUILDDAY END) AS BUILDDAY,
SGADATE,
CHANGECD,
REGION,
ELOANNO,
BKACT,
BYCD,
BYOTHER,
BNCD,
BNOTHER,
CTLFG,
AREA,
CNFLG2,
CNUSE,
CNGUAR,
LCOLLD,
NDSTR,
APPRV,
DEUSE,
RECYY,
MOEACODE,
LKBKDAYS,
COMPOUND,
NTRURT,
UACTNO,
TACTNO,
ODCD65,
LNSGCD,
JCICLS,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(JCRGDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(JCRGDT))='0' THEN NULL ELSE JCRGDT END) AS JCRGDT,
COMMIT,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
