-- SQL for table: EDW_IFRS9_ACCCDSTAT
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACC_CD_BAL' AS DATA_CHK_COL,
ACC_CD_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ACC_CD_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_AMORTIZE_DISC_AMT' AS DATA_CHK_COL,
NO_AMORTIZE_DISC_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_AMORTIZE_DISC_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_AMORTIZE_ADD_AMT' AS DATA_CHK_COL,
NO_AMORTIZE_ADD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_AMORTIZE_ADD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL' AS DATA_CHK_COL,
IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_RATE' AS DATA_CHK_COL,
IA_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LS_MON_IA_BAL' AS DATA_CHK_COL,
LS_MON_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(LS_MON_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL_DIFF' AS DATA_CHK_COL,
IA_BAL_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL1_ACC_CD_AMT' AS DATA_CHK_COL,
NPL1_ACC_CD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL1_ACC_CD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL2_ACC_CD_AMT' AS DATA_CHK_COL,
NPL2_ACC_CD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL2_ACC_CD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL3_ACC_CD_AMT' AS DATA_CHK_COL,
NPL3_ACC_CD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL3_ACC_CD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL4_ACC_CD_AMT' AS DATA_CHK_COL,
NPL4_ACC_CD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL4_ACC_CD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL5_ACC_CD_AMT' AS DATA_CHK_COL,
NPL5_ACC_CD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL5_ACC_CD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_ACC_CD_AMT' AS DATA_CHK_COL,
NPL_ACC_CD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_ACC_CD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_RATIO' AS DATA_CHK_COL,
NPL_RATIO AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_RATIO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_BAL_AMT_DIFF' AS DATA_CHK_COL,
NPL_BAL_AMT_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_BAL_AMT_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_IFRS9_ACCCDSTAT
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
VER_NO,
BRN_ID,
BRN_NM,
ACC_CD_CATEG,
ACC_CD_ALL,
ACC_CD_TYP,
ACC_CD_NAME,
ACC_CD_BAL,
NO_AMORTIZE_DISC_AMT,
NO_AMORTIZE_ADD_AMT,
IA_BAL,
IA_RATE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
NPL1_ACC_CD_AMT,
NPL2_ACC_CD_AMT,
NPL3_ACC_CD_AMT,
NPL4_ACC_CD_AMT,
NPL5_ACC_CD_AMT,
NPL_ACC_CD_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATA_YM), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATA_YM))='0' THEN NULL ELSE DATA_YM END) AS DATA_YM,
VER_NO,
BRN_ID,
BRN_NM,
ACC_CD_CATEG,
ACC_CD_ALL,
ACC_CD_TYP,
ACC_CD_NAME,
ACC_CD_BAL,
NO_AMORTIZE_DISC_AMT,
NO_AMORTIZE_ADD_AMT,
IA_BAL,
IA_RATE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
NPL1_ACC_CD_AMT,
NPL2_ACC_CD_AMT,
NPL3_ACC_CD_AMT,
NPL4_ACC_CD_AMT,
NPL5_ACC_CD_AMT,
NPL_ACC_CD_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CAL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CAL_DATE))='0' THEN NULL ELSE CAL_DATE END) AS CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
