-- SQL for table: EDW_WMS_RPTORGDEFNHSM
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YYYYMM,
DATA_DATE,
TERRITORY_ID,
DESCR,
BRCH_CLS,
LEVEL_ID,
ORG_SEQ,
PAR_TERRITORY_ID,
VIRTUAL_FLAG,
CLS_FLAG,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATA_YYYYMM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATA_DATE), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATA_DATE))='0' THEN '0001-01-01' ELSE DATA_DATE END) AS DATA_DATE,
TERRITORY_ID,
DESCR,
BRCH_CLS,
LEVEL_ID,
ORG_SEQ,
PAR_TERRITORY_ID,
VIRTUAL_FLAG,
CLS_FLAG,
VERSION,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREATETIME), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREATETIME))='0' THEN NULL ELSE CREATETIME END) AS CREATETIME,
CREATOR,
MODIFIER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTUPDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTUPDATE))='0' THEN NULL ELSE LASTUPDATE END) AS LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
