-- SQL for table: EDW_FC_FCKTR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
TXDAY,
MTRCNT,
ENTDAY,
TXTIME,
KINBR,
TRMSEQ,
TXTNO,
TLRNO,
SUPNO,
TXCD,
DSCPT,
HCODE,
YCODE,
CRDB,
CURCD,
TXAMT,
AVBAL,
RBRNO,
FXRT,
TRNAMT,
CKNO,
NOTE,
AFCLS,
RBKTP,
CNTRYCD,
USECD,
BKSRNO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXDAY))='0' THEN NULL ELSE TXDAY END) AS TXDAY,
MTRCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ENTDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ENTDAY))='0' THEN NULL ELSE ENTDAY END) AS ENTDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXDAY)||' '||TRIM(TXTIME), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXDAY)||' '||TRIM(TXTIME))='0' THEN NULL ELSE TRIM(TXDAY)||' '||TRIM(TXTIME) END) AS TXTIME,
KINBR,
TRMSEQ,
TXTNO,
TLRNO,
SUPNO,
TXCD,
DSCPT,
HCODE,
YCODE,
CRDB,
CURCD,
TXAMT,
AVBAL,
RBRNO,
FXRT,
TRNAMT,
CKNO,
NOTE,
AFCLS,
RBKTP,
CNTRYCD,
USECD,
BKSRNO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
