-- SQL for table: EDW_ELN_CRMWEL0008
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
IDBAN,
GRADEYEAR,
CRENVAL,
BOTMARK,
BOTRANK,
BRAUTHDATE,
HQCLOSEDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
IDBAN,
GRADEYEAR,
CRENVAL,
BOTMARK,
BOTRANK,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BRAUTHDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BRAUTHDATE))='0' THEN NULL ELSE BRAUTHDATE END) AS BRAUTHDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(HQCLOSEDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(HQCLOSEDATE))='0' THEN NULL ELSE HQCLOSEDATE END) AS HQCLOSEDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
