-- SQL for table: EDW_FXJ_FORMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'REMAMT' AS DATA_CHK_COL,
REMAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(REMAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PAYAMT' AS DATA_CHK_COL,
PAYAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PAYAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FCEXP' AS DATA_CHK_COL,
FCEXP AS DATA_VAL,
SDG.UFN_NUMCHECK(FCEXP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'XRATE' AS DATA_CHK_COL,
XRATE AS DATA_VAL,
SDG.UFN_NUMCHECK(XRATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RCLCNT' AS DATA_CHK_COL,
RCLCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RCLCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TCNT' AS DATA_CHK_COL,
TCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO' AS DATA_CHK_COL,
TXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COST' AS DATA_CHK_COL,
COST AS DATA_VAL,
SDG.UFN_NUMCHECK(COST) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CRSEQ' AS DATA_CHK_COL,
CRSEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(CRSEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT' AS DATA_CHK_COL,
EXAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DDNO1' AS DATA_CHK_COL,
DDNO1 AS DATA_VAL,
SDG.UFN_NUMCHECK(DDNO1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXJ_FORMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CIFKEY,
CORPNO,
CURCD,
REMAMT,
REMDAT,
CLRCUR,
CLRSRNO,
USECD,
CHARCD,
PAYBK,
PSWFCD,
PAYDAT,
CLSDAT,
PAYAMT,
FCEXP,
ADVICE,
XRATE,
NCHGDAT,
RFNDAT,
LRCLDAT,
RCLCNT,
ACTSTP,
ACTCLS,
HOLD,
HOLDAT,
RISSE,
TCNT,
CRS,
ACCID,
DDNO,
TELNO,
MAINCODE,
TXTNO,
WSNO,
LASTDT,
TLRNO,
THEIR,
COST,
CRBHNAM,
CRSEQ,
CUSTOM,
CN,
EXAMT,
DDNO1,
EBNO,
PBKID,
PBKNAM1,
PBKNAM2,
PBKNAM3,
PBKNAM4,
NTXDAY,
REMTYP,
CNTRYCD,
TXCD,
CNGOODS,
"690CODE",
NUSECDX,
"SOURCE",
TAG111,
TAG121,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CIFKEY,
CORPNO,
CURCD,
REMAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(REMDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(REMDAT))='0' THEN NULL ELSE REMDAT END) AS REMDAT,
CLRCUR,
CLRSRNO,
USECD,
CHARCD,
PAYBK,
PSWFCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PAYDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PAYDAT))='0' THEN NULL ELSE PAYDAT END) AS PAYDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLSDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLSDAT))='0' THEN NULL ELSE CLSDAT END) AS CLSDAT,
PAYAMT,
FCEXP,
ADVICE,
XRATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NCHGDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NCHGDAT))='0' THEN NULL ELSE NCHGDAT END) AS NCHGDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RFNDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RFNDAT))='0' THEN NULL ELSE RFNDAT END) AS RFNDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRCLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRCLDAT))='0' THEN NULL ELSE LRCLDAT END) AS LRCLDAT,
RCLCNT,
ACTSTP,
ACTCLS,
HOLD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(HOLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(HOLDAT))='0' THEN NULL ELSE HOLDAT END) AS HOLDAT,
RISSE,
TCNT,
CRS,
ACCID,
DDNO,
TELNO,
MAINCODE,
TXTNO,
WSNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
TLRNO,
THEIR,
COST,
CRBHNAM,
CRSEQ,
CUSTOM,
CN,
EXAMT,
DDNO1,
EBNO,
PBKID,
PBKNAM1,
PBKNAM2,
PBKNAM3,
PBKNAM4,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
REMTYP,
CNTRYCD,
TXCD,
CNGOODS,
"690CODE",
NUSECDX,
"SOURCE",
TAG111,
TAG121,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
