-- SQL for table: EDW_FXI_FIRMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO' AS DATA_CHK_COL,
CORPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'REMAMT' AS DATA_CHK_COL,
REMAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(REMAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTAMT' AS DATA_CHK_COL,
NTAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NTAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FCEXP' AS DATA_CHK_COL,
FCEXP AS DATA_VAL,
SDG.UFN_NUMCHECK(FCEXP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OSN' AS DATA_CHK_COL,
OSN AS DATA_VAL,
SDG.UFN_NUMCHECK(OSN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'XRATE' AS DATA_CHK_COL,
XRATE AS DATA_VAL,
SDG.UFN_NUMCHECK(XRATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO' AS DATA_CHK_COL,
TXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT' AS DATA_CHK_COL,
EXAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'"33B"' AS DATA_CHK_COL,
"33B" AS DATA_VAL,
SDG.UFN_NUMCHECK("33B") AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'"71FAMT"' AS DATA_CHK_COL,
"71FAMT" AS DATA_VAL,
SDG.UFN_NUMCHECK("71FAMT") AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'"71FAMT2"' AS DATA_CHK_COL,
"71FAMT2" AS DATA_VAL,
SDG.UFN_NUMCHECK("71FAMT2") AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'"71FAMT3"' AS DATA_CHK_COL,
"71FAMT3" AS DATA_VAL,
SDG.UFN_NUMCHECK("71FAMT3") AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXI_FIRMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CIFKEY,
CORPNO,
CURCD,
REMAMT,
REMDAT,
CLRCUR,
CLRSRNO,
USECD,
CHARCD,
RSWFCD,
ENTDAT,
THEIR,
ACTCLS,
HOLD,
NTCD,
IRCBFG,
HOLDAT,
NTAMT,
REMTYP,
REMBK,
REMSWFCD,
REMBKNM1,
REMBKNM2,
REMBKNM3,
VLDATE,
CLSDAT,
RECNAM1,
RECNAM2,
RECADR1,
RECADR2,
TELNO,
OPBRNO,
OPDAT,
FCEXP,
OSN,
RECSWFCD,
REMNAM1,
REMNAM2,
REMTELNO,
XRATE,
TXTNO,
WSNO,
LASTDT,
TLRNO,
TXCD,
MT110,
SRNBK,
RCVBRH,
CHKNO,
CUSTOM,
CN,
EXAMT,
RECINFO,
NTXDAY,
CNGOODS,
CNTRYCD,
REMINF1,
REMINF2,
REMINF3,
REMINF4,
REMADR1,
REMADR2,
REMADR3,
REMARK1,
REMARK2,
REMARK3,
REMARK4,
"690CODE",
NUSECDX,
UETR,
"33BCURNA",
"33B",
"71A",
"71FCUR",
"71FCUR2",
"71FCUR3",
"71FAMT",
"71FAMT2",
"71FAMT3",
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CIFKEY,
CORPNO,
CURCD,
REMAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(REMDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(REMDAT))='0' THEN NULL ELSE REMDAT END) AS REMDAT,
CLRCUR,
CLRSRNO,
USECD,
CHARCD,
RSWFCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ENTDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ENTDAT))='0' THEN NULL ELSE ENTDAT END) AS ENTDAT,
THEIR,
ACTCLS,
HOLD,
NTCD,
IRCBFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(HOLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(HOLDAT))='0' THEN NULL ELSE HOLDAT END) AS HOLDAT,
NTAMT,
REMTYP,
REMBK,
REMSWFCD,
REMBKNM1,
REMBKNM2,
REMBKNM3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(VLDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(VLDATE))='0' THEN NULL ELSE VLDATE END) AS VLDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLSDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLSDAT))='0' THEN NULL ELSE CLSDAT END) AS CLSDAT,
RECNAM1,
RECNAM2,
RECADR1,
RECADR2,
TELNO,
OPBRNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPDAT))='0' THEN NULL ELSE OPDAT END) AS OPDAT,
FCEXP,
OSN,
RECSWFCD,
REMNAM1,
REMNAM2,
REMTELNO,
XRATE,
TXTNO,
WSNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
TLRNO,
TXCD,
MT110,
SRNBK,
RCVBRH,
CHKNO,
CUSTOM,
CN,
EXAMT,
RECINFO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
CNGOODS,
CNTRYCD,
REMINF1,
REMINF2,
REMINF3,
REMINF4,
REMADR1,
REMADR2,
REMADR3,
REMARK1,
REMARK2,
REMARK3,
REMARK4,
"690CODE",
NUSECDX,
UETR,
"33BCURNA",
"33B",
"71A",
"71FCUR",
"71FCUR2",
"71FCUR3",
"71FAMT",
"71FAMT2",
"71FAMT3",
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
