-- SQL for table: EDW_IFRS9_INDIVIADTL
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IRB_RANK_CHG_AMT' AS DATA_CHK_COL,
IRB_RANK_CHG_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(IRB_RANK_CHG_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACC_CD_BAL' AS DATA_CHK_COL,
ACC_CD_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ACC_CD_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_AMORTIZE_DISC_AMT' AS DATA_CHK_COL,
NO_AMORTIZE_DISC_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_AMORTIZE_DISC_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_AMORTIZE_ADD_AMT' AS DATA_CHK_COL,
NO_AMORTIZE_ADD_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_AMORTIZE_ADD_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCT_AMT' AS DATA_CHK_COL,
ACCT_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCT_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DEAL_RECVY_AMT' AS DATA_CHK_COL,
DEAL_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(DEAL_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_RECVY_AMT' AS DATA_CHK_COL,
COLL_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OTHER_RECVY_AMT' AS DATA_CHK_COL,
OTHER_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OTHER_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TOTAL_RECVY_AMT' AS DATA_CHK_COL,
TOTAL_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(TOTAL_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EIR' AS DATA_CHK_COL,
EIR AS DATA_VAL,
SDG.UFN_NUMCHECK(EIR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL' AS DATA_CHK_COL,
IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_RATE' AS DATA_CHK_COL,
IA_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LS_MON_IA_BAL' AS DATA_CHK_COL,
LS_MON_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(LS_MON_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IA_BAL_DIFF' AS DATA_CHK_COL,
IA_BAL_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(IA_BAL_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_1ST' AS DATA_CHK_COL,
RECVY_AMT_1ST AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_1ST) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_2ND' AS DATA_CHK_COL,
RECVY_AMT_2ND AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_2ND) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_3RD' AS DATA_CHK_COL,
RECVY_AMT_3RD AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_3RD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_4TH' AS DATA_CHK_COL,
RECVY_AMT_4TH AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_4TH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_5TH' AS DATA_CHK_COL,
RECVY_AMT_5TH AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_5TH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_6TH' AS DATA_CHK_COL,
RECVY_AMT_6TH AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_6TH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_7TH' AS DATA_CHK_COL,
RECVY_AMT_7TH AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_7TH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_8TH' AS DATA_CHK_COL,
RECVY_AMT_8TH AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_8TH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_9TH' AS DATA_CHK_COL,
RECVY_AMT_9TH AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_9TH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECVY_AMT_10TH' AS DATA_CHK_COL,
RECVY_AMT_10TH AS DATA_VAL,
SDG.UFN_NUMCHECK(RECVY_AMT_10TH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EVAL_FULL_COLL_AMT' AS DATA_CHK_COL,
EVAL_FULL_COLL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EVAL_FULL_COLL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EVAL_NOT_RECVY_AMT' AS DATA_CHK_COL,
EVAL_NOT_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EVAL_NOT_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FULL_COLL_AMT' AS DATA_CHK_COL,
FULL_COLL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(FULL_COLL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NO_COLL_AMT' AS DATA_CHK_COL,
NO_COLL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NO_COLL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NOT_RECVY_AMT' AS DATA_CHK_COL,
NOT_RECVY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NOT_RECVY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL1_LOAN_BAL' AS DATA_CHK_COL,
NPL1_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL1_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL2_LOAN_BAL' AS DATA_CHK_COL,
NPL2_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL2_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL3_LOAN_BAL' AS DATA_CHK_COL,
NPL3_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL3_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL4_LOAN_BAL' AS DATA_CHK_COL,
NPL4_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL4_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL5_LOAN_BAL' AS DATA_CHK_COL,
NPL5_LOAN_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL5_LOAN_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_BAL_AMT' AS DATA_CHK_COL,
NPL_BAL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_BAL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_RATIO' AS DATA_CHK_COL,
NPL_RATIO AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_RATIO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NPL_BAL_AMT_DIFF' AS DATA_CHK_COL,
NPL_BAL_AMT_DIFF AS DATA_VAL,
SDG.UFN_NUMCHECK(NPL_BAL_AMT_DIFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_RECV_AMT' AS DATA_CHK_COL,
INT_RECV_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_RECV_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_IA_AMT' AS DATA_CHK_COL,
INT_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVDUE_MON' AS DATA_CHK_COL,
OVDUE_MON AS DATA_VAL,
SDG.UFN_NUMCHECK(OVDUE_MON) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ADV_PAY_AMT' AS DATA_CHK_COL,
ADV_PAY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ADV_PAY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ADV_PAY_IA_AMT' AS DATA_CHK_COL,
ADV_PAY_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ADV_PAY_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAD_DEBT_AMT' AS DATA_CHK_COL,
BAD_DEBT_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BAD_DEBT_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUR_IA_BAL' AS DATA_CHK_COL,
CUR_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(CUR_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_IA_BAL' AS DATA_CHK_COL,
ORIG_IA_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_IA_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_IA_RATE' AS DATA_CHK_COL,
ORIG_IA_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_IA_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_INT_RECV_AMT' AS DATA_CHK_COL,
ORIG_INT_RECV_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_INT_RECV_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORIG_ADV_PAY_IA_AMT' AS DATA_CHK_COL,
ORIG_ADV_PAY_IA_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ORIG_ADV_PAY_IA_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_IFRS9_INDIVIADTL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATA_YM,
BRN_ID,
BRN_NM,
ACCT_NO,
CUST_ID,
CUST_NM,
BUS_TYP,
BUS_TYP_NM,
ACC_CD_ALL,
ACC_CD_TYP,
BKIND,
BCODE,
CHARCD,
COLL_TYP,
COLL_CATG_ID,
R0401CD,
DEAL_BEG_DATE,
DEAL_END_DATE,
ORIG_VERIFY_DATE,
ORIG_RANK_CATG,
ORIG_RANK_CATG_NM,
ORIG_RANK,
ORIG_IRB_RANK,
CUR_RANK_CATG,
CUR_RANK_CATG_NM,
CUR_RANK,
CUR_IRB_RANK,
IRB_RANK_CHG_AMT,
REVW_GRADE,
WARN_LEVEL,
RESN_CODE,
BAD_DEBT_MARK,
ACC_CD_BAL,
NO_AMORTIZE_DISC_AMT,
NO_AMORTIZE_ADD_AMT,
ACCT_AMT,
DEAL_RECVY_AMT,
COLL_RECVY_AMT,
OTHER_RECVY_AMT,
TOTAL_RECVY_AMT,
EIR,
STAGE,
IA_BAL,
IA_RATE,
LS_MON_STAGE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
RECVY_AMT_1ST,
RECVY_AMT_2ND,
RECVY_AMT_3RD,
RECVY_AMT_4TH,
RECVY_AMT_5TH,
RECVY_AMT_6TH,
RECVY_AMT_7TH,
RECVY_AMT_8TH,
RECVY_AMT_9TH,
RECVY_AMT_10TH,
EVAL_FULL_COLL_AMT,
EVAL_NOT_RECVY_AMT,
FULL_COLL_AMT,
NO_COLL_AMT,
NOT_RECVY_AMT,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
INT_RECV_AMT,
INT_IA_AMT,
IS_MAJOR,
OVDUE_MON,
IS_EXIST_COLL,
ADV_PAY_AMT,
ADV_PAY_IA_AMT,
EVAL_BRN_NM,
EVAL_DATE,
CASE_REL_DATE,
EVAL_DESCR,
BAD_DEBT_AMT,
COLL_STS,
COLL_STS_NM,
CUR_IA_BAL,
ORIG_IA_BAL,
ORIG_IA_RATE,
ORIG_INT_RECV_AMT,
ORIG_ADV_PAY_IA_AMT,
CAL_DATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATA_YM), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATA_YM))='0' THEN '0001-01-01' ELSE DATA_YM END) AS DATA_YM,
BRN_ID,
BRN_NM,
ACCT_NO,
CUST_ID,
CUST_NM,
BUS_TYP,
BUS_TYP_NM,
ACC_CD_ALL,
ACC_CD_TYP,
BKIND,
BCODE,
CHARCD,
COLL_TYP,
COLL_CATG_ID,
R0401CD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEAL_BEG_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEAL_BEG_DATE))='0' THEN NULL ELSE DEAL_BEG_DATE END) AS DEAL_BEG_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEAL_END_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEAL_END_DATE))='0' THEN NULL ELSE DEAL_END_DATE END) AS DEAL_END_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ORIG_VERIFY_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ORIG_VERIFY_DATE))='0' THEN NULL ELSE ORIG_VERIFY_DATE END) AS ORIG_VERIFY_DATE,
ORIG_RANK_CATG,
ORIG_RANK_CATG_NM,
ORIG_RANK,
ORIG_IRB_RANK,
CUR_RANK_CATG,
CUR_RANK_CATG_NM,
CUR_RANK,
CUR_IRB_RANK,
IRB_RANK_CHG_AMT,
REVW_GRADE,
WARN_LEVEL,
RESN_CODE,
BAD_DEBT_MARK,
ACC_CD_BAL,
NO_AMORTIZE_DISC_AMT,
NO_AMORTIZE_ADD_AMT,
ACCT_AMT,
DEAL_RECVY_AMT,
COLL_RECVY_AMT,
OTHER_RECVY_AMT,
TOTAL_RECVY_AMT,
EIR,
STAGE,
IA_BAL,
IA_RATE,
LS_MON_STAGE,
LS_MON_IA_BAL,
IA_BAL_DIFF,
RECVY_AMT_1ST,
RECVY_AMT_2ND,
RECVY_AMT_3RD,
RECVY_AMT_4TH,
RECVY_AMT_5TH,
RECVY_AMT_6TH,
RECVY_AMT_7TH,
RECVY_AMT_8TH,
RECVY_AMT_9TH,
RECVY_AMT_10TH,
EVAL_FULL_COLL_AMT,
EVAL_NOT_RECVY_AMT,
FULL_COLL_AMT,
NO_COLL_AMT,
NOT_RECVY_AMT,
NPL1_LOAN_BAL,
NPL2_LOAN_BAL,
NPL3_LOAN_BAL,
NPL4_LOAN_BAL,
NPL5_LOAN_BAL,
NPL_BAL_AMT,
NPL_RATIO,
NPL_BAL_AMT_DIFF,
INT_RECV_AMT,
INT_IA_AMT,
IS_MAJOR,
OVDUE_MON,
IS_EXIST_COLL,
ADV_PAY_AMT,
ADV_PAY_IA_AMT,
EVAL_BRN_NM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EVAL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EVAL_DATE))='0' THEN NULL ELSE EVAL_DATE END) AS EVAL_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CASE_REL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CASE_REL_DATE))='0' THEN NULL ELSE CASE_REL_DATE END) AS CASE_REL_DATE,
EVAL_DESCR,
BAD_DEBT_AMT,
COLL_STS,
COLL_STS_NM,
CUR_IA_BAL,
ORIG_IA_BAL,
ORIG_IA_RATE,
ORIG_INT_RECV_AMT,
ORIG_ADV_PAY_IA_AMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CAL_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CAL_DATE))='0' THEN NULL ELSE CAL_DATE END) AS CAL_DATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
