-- SQL for table: EDW_GL_GLENTR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_01' AS DATA_CHK_COL,
APLQTY_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_01' AS DATA_CHK_COL,
ACTQTY_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_01' AS DATA_CHK_COL,
VALUE_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_02' AS DATA_CHK_COL,
APLQTY_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_02' AS DATA_CHK_COL,
ACTQTY_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_02' AS DATA_CHK_COL,
VALUE_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_03' AS DATA_CHK_COL,
APLQTY_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_03' AS DATA_CHK_COL,
ACTQTY_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_03' AS DATA_CHK_COL,
VALUE_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_04' AS DATA_CHK_COL,
APLQTY_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_04' AS DATA_CHK_COL,
ACTQTY_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_04' AS DATA_CHK_COL,
VALUE_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_05' AS DATA_CHK_COL,
APLQTY_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_05' AS DATA_CHK_COL,
ACTQTY_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_05' AS DATA_CHK_COL,
VALUE_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_06' AS DATA_CHK_COL,
APLQTY_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_06' AS DATA_CHK_COL,
ACTQTY_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_06' AS DATA_CHK_COL,
VALUE_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_07' AS DATA_CHK_COL,
APLQTY_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_07' AS DATA_CHK_COL,
ACTQTY_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_07' AS DATA_CHK_COL,
VALUE_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_08' AS DATA_CHK_COL,
APLQTY_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_08' AS DATA_CHK_COL,
ACTQTY_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_08' AS DATA_CHK_COL,
VALUE_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_09' AS DATA_CHK_COL,
APLQTY_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_09' AS DATA_CHK_COL,
ACTQTY_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_09' AS DATA_CHK_COL,
VALUE_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APLQTY_10' AS DATA_CHK_COL,
APLQTY_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(APLQTY_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTQTY_10' AS DATA_CHK_COL,
ACTQTY_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTQTY_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VALUE_10' AS DATA_CHK_COL,
VALUE_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(VALUE_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_GL_GLENTR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BRNO,
KIND,
SRNO,
APLSTA,
GOODNO_01,
APLQTY_01,
ACTQTY_01,
VALUE_01,
GOODNO_02,
APLQTY_02,
ACTQTY_02,
VALUE_02,
GOODNO_03,
APLQTY_03,
ACTQTY_03,
VALUE_03,
GOODNO_04,
APLQTY_04,
ACTQTY_04,
VALUE_04,
GOODNO_05,
APLQTY_05,
ACTQTY_05,
VALUE_05,
GOODNO_06,
APLQTY_06,
ACTQTY_06,
VALUE_06,
GOODNO_07,
APLQTY_07,
ACTQTY_07,
VALUE_07,
GOODNO_08,
APLQTY_08,
ACTQTY_08,
VALUE_08,
GOODNO_09,
APLQTY_09,
ACTQTY_09,
VALUE_09,
GOODNO_10,
APLQTY_10,
ACTQTY_10,
VALUE_10,
APLDAY,
APVDAY,
OUDAY,
INDAY,
OUTLR,
OUSUP,
INTLR,
INSUP,
OUBRNO,
PRVSUP,
REMARK,
SUPNO,
TLRNO,
LTXDAY,
DEBANK,
BRCRGFG,
DEBANKNM,
DENO,
CIFKEY,
CIFERR,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO,
KIND,
SRNO,
APLSTA,
GOODNO_01,
APLQTY_01,
ACTQTY_01,
VALUE_01,
GOODNO_02,
APLQTY_02,
ACTQTY_02,
VALUE_02,
GOODNO_03,
APLQTY_03,
ACTQTY_03,
VALUE_03,
GOODNO_04,
APLQTY_04,
ACTQTY_04,
VALUE_04,
GOODNO_05,
APLQTY_05,
ACTQTY_05,
VALUE_05,
GOODNO_06,
APLQTY_06,
ACTQTY_06,
VALUE_06,
GOODNO_07,
APLQTY_07,
ACTQTY_07,
VALUE_07,
GOODNO_08,
APLQTY_08,
ACTQTY_08,
VALUE_08,
GOODNO_09,
APLQTY_09,
ACTQTY_09,
VALUE_09,
GOODNO_10,
APLQTY_10,
ACTQTY_10,
VALUE_10,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APLDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APLDAY))='0' THEN NULL ELSE APLDAY END) AS APLDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APVDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APVDAY))='0' THEN NULL ELSE APVDAY END) AS APVDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OUDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OUDAY))='0' THEN NULL ELSE OUDAY END) AS OUDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(INDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(INDAY))='0' THEN NULL ELSE INDAY END) AS INDAY,
OUTLR,
OUSUP,
INTLR,
INSUP,
OUBRNO,
PRVSUP,
REMARK,
SUPNO,
TLRNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTXDAY))='0' THEN NULL ELSE LTXDAY END) AS LTXDAY,
DEBANK,
BRCRGFG,
DEBANKNM,
DENO,
CIFKEY,
CIFERR,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
