-- SQL for table: EDW_CF_ACTCMP_STAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Stage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Prestage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
CMPNAME,
ADDR,
ZIPNO1,
ZIPNO2,
TLRNO,
LUDATE,
HENTPNO,
CZONE,
CSRNO,
CEXT,
CPHONE,
NMFLG,
ADRFLG,
LUBRNO,
NMDATE,
EXTCNT,
CPHONECF,
CPHONEDT,
CPHONETM,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ACTNO,
CMPNAME,
ADDR,
ZIPNO1,
ZIPNO2,
TLRNO,
LUDATE,
HENTPNO,
CZONE,
CSRNO,
CEXT,
CPHONE,
NMFLG,
ADRFLG,
LUBRNO,
NMDATE,
EXTCNT,
CPHONECF,
CPHONEDT,
CPHONETM,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
