-- SQL for table: EDW_NCARD_SETUPCODE_STAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Stage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Prestage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
"TYPE",
TYPE_SUB,
CODE,
LANGUAGE_FAMILY,
DESCR,
DESCR_SHORT,
ADD_VAL1,
ADD_VAL2,
ADD_VAL3,
ADD_VAL4,
ADD_VAL5,
ADD_VAL6,
POST_RESULT,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
"TYPE",
TYPE_SUB,
CODE,
LANGUAGE_FAMILY,
DESCR,
DESCR_SHORT,
ADD_VAL1,
ADD_VAL2,
ADD_VAL3,
ADD_VAL4,
ADD_VAL5,
ADD_VAL6,
POST_RESULT,
MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
