-- SQL for table: EDW_EFAS_NETBANK_STAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Stage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Prestage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SN,
BATCHYYYMM,
BRANCHSN,
BRANCHNAME,
GROUPNUM,
NEWACC,
NEWACCSUM,
EMPSUM,
REALACC,
SCOREA,
ACCAVG,
DEPOSITAVG,
RATIO,
RANKB,
SCOREB,
TRADECNT,
TRADECNTSUM,
RANKC,
SCOREC,
LASTTOTAL,
TOTAL,
TRANK,
UPANDDOWN,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SN,
BATCHYYYMM,
BRANCHSN,
BRANCHNAME,
GROUPNUM,
NEWACC,
NEWACCSUM,
EMPSUM,
REALACC,
SCOREA,
ACCAVG,
DEPOSITAVG,
RATIO,
RANKB,
SCOREB,
TRADECNT,
TRADECNTSUM,
RANKC,
SCOREC,
LASTTOTAL,
TOTAL,
TRANK,
UPANDDOWN,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
