-- SQL for table: EDW_AROBO_IPMSETRBL_STAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Stage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Prestage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
RBL_LOG_ID,
CUS_CODE,
IPMSET_CODE,
ORDER_DATE,
TRAN_STATUS,
RBL_TYPE_CD,
DATA_DATE,
RBL_DUE_DATE,
ADJ_REASON,
ADJ_DESC,
RANK_CODE,
PREFERENCE_CODE,
EFFECTIVE_YN,
ADJ_TYPE_CODE,
ORG_RANK_CODE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
RBL_LOG_ID,
CUS_CODE,
IPMSET_CODE,
ORDER_DATE,
TRAN_STATUS,
RBL_TYPE_CD,
DATA_DATE,
RBL_DUE_DATE,
ADJ_REASON,
ADJ_DESC,
RANK_CODE,
PREFERENCE_CODE,
EFFECTIVE_YN,
ADJ_TYPE_CODE,
ORG_RANK_CODE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
