-- SQL for table: EDW_ELN_CRMAINFILE_STAGE
/* TRANSFORM_DATA */

/* 1. Delete 目的表 Stage data_exch_date = '#排程啟動日#' */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取 Prestage 同期別進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CASEID,
SUBSYSID,
OCID,
OFFICER,
BRAUTHDATE,
HQDISP1,
HQDISP1DATE,
HQCLOSE,
HQCLOSEDATE,
FILING_TYPE,
SWHOAGENT,
DEBTIDMFNAME,
DEBTSW,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASEID,
SUBSYSID,
OCID,
OFFICER,
BRAUTHDATE,
HQDISP1,
HQDISP1DATE,
HQCLOSE,
HQCLOSEDATE,
FILING_TYPE,
SWHOAGENT,
DEBTIDMFNAME,
DEBTSW,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
