-- SQL for table: EDW_SHR_BDATE
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
TBSDY,
HOLIDAY,
WEEKDY,
NBSDY,
NNBSDY,
N3BSDY,
N4BSDY,
N5BSDY,
N6BSDY,
LBSDY,
LLBSDY,
L3BSDY,
L4BSDY,
L5BSDY,
LMNDY,
TMNDY,
FNBSDY,
NDYCNT,
NNDYCNT,
N3DYCNT,
N4DYCNT,
N5DYCNT,
N6DYCNT,
LDYCNT,
LLDYCNT,
L3DYCNT,
L4DYCNT,
L5DYCNT,
TIMECD,
LFNBSDY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TBSDY))='0' THEN NULL ELSE TBSDY END) AS TBSDY,
HOLIDAY,
WEEKDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NBSDY))='0' THEN NULL ELSE NBSDY END) AS NBSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NNBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NNBSDY))='0' THEN NULL ELSE NNBSDY END) AS NNBSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(N3BSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(N3BSDY))='0' THEN NULL ELSE N3BSDY END) AS N3BSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(N4BSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(N4BSDY))='0' THEN NULL ELSE N4BSDY END) AS N4BSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(N5BSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(N5BSDY))='0' THEN NULL ELSE N5BSDY END) AS N5BSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(N6BSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(N6BSDY))='0' THEN NULL ELSE N6BSDY END) AS N6BSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LBSDY))='0' THEN NULL ELSE LBSDY END) AS LBSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LLBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LLBSDY))='0' THEN NULL ELSE LLBSDY END) AS LLBSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(L3BSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(L3BSDY))='0' THEN NULL ELSE L3BSDY END) AS L3BSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(L4BSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(L4BSDY))='0' THEN NULL ELSE L4BSDY END) AS L4BSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(L5BSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(L5BSDY))='0' THEN NULL ELSE L5BSDY END) AS L5BSDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LMNDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LMNDY))='0' THEN NULL ELSE LMNDY END) AS LMNDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TMNDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TMNDY))='0' THEN NULL ELSE TMNDY END) AS TMNDY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(FNBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(FNBSDY))='0' THEN NULL ELSE FNBSDY END) AS FNBSDY,
NDYCNT,
NNDYCNT,
N3DYCNT,
N4DYCNT,
N5DYCNT,
N6DYCNT,
LDYCNT,
LLDYCNT,
L3DYCNT,
L4DYCNT,
L5DYCNT,
TIMECD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LFNBSDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LFNBSDY))='0' THEN NULL ELSE LFNBSDY END) AS LFNBSDY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
