-- SQL for table: EDW_GL_GLACTMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PAGENO' AS DATA_CHK_COL,
PAGENO AS DATA_VAL,
SDG.UFN_NUMCHECK(PAGENO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LINENO' AS DATA_CHK_COL,
LINENO AS DATA_VAL,
SDG.UFN_NUMCHECK(LINENO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RISUCNT' AS DATA_CHK_COL,
RISUCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RISUCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EVTCNT' AS DATA_CHK_COL,
EVTCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(EVTCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NBBAL' AS DATA_CHK_COL,
NBBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NBBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NBCNT' AS DATA_CHK_COL,
NBCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(NBCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EBFACTCT' AS DATA_CHK_COL,
EBFACTCT AS DATA_VAL,
SDG.UFN_NUMCHECK(EBFACTCT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LTCALCNT' AS DATA_CHK_COL,
LTCALCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(LTCALCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LTFALCNT' AS DATA_CHK_COL,
LTFALCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(LTFALCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EBTRNOUTFG' AS DATA_CHK_COL,
EBTRNOUTFG AS DATA_VAL,
SDG.UFN_NUMCHECK(EBTRNOUTFG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_GL_GLACTMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
CIFKEY,
CIFERR,
OBRNO,
ACTCLS,
SEAL,
DEAD,
"STOP",
LOST,
MAILCD,
INTRCD,
PSWD,
KYC,
INVMAIL,
MBRNO,
NBNO,
PAGENO,
LINENO,
RISUCNT,
EVTCNT,
OPDAY,
CLSDAY,
NBDAY,
NBSEQ,
NBBAL,
NBCNT,
EMPNO,
"SOURCE",
EBOPFG,
EBOPDAY,
EBNBDAY,
IDFG,
IDDATE,
IDAREA,
IDPHOTO,
TLRNO,
LTXDAY,
HOLDNO,
EBNBBR,
EBFACTNO1,
EBFACTFG1,
EBFACTNO2,
EBFACTFG2,
EBFACTNO3,
EBFACTFG3,
EBFACTNO4,
EBFACTFG4,
EBFACTNO5,
EBFACTFG5,
EBFACTNO6,
EBFACTFG6,
EBFACTNO7,
EBFACTFG7,
EBFACTNO8,
EBFACTFG8,
EBFACTYR,
EBFACTCT,
LTDPACTNO,
LTDPBRNO,
LTDPAPNO,
LTDPSRNO,
LTDPCHKDG,
LTFXACTNO,
LTFXBRNO,
LTFXAPNO,
LTFXSRNO,
LTFXCHKDG,
LTSTOFG,
LTSTOSDAY,
LTSTOEDAY,
LTCALDAY,
LTCALCNT,
LTFALCNT,
LTFALSDAY,
EBTRNOUTFG,
EBTRNDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
CIFKEY,
CIFERR,
OBRNO,
ACTCLS,
SEAL,
DEAD,
"STOP",
LOST,
MAILCD,
INTRCD,
PSWD,
KYC,
INVMAIL,
MBRNO,
NBNO,
PAGENO,
LINENO,
RISUCNT,
EVTCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPDAY))='0' THEN NULL ELSE OPDAY END) AS OPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLSDAY))='0' THEN NULL ELSE CLSDAY END) AS CLSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NBDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NBDAY))='0' THEN NULL ELSE NBDAY END) AS NBDAY,
NBSEQ,
NBBAL,
NBCNT,
EMPNO,
"SOURCE",
EBOPFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EBOPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EBOPDAY))='0' THEN NULL ELSE EBOPDAY END) AS EBOPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EBNBDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EBNBDAY))='0' THEN NULL ELSE EBNBDAY END) AS EBNBDAY,
IDFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IDDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IDDATE))='0' THEN NULL ELSE IDDATE END) AS IDDATE,
IDAREA,
IDPHOTO,
TLRNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTXDAY))='0' THEN NULL ELSE LTXDAY END) AS LTXDAY,
HOLDNO,
EBNBBR,
EBFACTNO1,
EBFACTFG1,
EBFACTNO2,
EBFACTFG2,
EBFACTNO3,
EBFACTFG3,
EBFACTNO4,
EBFACTFG4,
EBFACTNO5,
EBFACTFG5,
EBFACTNO6,
EBFACTFG6,
EBFACTNO7,
EBFACTFG7,
EBFACTNO8,
EBFACTFG8,
EBFACTYR,
EBFACTCT,
LTDPBRNO||LTDPAPNO||LTDPSRNO||LTDPCHKDG,
LTDPBRNO,
LTDPAPNO,
LTDPSRNO,
LTDPCHKDG,
LTFXBRNO||LTFXAPNO||LTFXSRNO||LTFXCHKDG,
LTFXBRNO,
LTFXAPNO,
LTFXSRNO,
LTFXCHKDG,
LTSTOFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTSTOSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTSTOSDAY))='0' THEN NULL ELSE LTSTOSDAY END) AS LTSTOSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTSTOEDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTSTOEDAY))='0' THEN NULL ELSE LTSTOEDAY END) AS LTSTOEDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTCALDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTCALDAY))='0' THEN NULL ELSE LTCALDAY END) AS LTCALDAY,
LTCALCNT,
LTFALCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTFALSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTFALSDAY))='0' THEN NULL ELSE LTFALSDAY END) AS LTFALSDAY,
EBTRNOUTFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EBTRNDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EBTRNDAY))='0' THEN NULL ELSE EBTRNDAY END) AS EBTRNDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
