-- SQL for table: EDW_FXB_FCBMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BUYAMT' AS DATA_CHK_COL,
BUYAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BUYAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXCNT' AS DATA_CHK_COL,
TXCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TXCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RJTCNT' AS DATA_CHK_COL,
RJTCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RJTCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RJTSUM' AS DATA_CHK_COL,
RJTSUM AS DATA_VAL,
SDG.UFN_NUMCHECK(RJTSUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'WITHDRAW' AS DATA_CHK_COL,
WITHDRAW AS DATA_VAL,
SDG.UFN_NUMCHECK(WITHDRAW) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLSUM' AS DATA_CHK_COL,
COLSUM AS DATA_VAL,
SDG.UFN_NUMCHECK(COLSUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECCNT' AS DATA_CHK_COL,
RECCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RECCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BALAMT' AS DATA_CHK_COL,
BALAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BALAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRCCNT' AS DATA_CHK_COL,
TRCCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TRCCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRCNT' AS DATA_CHK_COL,
TRCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TRCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO' AS DATA_CHK_COL,
TXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECSUM' AS DATA_CHK_COL,
RECSUM AS DATA_VAL,
SDG.UFN_NUMCHECK(RECSUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXIDX' AS DATA_CHK_COL,
TXIDX AS DATA_VAL,
SDG.UFN_NUMCHECK(TXIDX) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_01' AS DATA_CHK_COL,
CORPNO_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_01' AS DATA_CHK_COL,
CBAMT_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_01' AS DATA_CHK_COL,
USELN_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_01' AS DATA_CHK_COL,
RSTLN_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_01' AS DATA_CHK_COL,
RTNLN_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_01' AS DATA_CHK_COL,
EXAMT_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_02' AS DATA_CHK_COL,
CORPNO_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_02' AS DATA_CHK_COL,
CBAMT_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_02' AS DATA_CHK_COL,
USELN_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_02' AS DATA_CHK_COL,
RSTLN_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_02' AS DATA_CHK_COL,
RTNLN_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_02' AS DATA_CHK_COL,
EXAMT_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_03' AS DATA_CHK_COL,
CORPNO_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_03' AS DATA_CHK_COL,
CBAMT_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_03' AS DATA_CHK_COL,
USELN_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_03' AS DATA_CHK_COL,
RSTLN_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_03' AS DATA_CHK_COL,
RTNLN_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_03' AS DATA_CHK_COL,
EXAMT_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_04' AS DATA_CHK_COL,
CORPNO_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_04' AS DATA_CHK_COL,
CBAMT_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_04' AS DATA_CHK_COL,
USELN_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_04' AS DATA_CHK_COL,
RSTLN_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_04' AS DATA_CHK_COL,
RTNLN_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_04' AS DATA_CHK_COL,
EXAMT_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_05' AS DATA_CHK_COL,
CORPNO_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_05' AS DATA_CHK_COL,
CBAMT_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_05' AS DATA_CHK_COL,
USELN_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_05' AS DATA_CHK_COL,
RSTLN_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_05' AS DATA_CHK_COL,
RTNLN_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_05' AS DATA_CHK_COL,
EXAMT_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_06' AS DATA_CHK_COL,
CORPNO_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_06' AS DATA_CHK_COL,
CBAMT_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_06' AS DATA_CHK_COL,
USELN_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_06' AS DATA_CHK_COL,
RSTLN_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_06' AS DATA_CHK_COL,
RTNLN_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_06' AS DATA_CHK_COL,
EXAMT_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_07' AS DATA_CHK_COL,
CORPNO_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_07' AS DATA_CHK_COL,
CBAMT_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_07' AS DATA_CHK_COL,
USELN_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_07' AS DATA_CHK_COL,
RSTLN_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_07' AS DATA_CHK_COL,
RTNLN_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_07' AS DATA_CHK_COL,
EXAMT_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_08' AS DATA_CHK_COL,
CORPNO_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_08' AS DATA_CHK_COL,
CBAMT_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_08' AS DATA_CHK_COL,
USELN_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_08' AS DATA_CHK_COL,
RSTLN_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_08' AS DATA_CHK_COL,
RTNLN_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_08' AS DATA_CHK_COL,
EXAMT_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_09' AS DATA_CHK_COL,
CORPNO_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_09' AS DATA_CHK_COL,
CBAMT_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_09' AS DATA_CHK_COL,
USELN_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_09' AS DATA_CHK_COL,
RSTLN_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_09' AS DATA_CHK_COL,
RTNLN_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_09' AS DATA_CHK_COL,
EXAMT_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_10' AS DATA_CHK_COL,
CORPNO_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_10' AS DATA_CHK_COL,
CBAMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_10' AS DATA_CHK_COL,
USELN_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_10' AS DATA_CHK_COL,
RSTLN_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_10' AS DATA_CHK_COL,
RTNLN_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_10' AS DATA_CHK_COL,
EXAMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_11' AS DATA_CHK_COL,
CORPNO_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_11' AS DATA_CHK_COL,
CBAMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_11' AS DATA_CHK_COL,
USELN_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_11' AS DATA_CHK_COL,
RSTLN_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_11' AS DATA_CHK_COL,
RTNLN_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_11' AS DATA_CHK_COL,
EXAMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_12' AS DATA_CHK_COL,
CORPNO_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_12' AS DATA_CHK_COL,
CBAMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_12' AS DATA_CHK_COL,
USELN_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_12' AS DATA_CHK_COL,
RSTLN_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_12' AS DATA_CHK_COL,
RTNLN_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_12' AS DATA_CHK_COL,
EXAMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_13' AS DATA_CHK_COL,
CORPNO_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_13' AS DATA_CHK_COL,
CBAMT_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_13' AS DATA_CHK_COL,
USELN_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_13' AS DATA_CHK_COL,
RSTLN_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_13' AS DATA_CHK_COL,
RTNLN_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_13' AS DATA_CHK_COL,
EXAMT_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_14' AS DATA_CHK_COL,
CORPNO_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_14' AS DATA_CHK_COL,
CBAMT_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_14' AS DATA_CHK_COL,
USELN_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_14' AS DATA_CHK_COL,
RSTLN_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_14' AS DATA_CHK_COL,
RTNLN_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_14' AS DATA_CHK_COL,
EXAMT_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_15' AS DATA_CHK_COL,
CORPNO_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_15' AS DATA_CHK_COL,
CBAMT_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_15' AS DATA_CHK_COL,
USELN_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_15' AS DATA_CHK_COL,
RSTLN_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_15' AS DATA_CHK_COL,
RTNLN_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_15' AS DATA_CHK_COL,
EXAMT_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_16' AS DATA_CHK_COL,
CORPNO_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_16' AS DATA_CHK_COL,
CBAMT_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_16' AS DATA_CHK_COL,
USELN_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_16' AS DATA_CHK_COL,
RSTLN_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_16' AS DATA_CHK_COL,
RTNLN_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_16' AS DATA_CHK_COL,
EXAMT_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_17' AS DATA_CHK_COL,
CORPNO_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_17' AS DATA_CHK_COL,
CBAMT_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_17' AS DATA_CHK_COL,
USELN_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_17' AS DATA_CHK_COL,
RSTLN_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_17' AS DATA_CHK_COL,
RTNLN_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_17' AS DATA_CHK_COL,
EXAMT_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_18' AS DATA_CHK_COL,
CORPNO_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_18' AS DATA_CHK_COL,
CBAMT_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_18' AS DATA_CHK_COL,
USELN_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_18' AS DATA_CHK_COL,
RSTLN_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_18' AS DATA_CHK_COL,
RTNLN_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_18' AS DATA_CHK_COL,
EXAMT_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_19' AS DATA_CHK_COL,
CORPNO_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_19' AS DATA_CHK_COL,
CBAMT_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_19' AS DATA_CHK_COL,
USELN_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_19' AS DATA_CHK_COL,
RSTLN_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_19' AS DATA_CHK_COL,
RTNLN_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_19' AS DATA_CHK_COL,
EXAMT_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_20' AS DATA_CHK_COL,
CORPNO_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_20' AS DATA_CHK_COL,
CBAMT_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_20' AS DATA_CHK_COL,
USELN_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_20' AS DATA_CHK_COL,
RSTLN_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_20' AS DATA_CHK_COL,
RTNLN_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_20' AS DATA_CHK_COL,
EXAMT_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_21' AS DATA_CHK_COL,
CORPNO_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_21' AS DATA_CHK_COL,
CBAMT_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_21' AS DATA_CHK_COL,
USELN_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_21' AS DATA_CHK_COL,
RSTLN_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_21' AS DATA_CHK_COL,
RTNLN_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_21' AS DATA_CHK_COL,
EXAMT_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_22' AS DATA_CHK_COL,
CORPNO_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_22' AS DATA_CHK_COL,
CBAMT_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_22' AS DATA_CHK_COL,
USELN_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_22' AS DATA_CHK_COL,
RSTLN_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_22' AS DATA_CHK_COL,
RTNLN_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_22' AS DATA_CHK_COL,
EXAMT_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_23' AS DATA_CHK_COL,
CORPNO_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_23' AS DATA_CHK_COL,
CBAMT_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_23' AS DATA_CHK_COL,
USELN_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_23' AS DATA_CHK_COL,
RSTLN_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_23' AS DATA_CHK_COL,
RTNLN_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_23' AS DATA_CHK_COL,
EXAMT_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_24' AS DATA_CHK_COL,
CORPNO_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_24' AS DATA_CHK_COL,
CBAMT_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_24' AS DATA_CHK_COL,
USELN_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_24' AS DATA_CHK_COL,
RSTLN_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_24' AS DATA_CHK_COL,
RTNLN_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_24' AS DATA_CHK_COL,
EXAMT_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_25' AS DATA_CHK_COL,
CORPNO_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_25' AS DATA_CHK_COL,
CBAMT_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_25' AS DATA_CHK_COL,
USELN_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_25' AS DATA_CHK_COL,
RSTLN_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_25' AS DATA_CHK_COL,
RTNLN_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_25' AS DATA_CHK_COL,
EXAMT_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_26' AS DATA_CHK_COL,
CORPNO_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_26' AS DATA_CHK_COL,
CBAMT_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_26' AS DATA_CHK_COL,
USELN_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_26' AS DATA_CHK_COL,
RSTLN_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_26' AS DATA_CHK_COL,
RTNLN_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_26' AS DATA_CHK_COL,
EXAMT_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_27' AS DATA_CHK_COL,
CORPNO_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_27' AS DATA_CHK_COL,
CBAMT_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_27' AS DATA_CHK_COL,
USELN_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_27' AS DATA_CHK_COL,
RSTLN_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_27' AS DATA_CHK_COL,
RTNLN_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_27' AS DATA_CHK_COL,
EXAMT_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_28' AS DATA_CHK_COL,
CORPNO_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_28' AS DATA_CHK_COL,
CBAMT_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_28' AS DATA_CHK_COL,
USELN_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_28' AS DATA_CHK_COL,
RSTLN_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_28' AS DATA_CHK_COL,
RTNLN_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_28' AS DATA_CHK_COL,
EXAMT_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_29' AS DATA_CHK_COL,
CORPNO_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_29' AS DATA_CHK_COL,
CBAMT_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_29' AS DATA_CHK_COL,
USELN_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_29' AS DATA_CHK_COL,
RSTLN_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_29' AS DATA_CHK_COL,
RTNLN_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_29' AS DATA_CHK_COL,
EXAMT_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_30' AS DATA_CHK_COL,
CORPNO_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_30' AS DATA_CHK_COL,
CBAMT_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_30' AS DATA_CHK_COL,
USELN_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSTLN_30' AS DATA_CHK_COL,
RSTLN_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(RSTLN_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTNLN_30' AS DATA_CHK_COL,
RTNLN_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTNLN_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_30' AS DATA_CHK_COL,
EXAMT_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXPAMT' AS DATA_CHK_COL,
EXPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EXPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXB_FCBMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
BKCUR1,
BKSRNO1,
CURCD,
BUYAMT,
BUYDAT,
TXCNT,
RJTCNT,
RJTSUM,
WITHDRAW,
MAILBK,
MSWFCD,
COLSUM,
RECCNT,
BALAMT,
LRECDAT,
PRCLDAT,
TRCCNT,
TRCDAT,
TRCNT,
TXTNO,
WSNO,
LASTDT,
TLRNO,
RECSUM,
LRJTDAT,
RSTDAT,
TXIDX,
CIFKEY_01,
CORPNO_01,
CBAMT_01,
USELN_01,
RSTLN_01,
RTNLN_01,
USECD_01,
CUSTOM_01,
CN_01,
EXAMT_01,
CKKIND_01,
CIFKEY_02,
CORPNO_02,
CBAMT_02,
USELN_02,
RSTLN_02,
RTNLN_02,
USECD_02,
CUSTOM_02,
CN_02,
EXAMT_02,
CKKIND_02,
CIFKEY_03,
CORPNO_03,
CBAMT_03,
USELN_03,
RSTLN_03,
RTNLN_03,
USECD_03,
CUSTOM_03,
CN_03,
EXAMT_03,
CKKIND_03,
CIFKEY_04,
CORPNO_04,
CBAMT_04,
USELN_04,
RSTLN_04,
RTNLN_04,
USECD_04,
CUSTOM_04,
CN_04,
EXAMT_04,
CKKIND_04,
CIFKEY_05,
CORPNO_05,
CBAMT_05,
USELN_05,
RSTLN_05,
RTNLN_05,
USECD_05,
CUSTOM_05,
CN_05,
EXAMT_05,
CKKIND_05,
CIFKEY_06,
CORPNO_06,
CBAMT_06,
USELN_06,
RSTLN_06,
RTNLN_06,
USECD_06,
CUSTOM_06,
CN_06,
EXAMT_06,
CKKIND_06,
CIFKEY_07,
CORPNO_07,
CBAMT_07,
USELN_07,
RSTLN_07,
RTNLN_07,
USECD_07,
CUSTOM_07,
CN_07,
EXAMT_07,
CKKIND_07,
CIFKEY_08,
CORPNO_08,
CBAMT_08,
USELN_08,
RSTLN_08,
RTNLN_08,
USECD_08,
CUSTOM_08,
CN_08,
EXAMT_08,
CKKIND_08,
CIFKEY_09,
CORPNO_09,
CBAMT_09,
USELN_09,
RSTLN_09,
RTNLN_09,
USECD_09,
CUSTOM_09,
CN_09,
EXAMT_09,
CKKIND_09,
CIFKEY_10,
CORPNO_10,
CBAMT_10,
USELN_10,
RSTLN_10,
RTNLN_10,
USECD_10,
CUSTOM_10,
CN_10,
EXAMT_10,
CKKIND_10,
CIFKEY_11,
CORPNO_11,
CBAMT_11,
USELN_11,
RSTLN_11,
RTNLN_11,
USECD_11,
CUSTOM_11,
CN_11,
EXAMT_11,
CKKIND_11,
CIFKEY_12,
CORPNO_12,
CBAMT_12,
USELN_12,
RSTLN_12,
RTNLN_12,
USECD_12,
CUSTOM_12,
CN_12,
EXAMT_12,
CKKIND_12,
CIFKEY_13,
CORPNO_13,
CBAMT_13,
USELN_13,
RSTLN_13,
RTNLN_13,
USECD_13,
CUSTOM_13,
CN_13,
EXAMT_13,
CKKIND_13,
CIFKEY_14,
CORPNO_14,
CBAMT_14,
USELN_14,
RSTLN_14,
RTNLN_14,
USECD_14,
CUSTOM_14,
CN_14,
EXAMT_14,
CKKIND_14,
CIFKEY_15,
CORPNO_15,
CBAMT_15,
USELN_15,
RSTLN_15,
RTNLN_15,
USECD_15,
CUSTOM_15,
CN_15,
EXAMT_15,
CKKIND_15,
CIFKEY_16,
CORPNO_16,
CBAMT_16,
USELN_16,
RSTLN_16,
RTNLN_16,
USECD_16,
CUSTOM_16,
CN_16,
EXAMT_16,
CKKIND_16,
CIFKEY_17,
CORPNO_17,
CBAMT_17,
USELN_17,
RSTLN_17,
RTNLN_17,
USECD_17,
CUSTOM_17,
CN_17,
EXAMT_17,
CKKIND_17,
CIFKEY_18,
CORPNO_18,
CBAMT_18,
USELN_18,
RSTLN_18,
RTNLN_18,
USECD_18,
CUSTOM_18,
CN_18,
EXAMT_18,
CKKIND_18,
CIFKEY_19,
CORPNO_19,
CBAMT_19,
USELN_19,
RSTLN_19,
RTNLN_19,
USECD_19,
CUSTOM_19,
CN_19,
EXAMT_19,
CKKIND_19,
CIFKEY_20,
CORPNO_20,
CBAMT_20,
USELN_20,
RSTLN_20,
RTNLN_20,
USECD_20,
CUSTOM_20,
CN_20,
EXAMT_20,
CKKIND_20,
CIFKEY_21,
CORPNO_21,
CBAMT_21,
USELN_21,
RSTLN_21,
RTNLN_21,
USECD_21,
CUSTOM_21,
CN_21,
EXAMT_21,
CKKIND_21,
CIFKEY_22,
CORPNO_22,
CBAMT_22,
USELN_22,
RSTLN_22,
RTNLN_22,
USECD_22,
CUSTOM_22,
CN_22,
EXAMT_22,
CKKIND_22,
CIFKEY_23,
CORPNO_23,
CBAMT_23,
USELN_23,
RSTLN_23,
RTNLN_23,
USECD_23,
CUSTOM_23,
CN_23,
EXAMT_23,
CKKIND_23,
CIFKEY_24,
CORPNO_24,
CBAMT_24,
USELN_24,
RSTLN_24,
RTNLN_24,
USECD_24,
CUSTOM_24,
CN_24,
EXAMT_24,
CKKIND_24,
CIFKEY_25,
CORPNO_25,
CBAMT_25,
USELN_25,
RSTLN_25,
RTNLN_25,
USECD_25,
CUSTOM_25,
CN_25,
EXAMT_25,
CKKIND_25,
CIFKEY_26,
CORPNO_26,
CBAMT_26,
USELN_26,
RSTLN_26,
RTNLN_26,
USECD_26,
CUSTOM_26,
CN_26,
EXAMT_26,
CKKIND_26,
CIFKEY_27,
CORPNO_27,
CBAMT_27,
USELN_27,
RSTLN_27,
RTNLN_27,
USECD_27,
CUSTOM_27,
CN_27,
EXAMT_27,
CKKIND_27,
CIFKEY_28,
CORPNO_28,
CBAMT_28,
USELN_28,
RSTLN_28,
RTNLN_28,
USECD_28,
CUSTOM_28,
CN_28,
EXAMT_28,
CKKIND_28,
CIFKEY_29,
CORPNO_29,
CBAMT_29,
USELN_29,
RSTLN_29,
RTNLN_29,
USECD_29,
CUSTOM_29,
CN_29,
EXAMT_29,
CKKIND_29,
CIFKEY_30,
CORPNO_30,
CBAMT_30,
USELN_30,
RSTLN_30,
RTNLN_30,
USECD_30,
CUSTOM_30,
CN_30,
EXAMT_30,
CKKIND_30,
USDAREA,
EXPAMT,
NTXDAY,
CBKIND,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
BKCUR1,
BKSRNO1,
CURCD,
BUYAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BUYDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BUYDAT))='0' THEN NULL ELSE BUYDAT END) AS BUYDAT,
TXCNT,
RJTCNT,
RJTSUM,
WITHDRAW,
MAILBK,
MSWFCD,
COLSUM,
RECCNT,
BALAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRECDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRECDAT))='0' THEN NULL ELSE LRECDAT END) AS LRECDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRCLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRCLDAT))='0' THEN NULL ELSE PRCLDAT END) AS PRCLDAT,
TRCCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TRCDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TRCDAT))='0' THEN NULL ELSE TRCDAT END) AS TRCDAT,
TRCNT,
TXTNO,
WSNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
TLRNO,
RECSUM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRJTDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRJTDAT))='0' THEN NULL ELSE LRJTDAT END) AS LRJTDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RSTDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RSTDAT))='0' THEN NULL ELSE RSTDAT END) AS RSTDAT,
TXIDX,
CIFKEY_01,
CORPNO_01,
CBAMT_01,
USELN_01,
RSTLN_01,
RTNLN_01,
USECD_01,
CUSTOM_01,
CN_01,
EXAMT_01,
CKKIND_01,
CIFKEY_02,
CORPNO_02,
CBAMT_02,
USELN_02,
RSTLN_02,
RTNLN_02,
USECD_02,
CUSTOM_02,
CN_02,
EXAMT_02,
CKKIND_02,
CIFKEY_03,
CORPNO_03,
CBAMT_03,
USELN_03,
RSTLN_03,
RTNLN_03,
USECD_03,
CUSTOM_03,
CN_03,
EXAMT_03,
CKKIND_03,
CIFKEY_04,
CORPNO_04,
CBAMT_04,
USELN_04,
RSTLN_04,
RTNLN_04,
USECD_04,
CUSTOM_04,
CN_04,
EXAMT_04,
CKKIND_04,
CIFKEY_05,
CORPNO_05,
CBAMT_05,
USELN_05,
RSTLN_05,
RTNLN_05,
USECD_05,
CUSTOM_05,
CN_05,
EXAMT_05,
CKKIND_05,
CIFKEY_06,
CORPNO_06,
CBAMT_06,
USELN_06,
RSTLN_06,
RTNLN_06,
USECD_06,
CUSTOM_06,
CN_06,
EXAMT_06,
CKKIND_06,
CIFKEY_07,
CORPNO_07,
CBAMT_07,
USELN_07,
RSTLN_07,
RTNLN_07,
USECD_07,
CUSTOM_07,
CN_07,
EXAMT_07,
CKKIND_07,
CIFKEY_08,
CORPNO_08,
CBAMT_08,
USELN_08,
RSTLN_08,
RTNLN_08,
USECD_08,
CUSTOM_08,
CN_08,
EXAMT_08,
CKKIND_08,
CIFKEY_09,
CORPNO_09,
CBAMT_09,
USELN_09,
RSTLN_09,
RTNLN_09,
USECD_09,
CUSTOM_09,
CN_09,
EXAMT_09,
CKKIND_09,
CIFKEY_10,
CORPNO_10,
CBAMT_10,
USELN_10,
RSTLN_10,
RTNLN_10,
USECD_10,
CUSTOM_10,
CN_10,
EXAMT_10,
CKKIND_10,
CIFKEY_11,
CORPNO_11,
CBAMT_11,
USELN_11,
RSTLN_11,
RTNLN_11,
USECD_11,
CUSTOM_11,
CN_11,
EXAMT_11,
CKKIND_11,
CIFKEY_12,
CORPNO_12,
CBAMT_12,
USELN_12,
RSTLN_12,
RTNLN_12,
USECD_12,
CUSTOM_12,
CN_12,
EXAMT_12,
CKKIND_12,
CIFKEY_13,
CORPNO_13,
CBAMT_13,
USELN_13,
RSTLN_13,
RTNLN_13,
USECD_13,
CUSTOM_13,
CN_13,
EXAMT_13,
CKKIND_13,
CIFKEY_14,
CORPNO_14,
CBAMT_14,
USELN_14,
RSTLN_14,
RTNLN_14,
USECD_14,
CUSTOM_14,
CN_14,
EXAMT_14,
CKKIND_14,
CIFKEY_15,
CORPNO_15,
CBAMT_15,
USELN_15,
RSTLN_15,
RTNLN_15,
USECD_15,
CUSTOM_15,
CN_15,
EXAMT_15,
CKKIND_15,
CIFKEY_16,
CORPNO_16,
CBAMT_16,
USELN_16,
RSTLN_16,
RTNLN_16,
USECD_16,
CUSTOM_16,
CN_16,
EXAMT_16,
CKKIND_16,
CIFKEY_17,
CORPNO_17,
CBAMT_17,
USELN_17,
RSTLN_17,
RTNLN_17,
USECD_17,
CUSTOM_17,
CN_17,
EXAMT_17,
CKKIND_17,
CIFKEY_18,
CORPNO_18,
CBAMT_18,
USELN_18,
RSTLN_18,
RTNLN_18,
USECD_18,
CUSTOM_18,
CN_18,
EXAMT_18,
CKKIND_18,
CIFKEY_19,
CORPNO_19,
CBAMT_19,
USELN_19,
RSTLN_19,
RTNLN_19,
USECD_19,
CUSTOM_19,
CN_19,
EXAMT_19,
CKKIND_19,
CIFKEY_20,
CORPNO_20,
CBAMT_20,
USELN_20,
RSTLN_20,
RTNLN_20,
USECD_20,
CUSTOM_20,
CN_20,
EXAMT_20,
CKKIND_20,
CIFKEY_21,
CORPNO_21,
CBAMT_21,
USELN_21,
RSTLN_21,
RTNLN_21,
USECD_21,
CUSTOM_21,
CN_21,
EXAMT_21,
CKKIND_21,
CIFKEY_22,
CORPNO_22,
CBAMT_22,
USELN_22,
RSTLN_22,
RTNLN_22,
USECD_22,
CUSTOM_22,
CN_22,
EXAMT_22,
CKKIND_22,
CIFKEY_23,
CORPNO_23,
CBAMT_23,
USELN_23,
RSTLN_23,
RTNLN_23,
USECD_23,
CUSTOM_23,
CN_23,
EXAMT_23,
CKKIND_23,
CIFKEY_24,
CORPNO_24,
CBAMT_24,
USELN_24,
RSTLN_24,
RTNLN_24,
USECD_24,
CUSTOM_24,
CN_24,
EXAMT_24,
CKKIND_24,
CIFKEY_25,
CORPNO_25,
CBAMT_25,
USELN_25,
RSTLN_25,
RTNLN_25,
USECD_25,
CUSTOM_25,
CN_25,
EXAMT_25,
CKKIND_25,
CIFKEY_26,
CORPNO_26,
CBAMT_26,
USELN_26,
RSTLN_26,
RTNLN_26,
USECD_26,
CUSTOM_26,
CN_26,
EXAMT_26,
CKKIND_26,
CIFKEY_27,
CORPNO_27,
CBAMT_27,
USELN_27,
RSTLN_27,
RTNLN_27,
USECD_27,
CUSTOM_27,
CN_27,
EXAMT_27,
CKKIND_27,
CIFKEY_28,
CORPNO_28,
CBAMT_28,
USELN_28,
RSTLN_28,
RTNLN_28,
USECD_28,
CUSTOM_28,
CN_28,
EXAMT_28,
CKKIND_28,
CIFKEY_29,
CORPNO_29,
CBAMT_29,
USELN_29,
RSTLN_29,
RTNLN_29,
USECD_29,
CUSTOM_29,
CN_29,
EXAMT_29,
CKKIND_29,
CIFKEY_30,
CORPNO_30,
CBAMT_30,
USELN_30,
RSTLN_30,
RTNLN_30,
USECD_30,
CUSTOM_30,
CN_30,
EXAMT_30,
CKKIND_30,
USDAREA,
EXPAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
CBKIND,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
