-- SQL for table: EDW_FXF_FRPCEN
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'"NATURAL"' AS DATA_CHK_COL,
"NATURAL" AS DATA_VAL,
SDG.UFN_NUMCHECK("NATURAL") AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPECBNK' AS DATA_CHK_COL,
SPECBNK AS DATA_VAL,
SDG.UFN_NUMCHECK(SPECBNK) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AMT' AS DATA_CHK_COL,
AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INTAMT' AS DATA_CHK_COL,
INTAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(INTAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXRATE' AS DATA_CHK_COL,
EXRATE AS DATA_VAL,
SDG.UFN_NUMCHECK(EXRATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NCFG' AS DATA_CHK_COL,
NCFG AS DATA_VAL,
SDG.UFN_NUMCHECK(NCFG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO' AS DATA_CHK_COL,
TXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FAXFG' AS DATA_CHK_COL,
FAXFG AS DATA_VAL,
SDG.UFN_NUMCHECK(FAXFG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXF_FRPCEN
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
DATANO,
JOBCODE,
CURCD,
ACBRNO,
REMTYP,
KINDCOD,
CIFKEY,
BIRDAY,
ISSDAY,
EXPDAY,
SPLIT,
CLASS,
"TOP",
"690CODE",
CNTRY,
REPFLAG,
QID,
"NATURAL",
DATAKID,
APROVFLAG,
SPECBNK,
DOCNO,
OPNAME,
SWIFT,
OPBANK,
ACCOUNT,
AMT,
INTAMT,
EXRATE,
"SOURCE",
DATADATE,
NCFG,
TXDATE,
KINBR,
RBRNO,
WSNO,
TXTNO,
TXCD,
BRCODE,
SWFCUR,
SEQNO,
OCLASS,
MLCD,
DSCPT,
ORGTXCD,
FAXFG,
NUSECDX,
AGDNO,
TRADT,
TRATYPE,
O690CODE,
PURPOSE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
DATANO,
JOBCODE,
CURCD,
ACBRNO,
REMTYP,
KINDCOD,
CIFKEY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BIRDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BIRDAY))='0' THEN NULL ELSE BIRDAY END) AS BIRDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISSDAY))='0' THEN NULL ELSE ISSDAY END) AS ISSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EXPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EXPDAY))='0' THEN NULL ELSE EXPDAY END) AS EXPDAY,
SPLIT,
CLASS,
"TOP",
"690CODE",
CNTRY,
REPFLAG,
QID,
"NATURAL",
DATAKID,
APROVFLAG,
SPECBNK,
DOCNO,
OPNAME,
SWIFT,
OPBANK,
ACCOUNT,
AMT,
INTAMT,
EXRATE,
"SOURCE",
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATADATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATADATE))='0' THEN NULL ELSE DATADATE END) AS DATADATE,
NCFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXDATE))='0' THEN NULL ELSE TXDATE END) AS TXDATE,
KINBR,
RBRNO,
WSNO,
TXTNO,
TXCD,
BRCODE,
SWFCUR,
SEQNO,
OCLASS,
MLCD,
DSCPT,
ORGTXCD,
FAXFG,
NUSECDX,
AGDNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TRADT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TRADT))='0' THEN NULL ELSE TRADT END) AS TRADT,
TRATYPE,
O690CODE,
PURPOSE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
