-- SQL for table: EDW_FXM_FIMMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'YEAR' AS DATA_CHK_COL,
YEAR AS DATA_VAL,
SDG.UFN_NUMCHECK(YEAR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO' AS DATA_CHK_COL,
CORPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IMCNT' AS DATA_CHK_COL,
IMCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(IMCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MODCNT' AS DATA_CHK_COL,
MODCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(MODCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ABSCNT' AS DATA_CHK_COL,
ABSCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(ABSCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RBCNT' AS DATA_CHK_COL,
RBCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RBCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LGCNT' AS DATA_CHK_COL,
LGCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(LGCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AMDCNT' AS DATA_CHK_COL,
AMDCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(AMDCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BPRCNT' AS DATA_CHK_COL,
BPRCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(BPRCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LCXRATE' AS DATA_CHK_COL,
LCXRATE AS DATA_VAL,
SDG.UFN_NUMCHECK(LCXRATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PCENT' AS DATA_CHK_COL,
PCENT AS DATA_VAL,
SDG.UFN_NUMCHECK(PCENT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LTXTNO' AS DATA_CHK_COL,
LTXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(LTXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OFCAMT' AS DATA_CHK_COL,
OFCAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OFCAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OLCAMT' AS DATA_CHK_COL,
OLCAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OLCAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OLCBAL' AS DATA_CHK_COL,
OLCBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(OLCBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MGAMT' AS DATA_CHK_COL,
MGAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(MGAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MGBAL' AS DATA_CHK_COL,
MGBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(MGBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IBBAL' AS DATA_CHK_COL,
IBBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(IBBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PREBAL' AS DATA_CHK_COL,
PREBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(PREBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BPRBAL' AS DATA_CHK_COL,
BPRBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(BPRBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FCAMT' AS DATA_CHK_COL,
FCAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(FCAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ULNAMT' AS DATA_CHK_COL,
ULNAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ULNAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ULNBAL' AS DATA_CHK_COL,
ULNBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ULNBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTPAYF' AS DATA_CHK_COL,
ACTPAYF AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTPAYF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTRCVF' AS DATA_CHK_COL,
ACTRCVF AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTRCVF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BTENOR' AS DATA_CHK_COL,
BTENOR AS DATA_VAL,
SDG.UFN_NUMCHECK(BTENOR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'STENOR' AS DATA_CHK_COL,
STENOR AS DATA_VAL,
SDG.UFN_NUMCHECK(STENOR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CN' AS DATA_CHK_COL,
CN AS DATA_VAL,
SDG.UFN_NUMCHECK(CN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LNSEQ' AS DATA_CHK_COL,
LNSEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(LNSEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EBYEAR' AS DATA_CHK_COL,
EBYEAR AS DATA_VAL,
SDG.UFN_NUMCHECK(EBYEAR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXM_FIMMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
YEAR,
PREFIX,
APCOD,
SRNO,
ACBRNO,
BKCUR,
BKSRNO,
ENTPNO,
CORPNO,
LNACTNO,
OVDUACT,
RBRNO,
KINBR,
ACTCLS,
AMTCD,
VDAYCD,
ADCCD,
OBUFG,
GNOFG,
COVFG,
LMTFG,
APTYP,
CURCD,
LCTYP,
ADCBK,
ASWFCD,
TCLBK,
TSWFCD,
ICDNO,
IMCNT,
MODCNT,
ABSCNT,
RBCNT,
LGCNT,
AMDCNT,
BPRCNT,
LCXRATE,
CNTRYCD,
PCENT,
SPLIT,
BKCODE1,
BKCODE2,
LWSNO,
LTXTNO,
OFCAMT,
OLCAMT,
OLCBAL,
MGAMT,
MGBAL,
IBBAL,
PREBAL,
BPRBAL,
FCAMT,
ULNAMT,
ULNBAL,
ACTPAYF,
ACTRCVF,
ISUDT,
VLDATE,
EDAY,
LTXDAY,
BTENOR,
STENOR,
CUSTOM,
CN,
LNSEQ,
LNCUR,
EBTYPE,
EBYEAR,
EBSRNO,
NTXDAY,
CNGOODS,
EXNAL,
IMNAL,
GRCD,
GRKIND,
ESGCD,
ESGKIND,
ESGCNL,
GRTXCD,
GRDAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
YEAR,
PREFIX,
APCOD,
SRNO,
ACBRNO,
BKCUR,
BKSRNO,
ENTPNO,
CORPNO,
LNACTNO,
OVDUACT,
RBRNO,
KINBR,
ACTCLS,
AMTCD,
VDAYCD,
ADCCD,
OBUFG,
GNOFG,
COVFG,
LMTFG,
APTYP,
CURCD,
LCTYP,
ADCBK,
ASWFCD,
TCLBK,
TSWFCD,
ICDNO,
IMCNT,
MODCNT,
ABSCNT,
RBCNT,
LGCNT,
AMDCNT,
BPRCNT,
LCXRATE,
CNTRYCD,
PCENT,
SPLIT,
BKCODE1,
BKCODE2,
LWSNO,
LTXTNO,
OFCAMT,
OLCAMT,
OLCBAL,
MGAMT,
MGBAL,
IBBAL,
PREBAL,
BPRBAL,
FCAMT,
ULNAMT,
ULNBAL,
ACTPAYF,
ACTRCVF,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISUDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISUDT))='0' THEN NULL ELSE ISUDT END) AS ISUDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(VLDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(VLDATE))='0' THEN NULL ELSE VLDATE END) AS VLDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY))='0' THEN NULL ELSE EDAY END) AS EDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTXDAY))='0' THEN NULL ELSE LTXDAY END) AS LTXDAY,
BTENOR,
STENOR,
CUSTOM,
CN,
LNSEQ,
LNCUR,
EBTYPE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EBYEAR), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EBYEAR))='0' THEN NULL ELSE EBYEAR END) AS EBYEAR,
EBSRNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
CNGOODS,
EXNAL,
IMNAL,
GRCD,
GRKIND,
ESGCD,
ESGKIND,
ESGCNL,
GRTXCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRDAY))='0' THEN NULL ELSE GRDAY END) AS GRDAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
