-- SQL for table: EDW_FC_FSTPD
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RGAMT' AS DATA_CHK_COL,
RGAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RGAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSAMT' AS DATA_CHK_COL,
RSAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RSAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CKCNT' AS DATA_CHK_COL,
CKCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CKCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTIME' AS DATA_CHK_COL,
TXTIME AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTIME) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RPAMT' AS DATA_CHK_COL,
RPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BHCD' AS DATA_CHK_COL,
BHCD AS DATA_VAL,
SDG.UFN_NUMCHECK(BHCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FC_FSTPD
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
STPCD,
FILNO,
RGDAY,
RGAMT,
RSAMT,
CURCD,
ACTCLS,
CLSDAY,
TLRNO,
CKCNT,
CKDAY,
RBRNO,
TXTIME,
MEMO,
UNIT,
RGDATE,
RGCHAR,
RGNO,
RGKIND,
RPAMT,
RPTLR,
RPDATE,
RDMEMO,
RDTLR,
RDDATE,
BHCD,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO ||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
STPCD,
FILNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RGDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RGDAY))='0' THEN NULL ELSE RGDAY END) AS RGDAY,
RGAMT,
RSAMT,
CURCD,
ACTCLS,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLSDAY))='0' THEN NULL ELSE CLSDAY END) AS CLSDAY,
TLRNO,
CKCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CKDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CKDAY))='0' THEN NULL ELSE CKDAY END) AS CKDAY,
RBRNO,
TXTIME,
MEMO,
UNIT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RGDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RGDATE))='0' THEN NULL ELSE RGDATE END) AS RGDATE,
RGCHAR,
RGNO,
RGKIND,
RPAMT,
RPTLR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RPDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RPDATE))='0' THEN NULL ELSE RPDATE END) AS RPDATE,
RDMEMO,
RDTLR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RDDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RDDATE))='0' THEN NULL ELSE RDDATE END) AS RDDATE,
BHCD,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
