-- SQL for table: EDW_ELN_CRIRBSCORE
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXNO' AS DATA_CHK_COL,
TXNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASEITEMID' AS DATA_CHK_COL,
CASEITEMID AS DATA_VAL,
SDG.UFN_NUMCHECK(CASEITEMID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RATING_SEQ' AS DATA_CHK_COL,
RATING_SEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(RATING_SEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GRADE_SCORE' AS DATA_CHK_COL,
GRADE_SCORE AS DATA_VAL,
SDG.UFN_NUMCHECK(GRADE_SCORE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GRADE_PD' AS DATA_CHK_COL,
GRADE_PD AS DATA_VAL,
SDG.UFN_NUMCHECK(GRADE_PD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NON_ONE_YEAR' AS DATA_CHK_COL,
NON_ONE_YEAR AS DATA_VAL,
SDG.UFN_NUMCHECK(NON_ONE_YEAR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MISSING_VALUE_EXCEED30' AS DATA_CHK_COL,
MISSING_VALUE_EXCEED30 AS DATA_VAL,
SDG.UFN_NUMCHECK(MISSING_VALUE_EXCEED30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_MAINEFILE_SWJCICQRY' AS DATA_CHK_COL,
CR_MAINEFILE_SWJCICQRY AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_MAINEFILE_SWJCICQRY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_HRSTDENSU_SWJCICQRY' AS DATA_CHK_COL,
CR_HRSTDENSU_SWJCICQRY AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_HRSTDENSU_SWJCICQRY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAD_OWNER' AS DATA_CHK_COL,
BAD_OWNER AS DATA_VAL,
SDG.UFN_NUMCHECK(BAD_OWNER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'R0401CD' AS DATA_CHK_COL,
R0401CD AS DATA_VAL,
SDG.UFN_NUMCHECK(R0401CD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SUGGEST_PD' AS DATA_CHK_COL,
SUGGEST_PD AS DATA_VAL,
SDG.UFN_NUMCHECK(SUGGEST_PD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACARD_PRE_SCORE' AS DATA_CHK_COL,
ACARD_PRE_SCORE AS DATA_VAL,
SDG.UFN_NUMCHECK(ACARD_PRE_SCORE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACARD_PRE_PD' AS DATA_CHK_COL,
ACARD_PRE_PD AS DATA_VAL,
SDG.UFN_NUMCHECK(ACARD_PRE_PD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BCARD_PRE_SCORE' AS DATA_CHK_COL,
BCARD_PRE_SCORE AS DATA_VAL,
SDG.UFN_NUMCHECK(BCARD_PRE_SCORE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BCARD_PRE_PD' AS DATA_CHK_COL,
BCARD_PRE_PD AS DATA_VAL,
SDG.UFN_NUMCHECK(BCARD_PRE_PD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LOANCURRAMT' AS DATA_CHK_COL,
LOANCURRAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(LOANCURRAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MISSING_JCIC' AS DATA_CHK_COL,
MISSING_JCIC AS DATA_VAL,
SDG.UFN_NUMCHECK(MISSING_JCIC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DEFAULT_FLAG' AS DATA_CHK_COL,
DEFAULT_FLAG AS DATA_VAL,
SDG.UFN_NUMCHECK(DEFAULT_FLAG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACARD_PRE_CASEITEMID' AS DATA_CHK_COL,
ACARD_PRE_CASEITEMID AS DATA_VAL,
SDG.UFN_NUMCHECK(ACARD_PRE_CASEITEMID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_ELN_CRIRBSCORE
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BATCH_DT,
BATCH_ID,
CASEID,
TXNO,
SCORE_TIME,
CASEITEMID,
APPNAME,
BRID,
RATING_SEQ,
GRADE_SCORE,
GRADE_RANK,
GRADE_PD,
GRADE_TIME,
NON_ONE_YEAR,
MISSING_VALUE_EXCEED30,
CR_MAINEFILE_SWJCICQRY,
CR_HRSTDENSU_SWJCICQRY,
BAD_OWNER,
R0401CD,
SUGGEST_SCORE,
SUGGEST_RANK,
SUGGEST_PD,
ACARD_PRE_SCORE_DT,
ACARD_PRE_SCORE,
ACARD_PRE_RANK,
ACARD_PRE_PD,
ACARD_TOT_RANK,
ACCOUNT,
BCARD_PRE_SCORE_DT,
BCARD_PRE_SCORE,
BCARD_PRE_RANK,
BCARD_PRE_PD,
BCARD_TOT_RANK,
LOANCURRAMT,
MISSING_JCIC,
MODEL_TYPE,
ERROR_CODE,
DEFAULT_FLAG,
FDD,
ACARD_PRE_CASEID,
ACARD_PRE_CASEITEMID,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BATCH_DT,
BATCH_ID,
CASEID,
TXNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SCORE_TIME), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SCORE_TIME))='0' THEN NULL ELSE SCORE_TIME END) AS SCORE_TIME,
CASEITEMID,
APPNAME,
BRID,
RATING_SEQ,
GRADE_SCORE,
GRADE_RANK,
GRADE_PD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRADE_TIME), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRADE_TIME))='0' THEN NULL ELSE GRADE_TIME END) AS GRADE_TIME,
NON_ONE_YEAR,
MISSING_VALUE_EXCEED30,
CR_MAINEFILE_SWJCICQRY,
CR_HRSTDENSU_SWJCICQRY,
BAD_OWNER,
R0401CD,
SUGGEST_SCORE,
SUGGEST_RANK,
SUGGEST_PD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ACARD_PRE_SCORE_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ACARD_PRE_SCORE_DT))='0' THEN NULL ELSE ACARD_PRE_SCORE_DT END) AS ACARD_PRE_SCORE_DT,
ACARD_PRE_SCORE,
ACARD_PRE_RANK,
ACARD_PRE_PD,
ACARD_TOT_RANK,
ACCOUNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BCARD_PRE_SCORE_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BCARD_PRE_SCORE_DT))='0' THEN NULL ELSE BCARD_PRE_SCORE_DT END) AS BCARD_PRE_SCORE_DT,
BCARD_PRE_SCORE,
BCARD_PRE_RANK,
BCARD_PRE_PD,
BCARD_TOT_RANK,
LOANCURRAMT,
MISSING_JCIC,
MODEL_TYPE,
ERROR_CODE,
DEFAULT_FLAG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(FDD), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(FDD))='0' THEN NULL ELSE FDD END) AS FDD,
ACARD_PRE_CASEID,
ACARD_PRE_CASEITEMID,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
