-- SQL for table: EDW_WMS_TXNTRANFL
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MGN_ASSET_AMT' AS DATA_CHK_COL,
MGN_ASSET_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(MGN_ASSET_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MGN_ASSET_AMT_NEED' AS DATA_CHK_COL,
MGN_ASSET_AMT_NEED AS DATA_VAL,
SDG.UFN_NUMCHECK(MGN_ASSET_AMT_NEED) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SALES_AUM_ORG' AS DATA_CHK_COL,
SALES_AUM_ORG AS DATA_VAL,
SDG.UFN_NUMCHECK(SALES_AUM_ORG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SALES_AUM' AS DATA_CHK_COL,
SALES_AUM AS DATA_VAL,
SDG.UFN_NUMCHECK(SALES_AUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RATE' AS DATA_CHK_COL,
RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SALES_PCNT' AS DATA_CHK_COL,
SALES_PCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(SALES_PCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DIST_PCNT' AS DATA_CHK_COL,
DIST_PCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(DIST_PCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AO_GET' AS DATA_CHK_COL,
AO_GET AS DATA_VAL,
SDG.UFN_NUMCHECK(AO_GET) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INTRO_GET' AS DATA_CHK_COL,
INTRO_GET AS DATA_VAL,
SDG.UFN_NUMCHECK(INTRO_GET) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CATCH_PCNT' AS DATA_CHK_COL,
CATCH_PCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CATCH_PCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CATCH_PCNT_SAO' AS DATA_CHK_COL,
CATCH_PCNT_SAO AS DATA_VAL,
SDG.UFN_NUMCHECK(CATCH_PCNT_SAO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SAO_AUM' AS DATA_CHK_COL,
SAO_AUM AS DATA_VAL,
SDG.UFN_NUMCHECK(SAO_AUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DSAO_AUM' AS DATA_CHK_COL,
DSAO_AUM AS DATA_VAL,
SDG.UFN_NUMCHECK(DSAO_AUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INTRO_AUM' AS DATA_CHK_COL,
INTRO_AUM AS DATA_VAL,
SDG.UFN_NUMCHECK(INTRO_AUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SAO_AUM_18' AS DATA_CHK_COL,
SAO_AUM_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(SAO_AUM_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DSAO_AUM_18' AS DATA_CHK_COL,
DSAO_AUM_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(DSAO_AUM_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FEBN' AS DATA_CHK_COL,
FEBN AS DATA_VAL,
SDG.UFN_NUMCHECK(FEBN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DISCNT' AS DATA_CHK_COL,
DISCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(DISCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INI_SALES_AUM' AS DATA_CHK_COL,
INI_SALES_AUM AS DATA_VAL,
SDG.UFN_NUMCHECK(INI_SALES_AUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SALES_AUM_COEF' AS DATA_CHK_COL,
SALES_AUM_COEF AS DATA_VAL,
SDG.UFN_NUMCHECK(SALES_AUM_COEF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SALES_PCNT_BRA' AS DATA_CHK_COL,
SALES_PCNT_BRA AS DATA_VAL,
SDG.UFN_NUMCHECK(SALES_PCNT_BRA) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DIST_PCNT_BRA' AS DATA_CHK_COL,
DIST_PCNT_BRA AS DATA_VAL,
SDG.UFN_NUMCHECK(DIST_PCNT_BRA) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SBRA_AUM' AS DATA_CHK_COL,
SBRA_AUM AS DATA_VAL,
SDG.UFN_NUMCHECK(SBRA_AUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DSBRA_AUM' AS DATA_CHK_COL,
DSBRA_AUM AS DATA_VAL,
SDG.UFN_NUMCHECK(DSBRA_AUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VERSION' AS DATA_CHK_COL,
VERSION AS DATA_VAL,
SDG.UFN_NUMCHECK(VERSION) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXN_COUNT' AS DATA_CHK_COL,
TXN_COUNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TXN_COUNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_WMS_TXNTRANFL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
PROD_TYPE,
PROD_NO,
TXN_DATE,
BRANCH_NBR,
TXN_ID,
TXN_TYPE,
CUR_ID,
MGN_ASSET_AMT,
MGN_ASSET_AMT_NEED,
SALES_ID,
INTRO_ID,
CUST_ID,
SALES_AUM_ORG,
SALES_AUM,
RATE,
QUERY_DT,
QUERY_YY,
QUERY_MM,
QUERY_DD,
SALES_AO_ORG,
BRANCH_NBR_ORG,
FR_FIRSTDT,
FR_ACC_DT,
TXN_DATE_ORG,
AO_TRANS_DATE,
ASSIGN_AO_BRANCH,
ASSIGN_AO_ID,
SALES_PCNT,
DIST_PCNT,
AO_GET,
INTRO_GET,
CATCH_PCNT,
CATCH_PCNT_SAO,
SAO_AUM,
DSAO_AUM,
INTRO_AUM,
SAO_AUM_18,
DSAO_AUM_18,
INVTYPE,
FEBN,
DISCNT,
IS_FIRST,
APL_DT,
INI_SALES_AUM,
POLICY_KIND,
IS_FROM_BATCH,
SALES_AUM_COEF,
SALES_PCNT_BRA,
DIST_PCNT_BRA,
SBRA_AUM,
DSBRA_AUM,
SAO_BREAK,
DSAO_BREAK,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
TXN_COUNT,
PROD_RISK,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
PROD_TYPE,
PROD_NO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXN_DATE), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXN_DATE))='0' THEN '0001-01-01' ELSE TXN_DATE END) AS TXN_DATE,
BRANCH_NBR,
TXN_ID,
TXN_TYPE,
CUR_ID,
MGN_ASSET_AMT,
MGN_ASSET_AMT_NEED,
SALES_ID,
INTRO_ID,
CUST_ID,
SALES_AUM_ORG,
SALES_AUM,
RATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(QUERY_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(QUERY_DT))='0' THEN NULL ELSE QUERY_DT END) AS QUERY_DT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(QUERY_YY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(QUERY_YY))='0' THEN NULL ELSE QUERY_YY END) AS QUERY_YY,
QUERY_MM,
QUERY_DD,
SALES_AO_ORG,
BRANCH_NBR_ORG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(FR_FIRSTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(FR_FIRSTDT))='0' THEN NULL ELSE FR_FIRSTDT END) AS FR_FIRSTDT,
FR_ACC_DT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXN_DATE_ORG), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXN_DATE_ORG))='0' THEN NULL ELSE TXN_DATE_ORG END) AS TXN_DATE_ORG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(AO_TRANS_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(AO_TRANS_DATE))='0' THEN NULL ELSE AO_TRANS_DATE END) AS AO_TRANS_DATE,
ASSIGN_AO_BRANCH,
ASSIGN_AO_ID,
SALES_PCNT,
DIST_PCNT,
AO_GET,
INTRO_GET,
CATCH_PCNT,
CATCH_PCNT_SAO,
SAO_AUM,
DSAO_AUM,
INTRO_AUM,
SAO_AUM_18,
DSAO_AUM_18,
INVTYPE,
FEBN,
DISCNT,
IS_FIRST,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APL_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APL_DT))='0' THEN NULL ELSE APL_DT END) AS APL_DT,
INI_SALES_AUM,
POLICY_KIND,
IS_FROM_BATCH,
SALES_AUM_COEF,
SALES_PCNT_BRA,
DIST_PCNT_BRA,
SBRA_AUM,
DSBRA_AUM,
SAO_BREAK,
DSAO_BREAK,
VERSION,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREATETIME), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREATETIME))='0' THEN '0001-01-01' ELSE CREATETIME END) AS CREATETIME,
CREATOR,
MODIFIER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTUPDATE), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTUPDATE))='0' THEN '0001-01-01' ELSE LASTUPDATE END) AS LASTUPDATE,
TXN_COUNT,
PROD_RISK,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
