-- SQL for table: EDW_CF_ACTCMP_HIS
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
CMPNAME,
ADDR,
ZIPNO1,
ZIPNO2,
TLRNO,
LUDATE,
HENTPNO,
CZONE,
CSRNO,
CEXT,
CPHONE,
NMFLG,
ADRFLG,
LUBRNO,
NMDATE,
EXTCNT,
CPHONECF,
CPHONEDT,
CPHONETM,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ACTNO,
CMPNAME,
ADDR,
ZIPNO1,
ZIPNO2,
TLRNO,
LUDATE,
HENTPNO,
CZONE,
CSRNO,
CEXT,
CPHONE,
NMFLG,
ADRFLG,
LUBRNO,
NMDATE,
EXTCNT,
CPHONECF,
CPHONEDT,
CPHONETM,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
