-- SQL for table: EDW_ELN_CRNEWCASE
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCRPTVER' AS DATA_CHK_COL,
ACCRPTVER AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCRPTVER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_ELN_CRNEWCASE
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CASEID,
IDBAN,
BRID,
CASE_DATE,
REASON,
STAFFID,
REVIEW3,
APPROVEDATE,
ITEM_TYPE,
INDUNO,
INITDATE,
ENDDATE,
CREVALUE,
CURUNIT,
IND_GAP,
IND_IFRS,
SWSINGLE,
SWSIMINC,
SWJOIN,
ACCRPTVER,
GRADEYEAR,
APPNAME,
CHGMANID,
CHGMANNA,
TEL_ZIP,
TEL,
TELEXT,
FACINDUNO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASEID,
IDBAN,
BRID,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CASE_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CASE_DATE))='0' THEN NULL ELSE CASE_DATE END) AS CASE_DATE,
REASON,
STAFFID,
REVIEW3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APPROVEDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APPROVEDATE))='0' THEN NULL ELSE APPROVEDATE END) AS APPROVEDATE,
ITEM_TYPE,
INDUNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(INITDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(INITDATE))='0' THEN NULL ELSE INITDATE END) AS INITDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ENDDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ENDDATE))='0' THEN NULL ELSE ENDDATE END) AS ENDDATE,
CREVALUE,
CURUNIT,
IND_GAP,
IND_IFRS,
SWSINGLE,
SWSIMINC,
SWJOIN,
ACCRPTVER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRADEYEAR), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRADEYEAR))='0' THEN NULL ELSE GRADEYEAR END) AS GRADEYEAR,
APPNAME,
CHGMANID,
CHGMANNA,
TEL_ZIP,
TEL,
TELEXT,
FACINDUNO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
