-- SQL for table: EDW_ELN_CRCUSTREL
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONAMT' AS DATA_CHK_COL,
CONAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CONAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BOTCONAMT' AS DATA_CHK_COL,
BOTCONAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BOTCONAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LOANAMT' AS DATA_CHK_COL,
LOANAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(LOANAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BOTLOANAMT' AS DATA_CHK_COL,
BOTLOANAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BOTLOANAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GRADEYEAR' AS DATA_CHK_COL,
GRADEYEAR AS DATA_VAL,
SDG.UFN_NUMCHECK(GRADEYEAR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BOTMARK' AS DATA_CHK_COL,
BOTMARK AS DATA_VAL,
SDG.UFN_NUMCHECK(BOTMARK) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SEQNO' AS DATA_CHK_COL,
SEQNO AS DATA_VAL,
SDG.UFN_NUMCHECK(SEQNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_ELN_CRCUSTREL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CASEID,
IDNO,
NAME,
REL,
SWREL,
CRRPTER,
CRRPTDATE,
CONAMT,
BOTCONAMT,
LOANAMT,
BOTLOANAMT,
GRADEYEAR,
BOTMARK,
BOTRANK,
JCICID,
SYSIDNO,
SWRSN,
IDBAN,
RELLOAN,
AUTHDATE,
AUTHCASEID,
GLOBALID,
C2CENTID,
BCODE2,
RELBOT,
SEQNO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CASEID,
IDNO,
NAME,
REL,
SWREL,
CRRPTER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CRRPTDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CRRPTDATE))='0' THEN NULL ELSE CRRPTDATE END) AS CRRPTDATE,
CONAMT,
BOTCONAMT,
LOANAMT,
BOTLOANAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRADEYEAR), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRADEYEAR))='0' THEN NULL ELSE GRADEYEAR END) AS GRADEYEAR,
BOTMARK,
BOTRANK,
JCICID,
SYSIDNO,
SWRSN,
IDBAN,
RELLOAN,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(AUTHDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(AUTHDATE))='0' THEN NULL ELSE AUTHDATE END) AS AUTHDATE,
AUTHCASEID,
GLOBALID,
C2CENTID,
BCODE2,
RELBOT,
SEQNO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
