-- SQL for table: EDW_FXF_FCIF
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO' AS DATA_CHK_COL,
CORPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BCODE' AS DATA_CHK_COL,
BCODE AS DATA_VAL,
SDG.UFN_NUMCHECK(BCODE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUTYPE' AS DATA_CHK_COL,
CUTYPE AS DATA_VAL,
SDG.UFN_NUMCHECK(CUTYPE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUDTL' AS DATA_CHK_COL,
CUDTL AS DATA_VAL,
SDG.UFN_NUMCHECK(CUDTL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BSCD' AS DATA_CHK_COL,
BSCD AS DATA_VAL,
SDG.UFN_NUMCHECK(BSCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CTYPE' AS DATA_CHK_COL,
CTYPE AS DATA_VAL,
SDG.UFN_NUMCHECK(CTYPE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUSTCD' AS DATA_CHK_COL,
CUSTCD AS DATA_VAL,
SDG.UFN_NUMCHECK(CUSTCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MBRNO' AS DATA_CHK_COL,
MBRNO AS DATA_VAL,
SDG.UFN_NUMCHECK(MBRNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IBRNO' AS DATA_CHK_COL,
IBRNO AS DATA_VAL,
SDG.UFN_NUMCHECK(IBRNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MGP' AS DATA_CHK_COL,
MGP AS DATA_VAL,
SDG.UFN_NUMCHECK(MGP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ADVCD' AS DATA_CHK_COL,
ADVCD AS DATA_VAL,
SDG.UFN_NUMCHECK(ADVCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'KINBR' AS DATA_CHK_COL,
KINBR AS DATA_VAL,
SDG.UFN_NUMCHECK(KINBR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ZIP' AS DATA_CHK_COL,
ZIP AS DATA_VAL,
SDG.UFN_NUMCHECK(ZIP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SCOP' AS DATA_CHK_COL,
SCOP AS DATA_VAL,
SDG.UFN_NUMCHECK(SCOP) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SENDFG' AS DATA_CHK_COL,
SENDFG AS DATA_VAL,
SDG.UFN_NUMCHECK(SENDFG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EBFG' AS DATA_CHK_COL,
EBFG AS DATA_VAL,
SDG.UFN_NUMCHECK(EBFG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VACTCD' AS DATA_CHK_COL,
VACTCD AS DATA_VAL,
SDG.UFN_NUMCHECK(VACTCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RATINGORG' AS DATA_CHK_COL,
RATINGORG AS DATA_VAL,
SDG.UFN_NUMCHECK(RATINGORG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXF_FCIF
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CIFKEY,
CORPNO,
ENAME1,
ENAME2,
ENAME3,
EADDR1,
EADDR2,
EADDR3,
EADDR4,
EADDR5,
BCODE,
QID,
CUTYPE,
CUDTL,
BSCD,
PIDNO,
PNAME,
BNAME,
BIRDT,
ISUDT,
EXPDT,
CTYPE,
AREANO,
TELNO,
EXTNO,
FAXAREA,
FAXNO,
EMAIL,
CONAL,
RGNAL,
DERNAL,
CUSTCD,
MBRNO,
IBRNO,
MGP,
ADVCD,
KINBR,
TLRNO,
ZIP,
SCOP,
SENDFG,
CADDR,
CADDR2,
CADDR3,
CADDR4,
CADDR5,
EBFG,
VACTCD,
RATINGORG,
RATING,
OBUCIFKEY,
GTCUTYP,
CREDATE,
OBUCRE,
ICIFKEY,
BKIND2,
LEI,
ROMANAME,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CIFKEY,
CORPNO,
ENAME1,
ENAME2,
ENAME3,
EADDR1,
EADDR2,
EADDR3,
EADDR4,
EADDR5,
BCODE,
QID,
CUTYPE,
CUDTL,
BSCD,
PIDNO,
PNAME,
BNAME,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BIRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BIRDT))='0' THEN NULL ELSE BIRDT END) AS BIRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISUDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISUDT))='0' THEN NULL ELSE ISUDT END) AS ISUDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EXPDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EXPDT))='0' THEN NULL ELSE EXPDT END) AS EXPDT,
CTYPE,
AREANO,
TELNO,
EXTNO,
FAXAREA,
FAXNO,
EMAIL,
CONAL,
RGNAL,
DERNAL,
CUSTCD,
MBRNO,
IBRNO,
MGP,
ADVCD,
KINBR,
TLRNO,
ZIP,
SCOP,
SENDFG,
CADDR,
CADDR2,
CADDR3,
CADDR4,
CADDR5,
EBFG,
VACTCD,
RATINGORG,
RATING,
OBUCIFKEY,
GTCUTYP,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREDATE))='0' THEN NULL ELSE CREDATE END) AS CREDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OBUCRE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OBUCRE))='0' THEN NULL ELSE OBUCRE END) AS OBUCRE,
ICIFKEY,
BKIND2,
LEI,
ROMANAME,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
