-- SQL for table: EDW_DP_PIDCTL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
RGDAY,
RGTIME,
KINBR,
TRMSEQ,
TLRNO,
ACTFLG,
UPDDAY,
UPDTIME,
PIDNO,
NAME,
UNIT,
RGDATE,
RGCHAR,
RGNO,
NO1,
NO2,
TEXT,
CASENO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RGDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RGDAY))='0' THEN NULL ELSE RGDAY END) AS RGDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RGDAY)||' '||TRIM(RGTIME), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RGDAY)||' '||TRIM(RGTIME))='0' THEN NULL ELSE TRIM(RGDAY)||' '||TRIM(RGTIME) END) AS RGTIME,
KINBR,
TRMSEQ,
TLRNO,
ACTFLG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(UPDDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(UPDDAY))='0' THEN NULL ELSE UPDDAY END) AS UPDDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(UPDDAY)||' '||TRIM(UPDTIME), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(UPDDAY)||' '||TRIM(UPDTIME))='0' THEN NULL ELSE TRIM(UPDDAY)||' '||TRIM(UPDTIME) END) AS UPDTIME,
PIDNO,
NAME,
UNIT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RGDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RGDATE))='0' THEN NULL ELSE RGDATE END) AS RGDATE,
RGCHAR,
RGNO,
NO1,
NO2,
TEXT,
CASENO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
