-- SQL for table: EDW_LNW_LWMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APAMT' AS DATA_CHK_COL,
APAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(APAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SQBAL' AS DATA_CHK_COL,
SQBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(SQBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CURBAL' AS DATA_CHK_COL,
CURBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(CURBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MGCASH' AS DATA_CHK_COL,
MGCASH AS DATA_VAL,
SDG.UFN_NUMCHECK(MGCASH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MGBAL' AS DATA_CHK_COL,
MGBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(MGBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CXDAY' AS DATA_CHK_COL,
CXDAY AS DATA_VAL,
SDG.UFN_NUMCHECK(CXDAY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BKCNT' AS DATA_CHK_COL,
BKCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(BKCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UBKCNT' AS DATA_CHK_COL,
UBKCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(UBKCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PDTAMT' AS DATA_CHK_COL,
PDTAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PDTAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BONCNT' AS DATA_CHK_COL,
BONCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(BONCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TENOR' AS DATA_CHK_COL,
TENOR AS DATA_VAL,
SDG.UFN_NUMCHECK(TENOR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACPCNT' AS DATA_CHK_COL,
ACPCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(ACPCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RICAMT' AS DATA_CHK_COL,
RICAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RICAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'XRATEC' AS DATA_CHK_COL,
XRATEC AS DATA_VAL,
SDG.UFN_NUMCHECK(XRATEC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IPBAL' AS DATA_CHK_COL,
IPBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(IPBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ULNLMT' AS DATA_CHK_COL,
ULNLMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ULNLMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHARGE' AS DATA_CHK_COL,
CHARGE AS DATA_VAL,
SDG.UFN_NUMCHECK(CHARGE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GAID' AS DATA_CHK_COL,
GAID AS DATA_VAL,
SDG.UFN_NUMCHECK(GAID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AMOUNT' AS DATA_CHK_COL,
AMOUNT AS DATA_VAL,
SDG.UFN_NUMCHECK(AMOUNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CURAMT' AS DATA_CHK_COL,
CURAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CURAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IDATE' AS DATA_CHK_COL,
IDATE AS DATA_VAL,
SDG.UFN_NUMCHECK(IDATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGRT' AS DATA_CHK_COL,
CHGRT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSKAMT' AS DATA_CHK_COL,
RSKAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RSKAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSKBAL' AS DATA_CHK_COL,
RSKBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(RSKBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FXRATEC' AS DATA_CHK_COL,
FXRATEC AS DATA_VAL,
SDG.UFN_NUMCHECK(FXRATEC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GALEVEL' AS DATA_CHK_COL,
GALEVEL AS DATA_VAL,
SDG.UFN_NUMCHECK(GALEVEL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_LNW_LWMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
SQNO,
CURCD,
LGNO,
APAMT,
GACD,
APKIND,
SAPNO,
ISUDT,
EDAY,
APDATE,
LASTDT,
SQBAL,
CURBAL,
NUMEDT,
OIDATE,
MGCASH,
MGBAL,
MGCUR,
MGTYP,
CXDAY,
BKCNT,
UBKCNT,
PDTAMT,
BONCNT,
DGEDT,
ADCBK,
PBRNO,
TENOR,
ACPCNT,
DELCD,
ACTCLS,
RICAMT,
XRATEC,
LCTYP,
ISTCD,
IPBAL,
ULNLMT,
CHARGE,
GAID,
GDOCNO,
BNFINL,
INVTNO,
CONTNO,
BKNAM,
APNUM,
VLDATE,
APCUR,
AMOUNT,
CURAMT,
IDATE,
CHARCD,
TRUHD,
CHGRT,
SQICD,
CHGCD,
OPRDT,
PRDATE,
FXFLG,
RSKAMT,
RSKBAL,
RSKNAL,
FXRATEC,
NTXDAY,
GALEVEL,
FLOW,
REFNO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
SQNO,
CURCD,
LGNO,
APAMT,
GACD,
APKIND,
SAPNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISUDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISUDT))='0' THEN NULL ELSE ISUDT END) AS ISUDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY))='0' THEN NULL ELSE EDAY END) AS EDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APDATE))='0' THEN NULL ELSE APDATE END) AS APDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
SQBAL,
CURBAL,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NUMEDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NUMEDT))='0' THEN NULL ELSE NUMEDT END) AS NUMEDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OIDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OIDATE))='0' THEN NULL ELSE OIDATE END) AS OIDATE,
MGCASH,
MGBAL,
MGCUR,
MGTYP,
CXDAY,
BKCNT,
UBKCNT,
PDTAMT,
BONCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DGEDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DGEDT))='0' THEN NULL ELSE DGEDT END) AS DGEDT,
ADCBK,
PBRNO,
TENOR,
ACPCNT,
DELCD,
ACTCLS,
RICAMT,
XRATEC,
LCTYP,
ISTCD,
IPBAL,
ULNLMT,
CHARGE,
GAID,
GDOCNO,
BNFINL,
INVTNO,
CONTNO,
BKNAM,
APNUM,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(VLDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(VLDATE))='0' THEN NULL ELSE VLDATE END) AS VLDATE,
APCUR,
AMOUNT,
CURAMT,
IDATE,
CHARCD,
TRUHD,
CHGRT,
SQICD,
CHGCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPRDT))='0' THEN NULL ELSE OPRDT END) AS OPRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRDATE))='0' THEN NULL ELSE PRDATE END) AS PRDATE,
FXFLG,
RSKAMT,
RSKBAL,
RSKNAL,
FXRATEC,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
GALEVEL,
FLOW,
REFNO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
