-- SQL for table: EDW_FXB_FRCEN
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXAMT' AS DATA_CHK_COL,
TXAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(TXAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CKCNT' AS DATA_CHK_COL,
CKCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CKCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXIDX' AS DATA_CHK_COL,
TXIDX AS DATA_VAL,
SDG.UFN_NUMCHECK(TXIDX) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_01' AS DATA_CHK_COL,
CORPNO_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_01' AS DATA_CHK_COL,
CBAMT_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_01' AS DATA_CHK_COL,
USELN_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_01' AS DATA_CHK_COL,
TXTNO_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_01' AS DATA_CHK_COL,
EXAMT_01 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_01) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_02' AS DATA_CHK_COL,
CORPNO_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_02' AS DATA_CHK_COL,
CBAMT_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_02' AS DATA_CHK_COL,
USELN_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_02' AS DATA_CHK_COL,
TXTNO_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_02' AS DATA_CHK_COL,
EXAMT_02 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_02) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_03' AS DATA_CHK_COL,
CORPNO_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_03' AS DATA_CHK_COL,
CBAMT_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_03' AS DATA_CHK_COL,
USELN_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_03' AS DATA_CHK_COL,
TXTNO_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_03' AS DATA_CHK_COL,
EXAMT_03 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_03) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_04' AS DATA_CHK_COL,
CORPNO_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_04' AS DATA_CHK_COL,
CBAMT_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_04' AS DATA_CHK_COL,
USELN_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_04' AS DATA_CHK_COL,
TXTNO_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_04' AS DATA_CHK_COL,
EXAMT_04 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_04) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_05' AS DATA_CHK_COL,
CORPNO_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_05' AS DATA_CHK_COL,
CBAMT_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_05' AS DATA_CHK_COL,
USELN_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_05' AS DATA_CHK_COL,
TXTNO_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_05' AS DATA_CHK_COL,
EXAMT_05 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_05) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_06' AS DATA_CHK_COL,
CORPNO_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_06' AS DATA_CHK_COL,
CBAMT_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_06' AS DATA_CHK_COL,
USELN_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_06' AS DATA_CHK_COL,
TXTNO_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_06' AS DATA_CHK_COL,
EXAMT_06 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_06) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_07' AS DATA_CHK_COL,
CORPNO_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_07' AS DATA_CHK_COL,
CBAMT_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_07' AS DATA_CHK_COL,
USELN_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_07' AS DATA_CHK_COL,
TXTNO_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_07' AS DATA_CHK_COL,
EXAMT_07 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_07) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_08' AS DATA_CHK_COL,
CORPNO_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_08' AS DATA_CHK_COL,
CBAMT_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_08' AS DATA_CHK_COL,
USELN_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_08' AS DATA_CHK_COL,
TXTNO_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_08' AS DATA_CHK_COL,
EXAMT_08 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_08) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_09' AS DATA_CHK_COL,
CORPNO_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_09' AS DATA_CHK_COL,
CBAMT_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_09' AS DATA_CHK_COL,
USELN_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_09' AS DATA_CHK_COL,
TXTNO_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_09' AS DATA_CHK_COL,
EXAMT_09 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_09) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_10' AS DATA_CHK_COL,
CORPNO_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_10' AS DATA_CHK_COL,
CBAMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_10' AS DATA_CHK_COL,
USELN_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_10' AS DATA_CHK_COL,
TXTNO_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_10' AS DATA_CHK_COL,
EXAMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_11' AS DATA_CHK_COL,
CORPNO_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_11' AS DATA_CHK_COL,
CBAMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_11' AS DATA_CHK_COL,
USELN_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_11' AS DATA_CHK_COL,
TXTNO_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_11' AS DATA_CHK_COL,
EXAMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_12' AS DATA_CHK_COL,
CORPNO_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_12' AS DATA_CHK_COL,
CBAMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_12' AS DATA_CHK_COL,
USELN_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_12' AS DATA_CHK_COL,
TXTNO_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_12' AS DATA_CHK_COL,
EXAMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_13' AS DATA_CHK_COL,
CORPNO_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_13' AS DATA_CHK_COL,
CBAMT_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_13' AS DATA_CHK_COL,
USELN_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_13' AS DATA_CHK_COL,
TXTNO_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_13' AS DATA_CHK_COL,
EXAMT_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_14' AS DATA_CHK_COL,
CORPNO_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_14' AS DATA_CHK_COL,
CBAMT_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_14' AS DATA_CHK_COL,
USELN_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_14' AS DATA_CHK_COL,
TXTNO_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_14' AS DATA_CHK_COL,
EXAMT_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_15' AS DATA_CHK_COL,
CORPNO_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_15' AS DATA_CHK_COL,
CBAMT_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_15' AS DATA_CHK_COL,
USELN_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_15' AS DATA_CHK_COL,
TXTNO_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_15' AS DATA_CHK_COL,
EXAMT_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_16' AS DATA_CHK_COL,
CORPNO_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_16' AS DATA_CHK_COL,
CBAMT_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_16' AS DATA_CHK_COL,
USELN_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_16' AS DATA_CHK_COL,
TXTNO_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_16' AS DATA_CHK_COL,
EXAMT_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_17' AS DATA_CHK_COL,
CORPNO_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_17' AS DATA_CHK_COL,
CBAMT_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_17' AS DATA_CHK_COL,
USELN_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_17' AS DATA_CHK_COL,
TXTNO_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_17' AS DATA_CHK_COL,
EXAMT_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_18' AS DATA_CHK_COL,
CORPNO_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_18' AS DATA_CHK_COL,
CBAMT_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_18' AS DATA_CHK_COL,
USELN_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_18' AS DATA_CHK_COL,
TXTNO_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_18' AS DATA_CHK_COL,
EXAMT_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_19' AS DATA_CHK_COL,
CORPNO_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_19' AS DATA_CHK_COL,
CBAMT_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_19' AS DATA_CHK_COL,
USELN_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_19' AS DATA_CHK_COL,
TXTNO_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_19' AS DATA_CHK_COL,
EXAMT_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_20' AS DATA_CHK_COL,
CORPNO_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_20' AS DATA_CHK_COL,
CBAMT_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_20' AS DATA_CHK_COL,
USELN_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_20' AS DATA_CHK_COL,
TXTNO_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_20' AS DATA_CHK_COL,
EXAMT_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_21' AS DATA_CHK_COL,
CORPNO_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_21' AS DATA_CHK_COL,
CBAMT_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_21' AS DATA_CHK_COL,
USELN_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_21' AS DATA_CHK_COL,
TXTNO_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_21' AS DATA_CHK_COL,
EXAMT_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_22' AS DATA_CHK_COL,
CORPNO_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_22' AS DATA_CHK_COL,
CBAMT_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_22' AS DATA_CHK_COL,
USELN_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_22' AS DATA_CHK_COL,
TXTNO_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_22' AS DATA_CHK_COL,
EXAMT_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_23' AS DATA_CHK_COL,
CORPNO_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_23' AS DATA_CHK_COL,
CBAMT_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_23' AS DATA_CHK_COL,
USELN_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_23' AS DATA_CHK_COL,
TXTNO_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_23' AS DATA_CHK_COL,
EXAMT_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_24' AS DATA_CHK_COL,
CORPNO_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_24' AS DATA_CHK_COL,
CBAMT_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_24' AS DATA_CHK_COL,
USELN_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_24' AS DATA_CHK_COL,
TXTNO_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_24' AS DATA_CHK_COL,
EXAMT_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_25' AS DATA_CHK_COL,
CORPNO_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_25' AS DATA_CHK_COL,
CBAMT_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_25' AS DATA_CHK_COL,
USELN_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_25' AS DATA_CHK_COL,
TXTNO_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_25' AS DATA_CHK_COL,
EXAMT_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_26' AS DATA_CHK_COL,
CORPNO_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_26' AS DATA_CHK_COL,
CBAMT_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_26' AS DATA_CHK_COL,
USELN_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_26' AS DATA_CHK_COL,
TXTNO_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_26' AS DATA_CHK_COL,
EXAMT_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_27' AS DATA_CHK_COL,
CORPNO_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_27' AS DATA_CHK_COL,
CBAMT_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_27' AS DATA_CHK_COL,
USELN_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_27' AS DATA_CHK_COL,
TXTNO_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_27' AS DATA_CHK_COL,
EXAMT_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_28' AS DATA_CHK_COL,
CORPNO_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_28' AS DATA_CHK_COL,
CBAMT_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_28' AS DATA_CHK_COL,
USELN_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_28' AS DATA_CHK_COL,
TXTNO_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_28' AS DATA_CHK_COL,
EXAMT_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_29' AS DATA_CHK_COL,
CORPNO_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_29' AS DATA_CHK_COL,
CBAMT_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_29' AS DATA_CHK_COL,
USELN_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_29' AS DATA_CHK_COL,
TXTNO_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_29' AS DATA_CHK_COL,
EXAMT_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO_30' AS DATA_CHK_COL,
CORPNO_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBAMT_30' AS DATA_CHK_COL,
CBAMT_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(CBAMT_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USELN_30' AS DATA_CHK_COL,
USELN_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(USELN_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO_30' AS DATA_CHK_COL,
TXTNO_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXAMT_30' AS DATA_CHK_COL,
EXAMT_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(EXAMT_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXPAMT' AS DATA_CHK_COL,
EXPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(EXPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXB_FRCEN
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
KINBR,
BKCUR1,
BKSRNO1,
CURCD,
TXAMT,
TXDAT,
CKCNT,
COVER,
TXIDX,
CIFKEY_01,
CORPNO_01,
CBAMT_01,
USELN_01,
WSNO_01,
TXTNO_01,
USECD_01,
CUSTOM_01,
CN_01,
EXAMT_01,
CKKIND_01,
CIFKEY_02,
CORPNO_02,
CBAMT_02,
USELN_02,
WSNO_02,
TXTNO_02,
USECD_02,
CUSTOM_02,
CN_02,
EXAMT_02,
CKKIND_02,
CIFKEY_03,
CORPNO_03,
CBAMT_03,
USELN_03,
WSNO_03,
TXTNO_03,
USECD_03,
CUSTOM_03,
CN_03,
EXAMT_03,
CKKIND_03,
CIFKEY_04,
CORPNO_04,
CBAMT_04,
USELN_04,
WSNO_04,
TXTNO_04,
USECD_04,
CUSTOM_04,
CN_04,
EXAMT_04,
CKKIND_04,
CIFKEY_05,
CORPNO_05,
CBAMT_05,
USELN_05,
WSNO_05,
TXTNO_05,
USECD_05,
CUSTOM_05,
CN_05,
EXAMT_05,
CKKIND_05,
CIFKEY_06,
CORPNO_06,
CBAMT_06,
USELN_06,
WSNO_06,
TXTNO_06,
USECD_06,
CUSTOM_06,
CN_06,
EXAMT_06,
CKKIND_06,
CIFKEY_07,
CORPNO_07,
CBAMT_07,
USELN_07,
WSNO_07,
TXTNO_07,
USECD_07,
CUSTOM_07,
CN_07,
EXAMT_07,
CKKIND_07,
CIFKEY_08,
CORPNO_08,
CBAMT_08,
USELN_08,
WSNO_08,
TXTNO_08,
USECD_08,
CUSTOM_08,
CN_08,
EXAMT_08,
CKKIND_08,
CIFKEY_09,
CORPNO_09,
CBAMT_09,
USELN_09,
WSNO_09,
TXTNO_09,
USECD_09,
CUSTOM_09,
CN_09,
EXAMT_09,
CKKIND_09,
CIFKEY_10,
CORPNO_10,
CBAMT_10,
USELN_10,
WSNO_10,
TXTNO_10,
USECD_10,
CUSTOM_10,
CN_10,
EXAMT_10,
CKKIND_10,
CIFKEY_11,
CORPNO_11,
CBAMT_11,
USELN_11,
WSNO_11,
TXTNO_11,
USECD_11,
CUSTOM_11,
CN_11,
EXAMT_11,
CKKIND_11,
CIFKEY_12,
CORPNO_12,
CBAMT_12,
USELN_12,
WSNO_12,
TXTNO_12,
USECD_12,
CUSTOM_12,
CN_12,
EXAMT_12,
CKKIND_12,
CIFKEY_13,
CORPNO_13,
CBAMT_13,
USELN_13,
WSNO_13,
TXTNO_13,
USECD_13,
CUSTOM_13,
CN_13,
EXAMT_13,
CKKIND_13,
CIFKEY_14,
CORPNO_14,
CBAMT_14,
USELN_14,
WSNO_14,
TXTNO_14,
USECD_14,
CUSTOM_14,
CN_14,
EXAMT_14,
CKKIND_14,
CIFKEY_15,
CORPNO_15,
CBAMT_15,
USELN_15,
WSNO_15,
TXTNO_15,
USECD_15,
CUSTOM_15,
CN_15,
EXAMT_15,
CKKIND_15,
CIFKEY_16,
CORPNO_16,
CBAMT_16,
USELN_16,
WSNO_16,
TXTNO_16,
USECD_16,
CUSTOM_16,
CN_16,
EXAMT_16,
CKKIND_16,
CIFKEY_17,
CORPNO_17,
CBAMT_17,
USELN_17,
WSNO_17,
TXTNO_17,
USECD_17,
CUSTOM_17,
CN_17,
EXAMT_17,
CKKIND_17,
CIFKEY_18,
CORPNO_18,
CBAMT_18,
USELN_18,
WSNO_18,
TXTNO_18,
USECD_18,
CUSTOM_18,
CN_18,
EXAMT_18,
CKKIND_18,
CIFKEY_19,
CORPNO_19,
CBAMT_19,
USELN_19,
WSNO_19,
TXTNO_19,
USECD_19,
CUSTOM_19,
CN_19,
EXAMT_19,
CKKIND_19,
CIFKEY_20,
CORPNO_20,
CBAMT_20,
USELN_20,
WSNO_20,
TXTNO_20,
USECD_20,
CUSTOM_20,
CN_20,
EXAMT_20,
CKKIND_20,
CIFKEY_21,
CORPNO_21,
CBAMT_21,
USELN_21,
WSNO_21,
TXTNO_21,
USECD_21,
CUSTOM_21,
CN_21,
EXAMT_21,
CKKIND_21,
CIFKEY_22,
CORPNO_22,
CBAMT_22,
USELN_22,
WSNO_22,
TXTNO_22,
USECD_22,
CUSTOM_22,
CN_22,
EXAMT_22,
CKKIND_22,
CIFKEY_23,
CORPNO_23,
CBAMT_23,
USELN_23,
WSNO_23,
TXTNO_23,
USECD_23,
CUSTOM_23,
CN_23,
EXAMT_23,
CKKIND_23,
CIFKEY_24,
CORPNO_24,
CBAMT_24,
USELN_24,
WSNO_24,
TXTNO_24,
USECD_24,
CUSTOM_24,
CN_24,
EXAMT_24,
CKKIND_24,
CIFKEY_25,
CORPNO_25,
CBAMT_25,
USELN_25,
WSNO_25,
TXTNO_25,
USECD_25,
CUSTOM_25,
CN_25,
EXAMT_25,
CKKIND_25,
CIFKEY_26,
CORPNO_26,
CBAMT_26,
USELN_26,
WSNO_26,
TXTNO_26,
USECD_26,
CUSTOM_26,
CN_26,
EXAMT_26,
CKKIND_26,
CIFKEY_27,
CORPNO_27,
CBAMT_27,
USELN_27,
WSNO_27,
TXTNO_27,
USECD_27,
CUSTOM_27,
CN_27,
EXAMT_27,
CKKIND_27,
CIFKEY_28,
CORPNO_28,
CBAMT_28,
USELN_28,
WSNO_28,
TXTNO_28,
USECD_28,
CUSTOM_28,
CN_28,
EXAMT_28,
CKKIND_28,
CIFKEY_29,
CORPNO_29,
CBAMT_29,
USELN_29,
WSNO_29,
TXTNO_29,
USECD_29,
CUSTOM_29,
CN_29,
EXAMT_29,
CKKIND_29,
CIFKEY_30,
CORPNO_30,
CBAMT_30,
USELN_30,
WSNO_30,
TXTNO_30,
USECD_30,
CUSTOM_30,
CN_30,
EXAMT_30,
CKKIND_30,
EXPAMT,
USDAREA,
RCKIND,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
KINBR,
BKCUR1,
BKSRNO1,
CURCD,
TXAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXDAT))='0' THEN NULL ELSE TXDAT END) AS TXDAT,
CKCNT,
COVER,
TXIDX,
CIFKEY_01,
CORPNO_01,
CBAMT_01,
USELN_01,
WSNO_01,
TXTNO_01,
USECD_01,
CUSTOM_01,
CN_01,
EXAMT_01,
CKKIND_01,
CIFKEY_02,
CORPNO_02,
CBAMT_02,
USELN_02,
WSNO_02,
TXTNO_02,
USECD_02,
CUSTOM_02,
CN_02,
EXAMT_02,
CKKIND_02,
CIFKEY_03,
CORPNO_03,
CBAMT_03,
USELN_03,
WSNO_03,
TXTNO_03,
USECD_03,
CUSTOM_03,
CN_03,
EXAMT_03,
CKKIND_03,
CIFKEY_04,
CORPNO_04,
CBAMT_04,
USELN_04,
WSNO_04,
TXTNO_04,
USECD_04,
CUSTOM_04,
CN_04,
EXAMT_04,
CKKIND_04,
CIFKEY_05,
CORPNO_05,
CBAMT_05,
USELN_05,
WSNO_05,
TXTNO_05,
USECD_05,
CUSTOM_05,
CN_05,
EXAMT_05,
CKKIND_05,
CIFKEY_06,
CORPNO_06,
CBAMT_06,
USELN_06,
WSNO_06,
TXTNO_06,
USECD_06,
CUSTOM_06,
CN_06,
EXAMT_06,
CKKIND_06,
CIFKEY_07,
CORPNO_07,
CBAMT_07,
USELN_07,
WSNO_07,
TXTNO_07,
USECD_07,
CUSTOM_07,
CN_07,
EXAMT_07,
CKKIND_07,
CIFKEY_08,
CORPNO_08,
CBAMT_08,
USELN_08,
WSNO_08,
TXTNO_08,
USECD_08,
CUSTOM_08,
CN_08,
EXAMT_08,
CKKIND_08,
CIFKEY_09,
CORPNO_09,
CBAMT_09,
USELN_09,
WSNO_09,
TXTNO_09,
USECD_09,
CUSTOM_09,
CN_09,
EXAMT_09,
CKKIND_09,
CIFKEY_10,
CORPNO_10,
CBAMT_10,
USELN_10,
WSNO_10,
TXTNO_10,
USECD_10,
CUSTOM_10,
CN_10,
EXAMT_10,
CKKIND_10,
CIFKEY_11,
CORPNO_11,
CBAMT_11,
USELN_11,
WSNO_11,
TXTNO_11,
USECD_11,
CUSTOM_11,
CN_11,
EXAMT_11,
CKKIND_11,
CIFKEY_12,
CORPNO_12,
CBAMT_12,
USELN_12,
WSNO_12,
TXTNO_12,
USECD_12,
CUSTOM_12,
CN_12,
EXAMT_12,
CKKIND_12,
CIFKEY_13,
CORPNO_13,
CBAMT_13,
USELN_13,
WSNO_13,
TXTNO_13,
USECD_13,
CUSTOM_13,
CN_13,
EXAMT_13,
CKKIND_13,
CIFKEY_14,
CORPNO_14,
CBAMT_14,
USELN_14,
WSNO_14,
TXTNO_14,
USECD_14,
CUSTOM_14,
CN_14,
EXAMT_14,
CKKIND_14,
CIFKEY_15,
CORPNO_15,
CBAMT_15,
USELN_15,
WSNO_15,
TXTNO_15,
USECD_15,
CUSTOM_15,
CN_15,
EXAMT_15,
CKKIND_15,
CIFKEY_16,
CORPNO_16,
CBAMT_16,
USELN_16,
WSNO_16,
TXTNO_16,
USECD_16,
CUSTOM_16,
CN_16,
EXAMT_16,
CKKIND_16,
CIFKEY_17,
CORPNO_17,
CBAMT_17,
USELN_17,
WSNO_17,
TXTNO_17,
USECD_17,
CUSTOM_17,
CN_17,
EXAMT_17,
CKKIND_17,
CIFKEY_18,
CORPNO_18,
CBAMT_18,
USELN_18,
WSNO_18,
TXTNO_18,
USECD_18,
CUSTOM_18,
CN_18,
EXAMT_18,
CKKIND_18,
CIFKEY_19,
CORPNO_19,
CBAMT_19,
USELN_19,
WSNO_19,
TXTNO_19,
USECD_19,
CUSTOM_19,
CN_19,
EXAMT_19,
CKKIND_19,
CIFKEY_20,
CORPNO_20,
CBAMT_20,
USELN_20,
WSNO_20,
TXTNO_20,
USECD_20,
CUSTOM_20,
CN_20,
EXAMT_20,
CKKIND_20,
CIFKEY_21,
CORPNO_21,
CBAMT_21,
USELN_21,
WSNO_21,
TXTNO_21,
USECD_21,
CUSTOM_21,
CN_21,
EXAMT_21,
CKKIND_21,
CIFKEY_22,
CORPNO_22,
CBAMT_22,
USELN_22,
WSNO_22,
TXTNO_22,
USECD_22,
CUSTOM_22,
CN_22,
EXAMT_22,
CKKIND_22,
CIFKEY_23,
CORPNO_23,
CBAMT_23,
USELN_23,
WSNO_23,
TXTNO_23,
USECD_23,
CUSTOM_23,
CN_23,
EXAMT_23,
CKKIND_23,
CIFKEY_24,
CORPNO_24,
CBAMT_24,
USELN_24,
WSNO_24,
TXTNO_24,
USECD_24,
CUSTOM_24,
CN_24,
EXAMT_24,
CKKIND_24,
CIFKEY_25,
CORPNO_25,
CBAMT_25,
USELN_25,
WSNO_25,
TXTNO_25,
USECD_25,
CUSTOM_25,
CN_25,
EXAMT_25,
CKKIND_25,
CIFKEY_26,
CORPNO_26,
CBAMT_26,
USELN_26,
WSNO_26,
TXTNO_26,
USECD_26,
CUSTOM_26,
CN_26,
EXAMT_26,
CKKIND_26,
CIFKEY_27,
CORPNO_27,
CBAMT_27,
USELN_27,
WSNO_27,
TXTNO_27,
USECD_27,
CUSTOM_27,
CN_27,
EXAMT_27,
CKKIND_27,
CIFKEY_28,
CORPNO_28,
CBAMT_28,
USELN_28,
WSNO_28,
TXTNO_28,
USECD_28,
CUSTOM_28,
CN_28,
EXAMT_28,
CKKIND_28,
CIFKEY_29,
CORPNO_29,
CBAMT_29,
USELN_29,
WSNO_29,
TXTNO_29,
USECD_29,
CUSTOM_29,
CN_29,
EXAMT_29,
CKKIND_29,
CIFKEY_30,
CORPNO_30,
CBAMT_30,
USELN_30,
WSNO_30,
TXTNO_30,
USECD_30,
CUSTOM_30,
CN_30,
EXAMT_30,
CKKIND_30,
EXPAMT,
USDAREA,
RCKIND,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
