-- SQL for table: EDW_IC_CARD
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SEQ' AS DATA_CHK_COL,
SEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(SEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APPSEQ' AS DATA_CHK_COL,
APPSEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(APPSEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COMBOSEQ' AS DATA_CHK_COL,
COMBOSEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(COMBOSEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRCNO' AS DATA_CHK_COL,
PRCNO AS DATA_VAL,
SDG.UFN_NUMCHECK(PRCNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_IC_CARD
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
SEQ,
CDKIND,
BIRTHDY,
PIDNO,
ICAP01,
ICAP02,
ICAP03,
ICAP04,
ICAP05,
ICAP06,
ICAP07,
ICAP08,
ICAP09,
ICAP10,
ICAP11,
ICAP12,
ICAP13,
ICAP14,
ICAP15,
ICAP16,
ICAP17,
ICAP18,
ICAP19,
ICAP20,
APEXDT01,
APEXDT02,
APEXDT03,
APEXDT04,
APEXDT05,
APEXDT06,
APEXDT07,
APEXDT08,
APEXDT09,
APEXDT10,
APEXDT11,
APEXDT12,
APEXDT13,
APEXDT14,
APEXDT15,
APEXDT16,
APEXDT17,
APEXDT18,
APEXDT19,
APEXDT20,
CDSTUS,
STUSDT,
STUSTM,
WSNO,
TLRNO,
HOTTYPE,
UNLKFG,
PREFG,
APPSEQ,
LANGUAGE,
USEDT,
KINBR,
APPTLRNO,
FEECD,
APPDT,
DIVTYPE,
EMPCARD,
EMPNO,
ITEM1,
ITEM2,
ITEM3,
ITEM4,
ITEM5,
ITEM6,
DESCHIP,
CREDIT,
BRNO,
"NEW",
CIRRUS,
DUEDT,
RCVDT,
COMBOSEQ,
PRCSB,
PRCNO,
MADFG,
MADAY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ACTNO,
SEQ,
CDKIND,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BIRTHDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BIRTHDY))='0' THEN NULL ELSE BIRTHDY END) AS BIRTHDY,
PIDNO,
ICAP01,
ICAP02,
ICAP03,
ICAP04,
ICAP05,
ICAP06,
ICAP07,
ICAP08,
ICAP09,
ICAP10,
ICAP11,
ICAP12,
ICAP13,
ICAP14,
ICAP15,
ICAP16,
ICAP17,
ICAP18,
ICAP19,
ICAP20,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT01), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT01))='0' THEN NULL ELSE APEXDT01 END) AS APEXDT01,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT02), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT02))='0' THEN NULL ELSE APEXDT02 END) AS APEXDT02,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT03), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT03))='0' THEN NULL ELSE APEXDT03 END) AS APEXDT03,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT04), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT04))='0' THEN NULL ELSE APEXDT04 END) AS APEXDT04,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT05), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT05))='0' THEN NULL ELSE APEXDT05 END) AS APEXDT05,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT06), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT06))='0' THEN NULL ELSE APEXDT06 END) AS APEXDT06,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT07), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT07))='0' THEN NULL ELSE APEXDT07 END) AS APEXDT07,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT08), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT08))='0' THEN NULL ELSE APEXDT08 END) AS APEXDT08,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT09), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT09))='0' THEN NULL ELSE APEXDT09 END) AS APEXDT09,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT10), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT10))='0' THEN NULL ELSE APEXDT10 END) AS APEXDT10,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT11), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT11))='0' THEN NULL ELSE APEXDT11 END) AS APEXDT11,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT12), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT12))='0' THEN NULL ELSE APEXDT12 END) AS APEXDT12,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT13), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT13))='0' THEN NULL ELSE APEXDT13 END) AS APEXDT13,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT14), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT14))='0' THEN NULL ELSE APEXDT14 END) AS APEXDT14,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT15), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT15))='0' THEN NULL ELSE APEXDT15 END) AS APEXDT15,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT16), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT16))='0' THEN NULL ELSE APEXDT16 END) AS APEXDT16,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT17), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT17))='0' THEN NULL ELSE APEXDT17 END) AS APEXDT17,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT18), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT18))='0' THEN NULL ELSE APEXDT18 END) AS APEXDT18,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT19), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT19))='0' THEN NULL ELSE APEXDT19 END) AS APEXDT19,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APEXDT20), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APEXDT20))='0' THEN NULL ELSE APEXDT20 END) AS APEXDT20,
CDSTUS,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(STUSDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(STUSDT))='0' THEN NULL ELSE STUSDT END) AS STUSDT,
STUSTM,
WSNO,
TLRNO,
HOTTYPE,
UNLKFG,
PREFG,
APPSEQ,
LANGUAGE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(USEDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(USEDT))='0' THEN NULL ELSE USEDT END) AS USEDT,
KINBR,
APPTLRNO,
FEECD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APPDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APPDT))='0' THEN NULL ELSE APPDT END) AS APPDT,
DIVTYPE,
EMPCARD,
EMPNO,
ITEM1,
ITEM2,
ITEM3,
ITEM4,
ITEM5,
ITEM6,
DESCHIP,
CREDIT,
BRNO,
"NEW",
CIRRUS,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DUEDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DUEDT))='0' THEN NULL ELSE DUEDT END) AS DUEDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RCVDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RCVDT))='0' THEN NULL ELSE RCVDT END) AS RCVDT,
COMBOSEQ,
PRCSB,
PRCNO,
MADFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MADAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MADAY))='0' THEN NULL ELSE MADAY END) AS MADAY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
