-- SQL for table: EDW_GL_GLDPMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EVTCNT' AS DATA_CHK_COL,
EVTCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(EVTCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LNCNT' AS DATA_CHK_COL,
LNCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(LNCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INVCHG' AS DATA_CHK_COL,
INVCHG AS DATA_VAL,
SDG.UFN_NUMCHECK(INVCHG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INVAMT' AS DATA_CHK_COL,
INVAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(INVAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INVQTY' AS DATA_CHK_COL,
INVQTY AS DATA_VAL,
SDG.UFN_NUMCHECK(INVQTY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INVERR' AS DATA_CHK_COL,
INVERR AS DATA_VAL,
SDG.UFN_NUMCHECK(INVERR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TELCHG' AS DATA_CHK_COL,
TELCHG AS DATA_VAL,
SDG.UFN_NUMCHECK(TELCHG) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TCODERR' AS DATA_CHK_COL,
TCODERR AS DATA_VAL,
SDG.UFN_NUMCHECK(TCODERR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TAMTERR' AS DATA_CHK_COL,
TAMTERR AS DATA_VAL,
SDG.UFN_NUMCHECK(TAMTERR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AVEBAL' AS DATA_CHK_COL,
AVEBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(AVEBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'STPBAL' AS DATA_CHK_COL,
STPBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(STPBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LNBAL' AS DATA_CHK_COL,
LNBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(LNBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NDBQTY' AS DATA_CHK_COL,
NDBQTY AS DATA_VAL,
SDG.UFN_NUMCHECK(NDBQTY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NCRQTY' AS DATA_CHK_COL,
NCRQTY AS DATA_VAL,
SDG.UFN_NUMCHECK(NCRQTY) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LTXTNO' AS DATA_CHK_COL,
LTXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(LTXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INITCOST' AS DATA_CHK_COL,
INITCOST AS DATA_VAL,
SDG.UFN_NUMCHECK(INITCOST) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OAVEBAL' AS DATA_CHK_COL,
OAVEBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(OAVEBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SUMAMT' AS DATA_CHK_COL,
SUMAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(SUMAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AVGCOST' AS DATA_CHK_COL,
AVGCOST AS DATA_VAL,
SDG.UFN_NUMCHECK(AVGCOST) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SAERAMT' AS DATA_CHK_COL,
SAERAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(SAERAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EBACTCT' AS DATA_CHK_COL,
EBACTCT AS DATA_VAL,
SDG.UFN_NUMCHECK(EBACTCT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_GL_GLDPMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
CURCD,
EVTCNT,
LNCNT,
INVSTA,
INVACT,
INVCHG,
INVAMT,
INVQTY,
INVERR,
INVDAY,
INVSOUR,
TELSTA,
TELCOD,
TELACT,
TELCHG,
TCODERR,
TCHKFG,
TCHKDAY,
TAMTERR,
TAPLDAY,
TCLSDAY,
THLDDAY,
TROPDAY,
TLTXDAY,
AVEBAL,
STPBAL,
LNBAL,
NDBQTY,
NCRQTY,
NTXDAY,
SELDAY,
BUYDAY,
LKINBR,
LWSNO,
LTXTNO,
TLRNO,
LTXDAY,
TRNCD,
EBACTNO_1,
EBACTNO_2,
EBACTNO_3,
EBACTNO_4,
EBACTNO_5,
EBACTNO_6,
EBACTNO_7,
EBACTNO_8,
INITCOST,
OAVEBAL,
SUMAMT,
AVGCOST,
SAFG,
SAERAMT,
HERITID,
HERITERR,
EBACTFG_1,
EBACTFG_2,
EBACTFG_3,
EBACTFG_4,
EBACTFG_5,
EBACTFG_6,
EBACTFG_7,
EBACTFG_8,
EBACTYR,
EBACTCT,
FILLER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
CURCD,
EVTCNT,
LNCNT,
INVSTA,
INVACT,
INVCHG,
INVAMT,
INVQTY,
INVERR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(INVDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(INVDAY))='0' THEN NULL ELSE INVDAY END) AS INVDAY,
INVSOUR,
TELSTA,
TELCOD,
TELACT,
TELCHG,
TCODERR,
TCHKFG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TCHKDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TCHKDAY))='0' THEN NULL ELSE TCHKDAY END) AS TCHKDAY,
TAMTERR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TAPLDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TAPLDAY))='0' THEN NULL ELSE TAPLDAY END) AS TAPLDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TCLSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TCLSDAY))='0' THEN NULL ELSE TCLSDAY END) AS TCLSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(THLDDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(THLDDAY))='0' THEN NULL ELSE THLDDAY END) AS THLDDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TROPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TROPDAY))='0' THEN NULL ELSE TROPDAY END) AS TROPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TLTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TLTXDAY))='0' THEN NULL ELSE TLTXDAY END) AS TLTXDAY,
AVEBAL,
STPBAL,
LNBAL,
NDBQTY,
NCRQTY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SELDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SELDAY))='0' THEN NULL ELSE SELDAY END) AS SELDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BUYDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BUYDAY))='0' THEN NULL ELSE BUYDAY END) AS BUYDAY,
LKINBR,
LWSNO,
LTXTNO,
TLRNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTXDAY))='0' THEN NULL ELSE LTXDAY END) AS LTXDAY,
TRNCD,
EBACTNO_1,
EBACTNO_2,
EBACTNO_3,
EBACTNO_4,
EBACTNO_5,
EBACTNO_6,
EBACTNO_7,
EBACTNO_8,
INITCOST,
OAVEBAL,
SUMAMT,
AVGCOST,
SAFG,
SAERAMT,
HERITID,
HERITERR,
EBACTFG_1,
EBACTFG_2,
EBACTFG_3,
EBACTFG_4,
EBACTFG_5,
EBACTFG_6,
EBACTFG_7,
EBACTFG_8,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EBACTYR), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EBACTYR))='0' THEN NULL ELSE EBACTYR END) AS EBACTYR,
EBACTCT,
FILLER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
