-- SQL for table: EDW_NCARD_ACCTANALYSIS
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BEG_BAL' AS DATA_CHK_COL,
BEG_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(BEG_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BEG_DUE' AS DATA_CHK_COL,
BEG_DUE AS DATA_VAL,
SDG.UFN_NUMCHECK(BEG_DUE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CURR_BAL' AS DATA_CHK_COL,
CURR_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(CURR_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVER_PMT' AS DATA_CHK_COL,
OVER_PMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OVER_PMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PMT_CTD' AS DATA_CHK_COL,
PMT_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PMT_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DB_CTD' AS DATA_CHK_COL,
DB_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(DB_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_CTD' AS DATA_CHK_COL,
CR_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_CTD' AS DATA_CHK_COL,
PRIN_1_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_CTD' AS DATA_CHK_COL,
PRIN_2_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_CTD' AS DATA_CHK_COL,
PRIN_3_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_CTD' AS DATA_CHK_COL,
PRIN_4_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_CTD' AS DATA_CHK_COL,
PRIN_5_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_CTD' AS DATA_CHK_COL,
INT_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_CTD' AS DATA_CHK_COL,
LC_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_CTD' AS DATA_CHK_COL,
CASH_FEE_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_CTD' AS DATA_CHK_COL,
MEMBER_FEE_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_CTD' AS DATA_CHK_COL,
SERVICE_FEE_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_CTD' AS DATA_CHK_COL,
USER_FEE_1_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_CTD' AS DATA_CHK_COL,
USER_FEE_2_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_CTD' AS DATA_CHK_COL,
USER_FEE_3_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_CTD' AS DATA_CHK_COL,
USER_FEE_4_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_CTD' AS DATA_CHK_COL,
USER_FEE_5_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_CTD' AS DATA_CHK_COL,
USER_FEE_6_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_BILL' AS DATA_CHK_COL,
PRIN_1_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_BILL' AS DATA_CHK_COL,
PRIN_2_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_BILL' AS DATA_CHK_COL,
PRIN_3_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_BILL' AS DATA_CHK_COL,
PRIN_4_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_BILL' AS DATA_CHK_COL,
PRIN_5_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_BILL' AS DATA_CHK_COL,
INT_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_BILL' AS DATA_CHK_COL,
LC_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_BILL' AS DATA_CHK_COL,
CASH_FEE_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_BILL' AS DATA_CHK_COL,
MEMBER_FEE_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_BILL' AS DATA_CHK_COL,
SERVICE_FEE_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_BILL' AS DATA_CHK_COL,
USER_FEE_1_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_BILL' AS DATA_CHK_COL,
USER_FEE_2_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_BILL' AS DATA_CHK_COL,
USER_FEE_3_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_BILL' AS DATA_CHK_COL,
USER_FEE_4_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_BILL' AS DATA_CHK_COL,
USER_FEE_5_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_BILL' AS DATA_CHK_COL,
USER_FEE_6_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_COLL' AS DATA_CHK_COL,
PRIN_1_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_COLL' AS DATA_CHK_COL,
PRIN_2_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_COLL' AS DATA_CHK_COL,
PRIN_3_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_COLL' AS DATA_CHK_COL,
PRIN_4_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_COLL' AS DATA_CHK_COL,
PRIN_5_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_COLL' AS DATA_CHK_COL,
INT_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_COLL' AS DATA_CHK_COL,
LC_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_COLL' AS DATA_CHK_COL,
CASH_FEE_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_COLL' AS DATA_CHK_COL,
MEMBER_FEE_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_COLL' AS DATA_CHK_COL,
SERVICE_FEE_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_COLL' AS DATA_CHK_COL,
USER_FEE_1_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_COLL' AS DATA_CHK_COL,
USER_FEE_2_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_COLL' AS DATA_CHK_COL,
USER_FEE_3_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_COLL' AS DATA_CHK_COL,
USER_FEE_4_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_COLL' AS DATA_CHK_COL,
USER_FEE_5_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_COLL' AS DATA_CHK_COL,
USER_FEE_6_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_CHGOFF' AS DATA_CHK_COL,
PRIN_1_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_CHGOFF' AS DATA_CHK_COL,
PRIN_2_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_CHGOFF' AS DATA_CHK_COL,
PRIN_3_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_CHGOFF' AS DATA_CHK_COL,
PRIN_4_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_CHGOFF' AS DATA_CHK_COL,
PRIN_5_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_CHGOFF' AS DATA_CHK_COL,
INT_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_CHGOFF' AS DATA_CHK_COL,
LC_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_CHGOFF' AS DATA_CHK_COL,
CASH_FEE_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_CHGOFF' AS DATA_CHK_COL,
MEMBER_FEE_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_CHGOFF' AS DATA_CHK_COL,
SERVICE_FEE_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_CHGOFF' AS DATA_CHK_COL,
USER_FEE_1_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_CHGOFF' AS DATA_CHK_COL,
USER_FEE_2_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_CHGOFF' AS DATA_CHK_COL,
USER_FEE_3_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_CHGOFF' AS DATA_CHK_COL,
USER_FEE_4_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_CHGOFF' AS DATA_CHK_COL,
USER_FEE_5_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_CHGOFF' AS DATA_CHK_COL,
USER_FEE_6_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_REVOLVING' AS DATA_CHK_COL,
PRIN_1_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_REVOLVING' AS DATA_CHK_COL,
PRIN_2_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_REVOLVING' AS DATA_CHK_COL,
PRIN_3_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_REVOLVING' AS DATA_CHK_COL,
PRIN_4_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_REVOLVING' AS DATA_CHK_COL,
PRIN_5_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'STMT_BAL' AS DATA_CHK_COL,
STMT_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(STMT_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'STMT_DUE' AS DATA_CHK_COL,
STMT_DUE AS DATA_VAL,
SDG.UFN_NUMCHECK(STMT_DUE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_1' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_2' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_3' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_4' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_5' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_6' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_7' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_8' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_9' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_10' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_11' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_12' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_1' AS DATA_CHK_COL,
BAL_BUCKET_AMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_2' AS DATA_CHK_COL,
BAL_BUCKET_AMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_3' AS DATA_CHK_COL,
BAL_BUCKET_AMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_4' AS DATA_CHK_COL,
BAL_BUCKET_AMT_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_5' AS DATA_CHK_COL,
BAL_BUCKET_AMT_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_6' AS DATA_CHK_COL,
BAL_BUCKET_AMT_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_7' AS DATA_CHK_COL,
BAL_BUCKET_AMT_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_8' AS DATA_CHK_COL,
BAL_BUCKET_AMT_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_9' AS DATA_CHK_COL,
BAL_BUCKET_AMT_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_10' AS DATA_CHK_COL,
BAL_BUCKET_AMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_11' AS DATA_CHK_COL,
BAL_BUCKET_AMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_12' AS DATA_CHK_COL,
BAL_BUCKET_AMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_CHG_CNT' AS DATA_CHK_COL,
LC_CHG_CNT AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_CHG_CNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DD1_ASSIGN_AMT' AS DATA_CHK_COL,
DD1_ASSIGN_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(DD1_ASSIGN_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DD1_ASSIGN_PCT' AS DATA_CHK_COL,
DD1_ASSIGN_PCT AS DATA_VAL,
SDG.UFN_NUMCHECK(DD1_ASSIGN_PCT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MAX_DUE' AS DATA_CHK_COL,
MAX_DUE AS DATA_VAL,
SDG.UFN_NUMCHECK(MAX_DUE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MAX_REVOLVING' AS DATA_CHK_COL,
MAX_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(MAX_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CREDIT_LIMIT' AS DATA_CHK_COL,
CREDIT_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(CREDIT_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CREDIT_AVAIL' AS DATA_CHK_COL,
CREDIT_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(CREDIT_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CREDIT_LIMIT_PERM' AS DATA_CHK_COL,
CREDIT_LIMIT_PERM AS DATA_VAL,
SDG.UFN_NUMCHECK(CREDIT_LIMIT_PERM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_LIMIT' AS DATA_CHK_COL,
CASH_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_AVAIL' AS DATA_CHK_COL,
CASH_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC1_LIMIT' AS DATA_CHK_COL,
SPEC1_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC1_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC1_AVAIL' AS DATA_CHK_COL,
SPEC1_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC1_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC2_LIMIT' AS DATA_CHK_COL,
SPEC2_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC2_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC2_AVAIL' AS DATA_CHK_COL,
SPEC2_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC2_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC3_LIMIT' AS DATA_CHK_COL,
SPEC3_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC3_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC3_AVAIL' AS DATA_CHK_COL,
SPEC3_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC3_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TEMP_LIMIT' AS DATA_CHK_COL,
TEMP_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(TEMP_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_1_RATE' AS DATA_CHK_COL,
INT_1_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_1_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_2_RATE' AS DATA_CHK_COL,
INT_2_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_2_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_3_RATE' AS DATA_CHK_COL,
INT_3_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_3_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_4_RATE' AS DATA_CHK_COL,
INT_4_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_4_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_5_RATE' AS DATA_CHK_COL,
INT_5_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_5_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_BEG_BAL' AS DATA_CHK_COL,
COLL_BEG_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_BEG_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_PRIN_1' AS DATA_CHK_COL,
COLL_PRIN_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_PRIN_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_PRIN_2' AS DATA_CHK_COL,
COLL_PRIN_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_PRIN_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_PRIN_3' AS DATA_CHK_COL,
COLL_PRIN_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_PRIN_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_PRIN_4' AS DATA_CHK_COL,
COLL_PRIN_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_PRIN_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_PRIN_5' AS DATA_CHK_COL,
COLL_PRIN_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_PRIN_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_INT' AS DATA_CHK_COL,
COLL_INT AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_INT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_FEE' AS DATA_CHK_COL,
COLL_FEE AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_FEE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_RECOVERY_AMT' AS DATA_CHK_COL,
COLL_RECOVERY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_RECOVERY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_REDUCE_DEBIT' AS DATA_CHK_COL,
COLL_REDUCE_DEBIT AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_REDUCE_DEBIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLL_RECOG_REVENUE' AS DATA_CHK_COL,
COLL_RECOG_REVENUE AS DATA_VAL,
SDG.UFN_NUMCHECK(COLL_RECOG_REVENUE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_BEG_BAL' AS DATA_CHK_COL,
CHGOFF_BEG_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_BEG_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_PRIN_1' AS DATA_CHK_COL,
CHGOFF_PRIN_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_PRIN_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_PRIN_2' AS DATA_CHK_COL,
CHGOFF_PRIN_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_PRIN_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_PRIN_3' AS DATA_CHK_COL,
CHGOFF_PRIN_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_PRIN_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_PRIN_4' AS DATA_CHK_COL,
CHGOFF_PRIN_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_PRIN_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_PRIN_5' AS DATA_CHK_COL,
CHGOFF_PRIN_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_PRIN_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_INT' AS DATA_CHK_COL,
CHGOFF_INT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_INT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_FEE' AS DATA_CHK_COL,
CHGOFF_FEE AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_FEE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_RECOVERY_AMT' AS DATA_CHK_COL,
CHGOFF_RECOVERY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_RECOVERY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_REDUCE_DEBIT' AS DATA_CHK_COL,
CHGOFF_REDUCE_DEBIT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_REDUCE_DEBIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGOFF_RECOG_REVENUE' AS DATA_CHK_COL,
CHGOFF_RECOG_REVENUE AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGOFF_RECOG_REVENUE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONFER_INT_RATE' AS DATA_CHK_COL,
CONFER_INT_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(CONFER_INT_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONFER_INST_TERM' AS DATA_CHK_COL,
CONFER_INST_TERM AS DATA_VAL,
SDG.UFN_NUMCHECK(CONFER_INST_TERM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONFER_EACH_PAY_AMT' AS DATA_CHK_COL,
CONFER_EACH_PAY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CONFER_EACH_PAY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONFER_INST_TERM_PAID' AS DATA_CHK_COL,
CONFER_INST_TERM_PAID AS DATA_VAL,
SDG.UFN_NUMCHECK(CONFER_INST_TERM_PAID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONFER_FINAL_CONFER_PAID' AS DATA_CHK_COL,
CONFER_FINAL_CONFER_PAID AS DATA_VAL,
SDG.UFN_NUMCHECK(CONFER_FINAL_CONFER_PAID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INST_UNPAID_NORMAL' AS DATA_CHK_COL,
INST_UNPAID_NORMAL AS DATA_VAL,
SDG.UFN_NUMCHECK(INST_UNPAID_NORMAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INST_UNPAID_CASH' AS DATA_CHK_COL,
INST_UNPAID_CASH AS DATA_VAL,
SDG.UFN_NUMCHECK(INST_UNPAID_CASH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INST_UNPAID_CONFER' AS DATA_CHK_COL,
INST_UNPAID_CONFER AS DATA_VAL,
SDG.UFN_NUMCHECK(INST_UNPAID_CONFER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INST_UNPAID_BT' AS DATA_CHK_COL,
INST_UNPAID_BT AS DATA_VAL,
SDG.UFN_NUMCHECK(INST_UNPAID_BT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INST_UNPAID_STMT' AS DATA_CHK_COL,
INST_UNPAID_STMT AS DATA_VAL,
SDG.UFN_NUMCHECK(INST_UNPAID_STMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVER_DUE_DAYS' AS DATA_CHK_COL,
OVER_DUE_DAYS AS DATA_VAL,
SDG.UFN_NUMCHECK(OVER_DUE_DAYS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCRUED_INT' AS DATA_CHK_COL,
ACCRUED_INT AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCRUED_INT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PMT_AMT_LAST' AS DATA_CHK_COL,
PMT_AMT_LAST AS DATA_VAL,
SDG.UFN_NUMCHECK(PMT_AMT_LAST) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_BILL_STMT' AS DATA_CHK_COL,
PRIN_1_BILL_STMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_BILL_STMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_BILL_STMT' AS DATA_CHK_COL,
PRIN_2_BILL_STMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_BILL_STMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_BILL_STMT' AS DATA_CHK_COL,
PRIN_3_BILL_STMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_BILL_STMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_BILL_STMT' AS DATA_CHK_COL,
PRIN_4_BILL_STMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_BILL_STMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_BILL_STMT' AS DATA_CHK_COL,
PRIN_5_BILL_STMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_BILL_STMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_BILL_REVOLV' AS DATA_CHK_COL,
PRIN_1_BILL_REVOLV AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_BILL_REVOLV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_BILL_REVOLV' AS DATA_CHK_COL,
PRIN_2_BILL_REVOLV AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_BILL_REVOLV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_BILL_REVOLV' AS DATA_CHK_COL,
PRIN_3_BILL_REVOLV AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_BILL_REVOLV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_BILL_REVOLV' AS DATA_CHK_COL,
PRIN_4_BILL_REVOLV AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_BILL_REVOLV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_BILL_REVOLV' AS DATA_CHK_COL,
PRIN_5_BILL_REVOLV AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_BILL_REVOLV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONFER_UNPAID_PRIN' AS DATA_CHK_COL,
CONFER_UNPAID_PRIN AS DATA_VAL,
SDG.UFN_NUMCHECK(CONFER_UNPAID_PRIN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_BT' AS DATA_CHK_COL,
PRIN_BT AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_BT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DISPUTE_BAL' AS DATA_CHK_COL,
DISPUTE_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(DISPUTE_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OWN_CARDS' AS DATA_CHK_COL,
OWN_CARDS AS DATA_VAL,
SDG.UFN_NUMCHECK(OWN_CARDS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTIVE_P_CARDS' AS DATA_CHK_COL,
ACTIVE_P_CARDS AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTIVE_P_CARDS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACTIVE_S_CARDS' AS DATA_CHK_COL,
ACTIVE_S_CARDS AS DATA_VAL,
SDG.UFN_NUMCHECK(ACTIVE_S_CARDS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_NCARD_ACCTANALYSIS
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID,
CARD_FLAG,
BEG_BAL,
BEG_DUE,
CURR_BAL,
OVER_PMT,
PMT_CTD,
DB_CTD,
CR_CTD,
PRIN_1_CTD,
PRIN_2_CTD,
PRIN_3_CTD,
PRIN_4_CTD,
PRIN_5_CTD,
INT_CTD,
LC_CTD,
CASH_FEE_CTD,
MEMBER_FEE_CTD,
SERVICE_FEE_CTD,
USER_FEE_1_CTD,
USER_FEE_2_CTD,
USER_FEE_3_CTD,
USER_FEE_4_CTD,
USER_FEE_5_CTD,
USER_FEE_6_CTD,
PRIN_1_BILL,
PRIN_2_BILL,
PRIN_3_BILL,
PRIN_4_BILL,
PRIN_5_BILL,
INT_BILL,
LC_BILL,
CASH_FEE_BILL,
MEMBER_FEE_BILL,
SERVICE_FEE_BILL,
USER_FEE_1_BILL,
USER_FEE_2_BILL,
USER_FEE_3_BILL,
USER_FEE_4_BILL,
USER_FEE_5_BILL,
USER_FEE_6_BILL,
PRIN_1_COLL,
PRIN_2_COLL,
PRIN_3_COLL,
PRIN_4_COLL,
PRIN_5_COLL,
INT_COLL,
LC_COLL,
CASH_FEE_COLL,
MEMBER_FEE_COLL,
SERVICE_FEE_COLL,
USER_FEE_1_COLL,
USER_FEE_2_COLL,
USER_FEE_3_COLL,
USER_FEE_4_COLL,
USER_FEE_5_COLL,
USER_FEE_6_COLL,
PRIN_1_CHGOFF,
PRIN_2_CHGOFF,
PRIN_3_CHGOFF,
PRIN_4_CHGOFF,
PRIN_5_CHGOFF,
INT_CHGOFF,
LC_CHGOFF,
CASH_FEE_CHGOFF,
MEMBER_FEE_CHGOFF,
SERVICE_FEE_CHGOFF,
USER_FEE_1_CHGOFF,
USER_FEE_2_CHGOFF,
USER_FEE_3_CHGOFF,
USER_FEE_4_CHGOFF,
USER_FEE_5_CHGOFF,
USER_FEE_6_CHGOFF,
PRIN_1_REVOLVING,
PRIN_2_REVOLVING,
PRIN_3_REVOLVING,
PRIN_4_REVOLVING,
PRIN_5_REVOLVING,
STMT_BAL,
STMT_DUE,
DUE_DTE,
GRACE_DTE,
LATE_DTE,
PAY_IN_FULL,
PAY_IN_MINI,
DELQ_STATUS_HIST,
PMT_STATUS_HIST,
STMT_DATE,
DELQ_BUCKET_AMT_1,
DELQ_BUCKET_AMT_2,
DELQ_BUCKET_AMT_3,
DELQ_BUCKET_AMT_4,
DELQ_BUCKET_AMT_5,
DELQ_BUCKET_AMT_6,
DELQ_BUCKET_AMT_7,
DELQ_BUCKET_AMT_8,
DELQ_BUCKET_AMT_9,
DELQ_BUCKET_AMT_10,
DELQ_BUCKET_AMT_11,
DELQ_BUCKET_AMT_12,
BAL_BUCKET_AMT_1,
BAL_BUCKET_AMT_2,
BAL_BUCKET_AMT_3,
BAL_BUCKET_AMT_4,
BAL_BUCKET_AMT_5,
BAL_BUCKET_AMT_6,
BAL_BUCKET_AMT_7,
BAL_BUCKET_AMT_8,
BAL_BUCKET_AMT_9,
BAL_BUCKET_AMT_10,
BAL_BUCKET_AMT_11,
BAL_BUCKET_AMT_12,
PAYOFF_DTE,
LC_CHG_CNT,
M0_STMT_DTE,
ACCT_STATUS,
CUST_BU,
CUST_NBR,
CYCLE,
COLL_DTE,
CHGOFF_DTE,
DORMANT_DTE,
CTL_CODE,
CTL_CODE_DTE,
CTL_CODE_REASON,
DD1_BANK,
DD1_BANK_NBR,
DD1_START_DTE,
DD1_END_DTE,
DD1_METHOD,
DD1_ASSIGN_AMT,
DD1_ASSIGN_PCT,
MAX_DUE,
MAX_REVOLVING,
STOP_DELQ,
OPEN_DTE_ACCT,
NAME,
VIP_FLAG,
CUST_TYPE,
CELL_PHONE_1,
STMT_ADDR_ZIP,
STMT_ADDR_ZONE,
STMT_ADDR,
HOME_PHONE,
EMP_NBR,
EMP_NAME,
EMP_PHONE,
EMP_TITLE,
RELA_NAME,
RELA_REL,
RELA_EMP_PHONE,
RELA_HOME_PHONE,
FRIEND_NAME,
FRIEND_REL,
FRIEND_EMP_PHONE,
FRIEND_HOME_PHONE,
COMM_FLAG_1,
COMM_FLAG_2,
COMM_FLAG_3,
COMM_FLAG_4,
COMM_FLAG_5,
LIMIT_CONTROL,
CREDIT_LIMIT,
CREDIT_AVAIL,
CREDIT_LIMIT_PERM,
CASH_LIMIT,
CASH_AVAIL,
SPEC1_LIMIT,
SPEC1_AVAIL,
SPEC2_LIMIT,
SPEC2_AVAIL,
SPEC3_LIMIT,
SPEC3_AVAIL,
TEMP_LIMIT,
TEMP_LIMIT_START_DTE,
TEMP_LIMIT_END_DTE,
INT_1_RATE,
INT_2_RATE,
INT_3_RATE,
INT_4_RATE,
INT_5_RATE,
COLL_BEG_BAL,
COLL_PRIN_1,
COLL_PRIN_2,
COLL_PRIN_3,
COLL_PRIN_4,
COLL_PRIN_5,
COLL_INT,
COLL_FEE,
COLL_RECOVERY_AMT,
COLL_REDUCE_DEBIT,
COLL_RECOG_REVENUE,
CHGOFF_BEG_BAL,
CHGOFF_PRIN_1,
CHGOFF_PRIN_2,
CHGOFF_PRIN_3,
CHGOFF_PRIN_4,
CHGOFF_PRIN_5,
CHGOFF_INT,
CHGOFF_FEE,
CHGOFF_RECOVERY_AMT,
CHGOFF_REDUCE_DEBIT,
CHGOFF_RECOG_REVENUE,
CONFER_TYPE,
CONFER_ORIG_DUE,
CONFER_APPLY_DTE,
CONFER_INT_RATE,
CONFER_INST_TERM,
CONFER_EACH_PAY_AMT,
CONFER_INST_TERM_PAID,
CONFER_FINAL_CONFER_PAID,
COMMEND_UNIT_FLAG,
COMMEND_UNIT_NBR,
COMMEND_UNIT_CODE,
COMMEND_ID,
COMMEND_NAME,
COMMEND_ACCT,
INST_UNPAID_NORMAL,
INST_UNPAID_CASH,
INST_UNPAID_CONFER,
INST_UNPAID_BT,
INST_UNPAID_STMT,
ACCT_VALID,
OVER_DUE_DAYS,
ACCRUED_INT,
CARD_NBR,
ALL_STOP,
CARD_TYPE,
PMT_DTE_LAST,
PMT_AMT_LAST,
ADDR_BRANCH,
AREA,
PRIN_1_BILL_STMT,
PRIN_2_BILL_STMT,
PRIN_3_BILL_STMT,
PRIN_4_BILL_STMT,
PRIN_5_BILL_STMT,
PRIN_1_BILL_REVOLV,
PRIN_2_BILL_REVOLV,
PRIN_3_BILL_REVOLV,
PRIN_4_BILL_REVOLV,
PRIN_5_BILL_REVOLV,
CONFER_STATUS,
CONFER_UNPAID_PRIN,
PRIN_BT,
DISPUTE_BAL,
OWN_CARDS,
ACTIVE_P_CARDS,
ACTIVE_S_CARDS,
FORCE_STOP_DTE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID,
CARD_FLAG,
BEG_BAL,
BEG_DUE,
CURR_BAL,
OVER_PMT,
PMT_CTD,
DB_CTD,
CR_CTD,
PRIN_1_CTD,
PRIN_2_CTD,
PRIN_3_CTD,
PRIN_4_CTD,
PRIN_5_CTD,
INT_CTD,
LC_CTD,
CASH_FEE_CTD,
MEMBER_FEE_CTD,
SERVICE_FEE_CTD,
USER_FEE_1_CTD,
USER_FEE_2_CTD,
USER_FEE_3_CTD,
USER_FEE_4_CTD,
USER_FEE_5_CTD,
USER_FEE_6_CTD,
PRIN_1_BILL,
PRIN_2_BILL,
PRIN_3_BILL,
PRIN_4_BILL,
PRIN_5_BILL,
INT_BILL,
LC_BILL,
CASH_FEE_BILL,
MEMBER_FEE_BILL,
SERVICE_FEE_BILL,
USER_FEE_1_BILL,
USER_FEE_2_BILL,
USER_FEE_3_BILL,
USER_FEE_4_BILL,
USER_FEE_5_BILL,
USER_FEE_6_BILL,
PRIN_1_COLL,
PRIN_2_COLL,
PRIN_3_COLL,
PRIN_4_COLL,
PRIN_5_COLL,
INT_COLL,
LC_COLL,
CASH_FEE_COLL,
MEMBER_FEE_COLL,
SERVICE_FEE_COLL,
USER_FEE_1_COLL,
USER_FEE_2_COLL,
USER_FEE_3_COLL,
USER_FEE_4_COLL,
USER_FEE_5_COLL,
USER_FEE_6_COLL,
PRIN_1_CHGOFF,
PRIN_2_CHGOFF,
PRIN_3_CHGOFF,
PRIN_4_CHGOFF,
PRIN_5_CHGOFF,
INT_CHGOFF,
LC_CHGOFF,
CASH_FEE_CHGOFF,
MEMBER_FEE_CHGOFF,
SERVICE_FEE_CHGOFF,
USER_FEE_1_CHGOFF,
USER_FEE_2_CHGOFF,
USER_FEE_3_CHGOFF,
USER_FEE_4_CHGOFF,
USER_FEE_5_CHGOFF,
USER_FEE_6_CHGOFF,
PRIN_1_REVOLVING,
PRIN_2_REVOLVING,
PRIN_3_REVOLVING,
PRIN_4_REVOLVING,
PRIN_5_REVOLVING,
STMT_BAL,
STMT_DUE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DUE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DUE_DTE))='0' THEN NULL ELSE DUE_DTE END) AS DUE_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRACE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRACE_DTE))='0' THEN NULL ELSE GRACE_DTE END) AS GRACE_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LATE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LATE_DTE))='0' THEN NULL ELSE LATE_DTE END) AS LATE_DTE,
PAY_IN_FULL,
PAY_IN_MINI,
DELQ_STATUS_HIST,
PMT_STATUS_HIST,
STMT_DATE,
DELQ_BUCKET_AMT_1,
DELQ_BUCKET_AMT_2,
DELQ_BUCKET_AMT_3,
DELQ_BUCKET_AMT_4,
DELQ_BUCKET_AMT_5,
DELQ_BUCKET_AMT_6,
DELQ_BUCKET_AMT_7,
DELQ_BUCKET_AMT_8,
DELQ_BUCKET_AMT_9,
DELQ_BUCKET_AMT_10,
DELQ_BUCKET_AMT_11,
DELQ_BUCKET_AMT_12,
BAL_BUCKET_AMT_1,
BAL_BUCKET_AMT_2,
BAL_BUCKET_AMT_3,
BAL_BUCKET_AMT_4,
BAL_BUCKET_AMT_5,
BAL_BUCKET_AMT_6,
BAL_BUCKET_AMT_7,
BAL_BUCKET_AMT_8,
BAL_BUCKET_AMT_9,
BAL_BUCKET_AMT_10,
BAL_BUCKET_AMT_11,
BAL_BUCKET_AMT_12,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PAYOFF_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PAYOFF_DTE))='0' THEN NULL ELSE PAYOFF_DTE END) AS PAYOFF_DTE,
LC_CHG_CNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(M0_STMT_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(M0_STMT_DTE))='0' THEN NULL ELSE M0_STMT_DTE END) AS M0_STMT_DTE,
ACCT_STATUS,
CUST_BU,
CUST_NBR,
CYCLE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(COLL_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(COLL_DTE))='0' THEN NULL ELSE COLL_DTE END) AS COLL_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CHGOFF_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CHGOFF_DTE))='0' THEN NULL ELSE CHGOFF_DTE END) AS CHGOFF_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DORMANT_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DORMANT_DTE))='0' THEN NULL ELSE DORMANT_DTE END) AS DORMANT_DTE,
CTL_CODE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CTL_CODE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CTL_CODE_DTE))='0' THEN NULL ELSE CTL_CODE_DTE END) AS CTL_CODE_DTE,
CTL_CODE_REASON,
DD1_BANK,
DD1_BANK_NBR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DD1_START_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DD1_START_DTE))='0' THEN NULL ELSE DD1_START_DTE END) AS DD1_START_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DD1_END_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DD1_END_DTE))='0' THEN NULL ELSE DD1_END_DTE END) AS DD1_END_DTE,
DD1_METHOD,
DD1_ASSIGN_AMT,
DD1_ASSIGN_PCT,
MAX_DUE,
MAX_REVOLVING,
STOP_DELQ,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPEN_DTE_ACCT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPEN_DTE_ACCT))='0' THEN NULL ELSE OPEN_DTE_ACCT END) AS OPEN_DTE_ACCT,
NAME,
VIP_FLAG,
CUST_TYPE,
CELL_PHONE_1,
STMT_ADDR_ZIP,
STMT_ADDR_ZONE,
STMT_ADDR,
HOME_PHONE,
EMP_NBR,
EMP_NAME,
EMP_PHONE,
EMP_TITLE,
RELA_NAME,
RELA_REL,
RELA_EMP_PHONE,
RELA_HOME_PHONE,
FRIEND_NAME,
FRIEND_REL,
FRIEND_EMP_PHONE,
FRIEND_HOME_PHONE,
COMM_FLAG_1,
COMM_FLAG_2,
COMM_FLAG_3,
COMM_FLAG_4,
COMM_FLAG_5,
LIMIT_CONTROL,
CREDIT_LIMIT,
CREDIT_AVAIL,
CREDIT_LIMIT_PERM,
CASH_LIMIT,
CASH_AVAIL,
SPEC1_LIMIT,
SPEC1_AVAIL,
SPEC2_LIMIT,
SPEC2_AVAIL,
SPEC3_LIMIT,
SPEC3_AVAIL,
TEMP_LIMIT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TEMP_LIMIT_START_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TEMP_LIMIT_START_DTE))='0' THEN NULL ELSE TEMP_LIMIT_START_DTE END) AS TEMP_LIMIT_START_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TEMP_LIMIT_END_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TEMP_LIMIT_END_DTE))='0' THEN NULL ELSE TEMP_LIMIT_END_DTE END) AS TEMP_LIMIT_END_DTE,
INT_1_RATE,
INT_2_RATE,
INT_3_RATE,
INT_4_RATE,
INT_5_RATE,
COLL_BEG_BAL,
COLL_PRIN_1,
COLL_PRIN_2,
COLL_PRIN_3,
COLL_PRIN_4,
COLL_PRIN_5,
COLL_INT,
COLL_FEE,
COLL_RECOVERY_AMT,
COLL_REDUCE_DEBIT,
COLL_RECOG_REVENUE,
CHGOFF_BEG_BAL,
CHGOFF_PRIN_1,
CHGOFF_PRIN_2,
CHGOFF_PRIN_3,
CHGOFF_PRIN_4,
CHGOFF_PRIN_5,
CHGOFF_INT,
CHGOFF_FEE,
CHGOFF_RECOVERY_AMT,
CHGOFF_REDUCE_DEBIT,
CHGOFF_RECOG_REVENUE,
CONFER_TYPE,
CONFER_ORIG_DUE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CONFER_APPLY_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CONFER_APPLY_DTE))='0' THEN NULL ELSE CONFER_APPLY_DTE END) AS CONFER_APPLY_DTE,
CONFER_INT_RATE,
CONFER_INST_TERM,
CONFER_EACH_PAY_AMT,
CONFER_INST_TERM_PAID,
CONFER_FINAL_CONFER_PAID,
COMMEND_UNIT_FLAG,
COMMEND_UNIT_NBR,
COMMEND_UNIT_CODE,
COMMEND_ID,
COMMEND_NAME,
COMMEND_ACCT,
INST_UNPAID_NORMAL,
INST_UNPAID_CASH,
INST_UNPAID_CONFER,
INST_UNPAID_BT,
INST_UNPAID_STMT,
ACCT_VALID,
OVER_DUE_DAYS,
ACCRUED_INT,
CARD_NBR,
ALL_STOP,
CARD_TYPE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PMT_DTE_LAST), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PMT_DTE_LAST))='0' THEN NULL ELSE PMT_DTE_LAST END) AS PMT_DTE_LAST,
PMT_AMT_LAST,
ADDR_BRANCH,
AREA,
PRIN_1_BILL_STMT,
PRIN_2_BILL_STMT,
PRIN_3_BILL_STMT,
PRIN_4_BILL_STMT,
PRIN_5_BILL_STMT,
PRIN_1_BILL_REVOLV,
PRIN_2_BILL_REVOLV,
PRIN_3_BILL_REVOLV,
PRIN_4_BILL_REVOLV,
PRIN_5_BILL_REVOLV,
CONFER_STATUS,
CONFER_UNPAID_PRIN,
PRIN_BT,
DISPUTE_BAL,
OWN_CARDS,
ACTIVE_P_CARDS,
ACTIVE_S_CARDS,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(FORCE_STOP_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(FORCE_STOP_DTE))='0' THEN NULL ELSE FORCE_STOP_DTE END) AS FORCE_STOP_DTE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
