-- SQL for table: EDW_NCARD_CUSTLIMIT
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CREDIT_LIMIT' AS DATA_CHK_COL,
CREDIT_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(CREDIT_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CREDIT_AVAIL' AS DATA_CHK_COL,
CREDIT_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(CREDIT_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PERM_LIMIT' AS DATA_CHK_COL,
PERM_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(PERM_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_LIMIT' AS DATA_CHK_COL,
CASH_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_AVAIL' AS DATA_CHK_COL,
CASH_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC1_LIMIT' AS DATA_CHK_COL,
SPEC1_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC1_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC1_AVAIL' AS DATA_CHK_COL,
SPEC1_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC1_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC2_LIMIT' AS DATA_CHK_COL,
SPEC2_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC2_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC2_AVAIL' AS DATA_CHK_COL,
SPEC2_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC2_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC3_LIMIT' AS DATA_CHK_COL,
SPEC3_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC3_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPEC3_AVAIL' AS DATA_CHK_COL,
SPEC3_AVAIL AS DATA_VAL,
SDG.UFN_NUMCHECK(SPEC3_AVAIL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TEMP_LIMIT' AS DATA_CHK_COL,
TEMP_LIMIT AS DATA_VAL,
SDG.UFN_NUMCHECK(TEMP_LIMIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMO_DB_AMT' AS DATA_CHK_COL,
MEMO_DB_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMO_DB_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMO_CR_AMT' AS DATA_CHK_COL,
MEMO_CR_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMO_CR_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_AMT' AS DATA_CHK_COL,
BAL_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUST_LIMIT_AMT_1' AS DATA_CHK_COL,
CUST_LIMIT_AMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(CUST_LIMIT_AMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUST_LIMIT_AMT_2' AS DATA_CHK_COL,
CUST_LIMIT_AMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(CUST_LIMIT_AMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUST_LIMIT_AMT_3' AS DATA_CHK_COL,
CUST_LIMIT_AMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(CUST_LIMIT_AMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUST_LIMIT_AMT_4' AS DATA_CHK_COL,
CUST_LIMIT_AMT_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(CUST_LIMIT_AMT_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CUST_LIMIT_AMT_5' AS DATA_CHK_COL,
CUST_LIMIT_AMT_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(CUST_LIMIT_AMT_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_NCARD_CUSTLIMIT
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BU,
CUST_NBR,
LIMIT_CTL,
CREDIT_LIMIT,
CREDIT_AVAIL,
PERM_LIMIT,
CASH_LIMIT,
CASH_AVAIL,
SPEC1_LIMIT,
SPEC1_AVAIL,
SPEC2_LIMIT,
SPEC2_AVAIL,
SPEC3_LIMIT,
SPEC3_AVAIL,
TEMP_LIMIT,
TEMP_LIMIT_START_DTE,
TEMP_LIMIT_END_DTE,
MEMO_DB_AMT,
MEMO_CR_AMT,
BAL_AMT,
CUST_LIMIT_AMT_1,
CUST_LIMIT_AMT_2,
CUST_LIMIT_AMT_3,
CUST_LIMIT_AMT_4,
CUST_LIMIT_AMT_5,
CUST_LIMIT_CHAR_1,
CUST_LIMIT_CHAR_2,
CUST_LIMIT_CHAR_3,
CUST_LIMIT_CHAR_4,
CUST_LIMIT_CHAR_5,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BU,
CUST_NBR,
LIMIT_CTL,
CREDIT_LIMIT,
CREDIT_AVAIL,
PERM_LIMIT,
CASH_LIMIT,
CASH_AVAIL,
SPEC1_LIMIT,
SPEC1_AVAIL,
SPEC2_LIMIT,
SPEC2_AVAIL,
SPEC3_LIMIT,
SPEC3_AVAIL,
TEMP_LIMIT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TEMP_LIMIT_START_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TEMP_LIMIT_START_DTE))='0' THEN NULL ELSE TEMP_LIMIT_START_DTE END) AS TEMP_LIMIT_START_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TEMP_LIMIT_END_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TEMP_LIMIT_END_DTE))='0' THEN NULL ELSE TEMP_LIMIT_END_DTE END) AS TEMP_LIMIT_END_DTE,
MEMO_DB_AMT,
MEMO_CR_AMT,
BAL_AMT,
CUST_LIMIT_AMT_1,
CUST_LIMIT_AMT_2,
CUST_LIMIT_AMT_3,
CUST_LIMIT_AMT_4,
CUST_LIMIT_AMT_5,
CUST_LIMIT_CHAR_1,
CUST_LIMIT_CHAR_2,
CUST_LIMIT_CHAR_3,
CUST_LIMIT_CHAR_4,
CUST_LIMIT_CHAR_5,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MNT_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MNT_DT))='0' THEN NULL ELSE MNT_DT END) AS MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
