-- SQL for table: EDW_FXF_FCRIF
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OURACT1' AS DATA_CHK_COL,
OURACT1 AS DATA_VAL,
SDG.UFN_NUMCHECK(OURACT1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OURACT2' AS DATA_CHK_COL,
OURACT2 AS DATA_VAL,
SDG.UFN_NUMCHECK(OURACT2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVRAMT' AS DATA_CHK_COL,
OVRAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OVRAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CLBKNO' AS DATA_CHK_COL,
CLBKNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CLBKNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RISK' AS DATA_CHK_COL,
RISK AS DATA_VAL,
SDG.UFN_NUMCHECK(RISK) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORGRISK' AS DATA_CHK_COL,
ORGRISK AS DATA_VAL,
SDG.UFN_NUMCHECK(ORGRISK) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXF_FCRIF
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BKCODE,
BRNO,
CHKDG,
SWFCD,
BKNAM1,
BKNAM2,
BRNAM,
BKADRFG_1,
BKADR1_1,
BKADR2_1,
BKADR3_1,
BKADR4_1,
BKADR5_1,
BKADR6_1,
BKADR7_1,
BKADR8_1,
BKADRFG_2,
BKADR1_2,
BKADR2_2,
BKADR3_2,
BKADR4_2,
BKADR5_2,
BKADR6_2,
BKADR7_2,
BKADR8_2,
BKADRFG_3,
BKADR1_3,
BKADR2_3,
BKADR3_3,
BKADR4_3,
BKADR5_3,
BKADR6_3,
BKADR7_3,
BKADR8_3,
CITY,
CNTRYCD,
NAL,
TLXNO,
FAXNO,
CTLDOC,
SWFCTL,
OURACT1,
OURACT2,
YYMM,
CLRCD1,
CLRTXT1,
CLRCD2,
CLRTXT2,
REMARK1,
REMARK2,
REMARK3,
REMARK4,
REMARK5,
REMARK6,
REMARK7,
REMARK8,
OVRAMT,
DELCD,
LASTDT,
CREDAT,
CLBKNO,
KINBR,
TLRNO,
SPFG,
SPRMK1,
SPRMK2,
BLACK_1,
BLACK_2,
BLACK_3,
BLACK_4,
BLACK_5,
BKNOTE,
RISK,
ORGRISK,
CDDNOTE,
KYCDT,
KYCLDT,
CDDDT,
PNAME1,
PNAME2,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BKCODE,
BRNO,
CHKDG,
SWFCD,
BKNAM1,
BKNAM2,
BRNAM,
BKADRFG_1,
BKADR1_1,
BKADR2_1,
BKADR3_1,
BKADR4_1,
BKADR5_1,
BKADR6_1,
BKADR7_1,
BKADR8_1,
BKADRFG_2,
BKADR1_2,
BKADR2_2,
BKADR3_2,
BKADR4_2,
BKADR5_2,
BKADR6_2,
BKADR7_2,
BKADR8_2,
BKADRFG_3,
BKADR1_3,
BKADR2_3,
BKADR3_3,
BKADR4_3,
BKADR5_3,
BKADR6_3,
BKADR7_3,
BKADR8_3,
CITY,
CNTRYCD,
NAL,
TLXNO,
FAXNO,
CTLDOC,
SWFCTL,
OURACT1,
OURACT2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(YYMM), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(YYMM))='0' THEN NULL ELSE YYMM END) AS YYMM,
CLRCD1,
CLRTXT1,
CLRCD2,
CLRTXT2,
REMARK1,
REMARK2,
REMARK3,
REMARK4,
REMARK5,
REMARK6,
REMARK7,
REMARK8,
OVRAMT,
DELCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREDAT))='0' THEN NULL ELSE CREDAT END) AS CREDAT,
CLBKNO,
KINBR,
TLRNO,
SPFG,
SPRMK1,
SPRMK2,
BLACK_1,
BLACK_2,
BLACK_3,
BLACK_4,
BLACK_5,
BKNOTE,
RISK,
ORGRISK,
CDDNOTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(KYCDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(KYCDT))='0' THEN NULL ELSE KYCDT END) AS KYCDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(KYCLDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(KYCLDT))='0' THEN NULL ELSE KYCLDT END) AS KYCLDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CDDDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CDDDT))='0' THEN NULL ELSE CDDDT END) AS CDDDT,
PNAME1,
PNAME2,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
