-- SQL for table: EDW_FXE_FADTR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRCNT' AS DATA_CHK_COL,
TRCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TRCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CORPNO' AS DATA_CHK_COL,
CORPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CORPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXAMT' AS DATA_CHK_COL,
TXAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(TXAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ADDAMT' AS DATA_CHK_COL,
ADDAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ADDAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SUBAMT' AS DATA_CHK_COL,
SUBAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(SUBAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NCHGAMT' AS DATA_CHK_COL,
NCHGAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NCHGAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CCHGAMT' AS DATA_CHK_COL,
CCHGAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CCHGAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGAMT' AS DATA_CHK_COL,
CHGAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SEQNO' AS DATA_CHK_COL,
SEQNO AS DATA_VAL,
SDG.UFN_NUMCHECK(SEQNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PCNT' AS DATA_CHK_COL,
PCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(PCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXE_FADTR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
YEAR,
APTYPE,
BRNO,
SRNO,
TRCNT,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
CIFKEY,
CORPNO,
ITNO,
FAX,
TXDAY,
ADVDAY,
ISUDAY,
EXPDAY,
PREDAY,
SHPDAY,
RCLDAY,
LOSDAY,
REPDAY,
SNDDAY,
RCVDAY,
SWFDAY,
TXAMT,
ADDAMT,
SUBAMT,
NCHGAMT,
CCHGAMT,
CHGAMT,
RECTYP,
LOSFG,
RCLFG,
PRECD,
CIFFG,
ADVCD,
SNDFG,
FAXFG,
SEQNO,
PCNT,
CHGFG,
GBRNO,
AUTO,
TLRNO,
BANO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(YEAR), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(YEAR))='0' THEN NULL ELSE YEAR END) AS YEAR,
APTYPE,
BRNO,
SRNO,
TRCNT,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
CIFKEY,
CORPNO,
ITNO,
FAX,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TXDAY))='0' THEN NULL ELSE TXDAY END) AS TXDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ADVDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ADVDAY))='0' THEN NULL ELSE ADVDAY END) AS ADVDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISUDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISUDAY))='0' THEN NULL ELSE ISUDAY END) AS ISUDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EXPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EXPDAY))='0' THEN NULL ELSE EXPDAY END) AS EXPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PREDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PREDAY))='0' THEN NULL ELSE PREDAY END) AS PREDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SHPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SHPDAY))='0' THEN NULL ELSE SHPDAY END) AS SHPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RCLDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RCLDAY))='0' THEN NULL ELSE RCLDAY END) AS RCLDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LOSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LOSDAY))='0' THEN NULL ELSE LOSDAY END) AS LOSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(REPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(REPDAY))='0' THEN NULL ELSE REPDAY END) AS REPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SNDDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SNDDAY))='0' THEN NULL ELSE SNDDAY END) AS SNDDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RCVDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RCVDAY))='0' THEN NULL ELSE RCVDAY END) AS RCVDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SWFDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SWFDAY))='0' THEN NULL ELSE SWFDAY END) AS SWFDAY,
TXAMT,
ADDAMT,
SUBAMT,
NCHGAMT,
CCHGAMT,
CHGAMT,
RECTYP,
LOSFG,
RCLFG,
PRECD,
CIFFG,
ADVCD,
SNDFG,
FAXFG,
SEQNO,
PCNT,
CHGFG,
GBRNO,
AUTO,
TLRNO,
BANO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
