-- SQL for table: EDW_PB_PBHMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IIRT' AS DATA_CHK_COL,
IIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(IIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'YDBAL' AS DATA_CHK_COL,
YDBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(YDBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LMBAL' AS DATA_CHK_COL,
LMBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(LMBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CTTBAL' AS DATA_CHK_COL,
CTTBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(CTTBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SLMT' AS DATA_CHK_COL,
SLMT AS DATA_VAL,
SDG.UFN_NUMCHECK(SLMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DAMT' AS DATA_CHK_COL,
DAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(DAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DCNT' AS DATA_CHK_COL,
DCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(DCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CAMT' AS DATA_CHK_COL,
CAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CCNT' AS DATA_CHK_COL,
CCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'EXPER' AS DATA_CHK_COL,
EXPER AS DATA_VAL,
SDG.UFN_NUMCHECK(EXPER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LIRT' AS DATA_CHK_COL,
LIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(LIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SLMT1' AS DATA_CHK_COL,
SLMT1 AS DATA_VAL,
SDG.UFN_NUMCHECK(SLMT1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SLMT2' AS DATA_CHK_COL,
SLMT2 AS DATA_VAL,
SDG.UFN_NUMCHECK(SLMT2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SINUM2' AS DATA_CHK_COL,
SINUM2 AS DATA_VAL,
SDG.UFN_NUMCHECK(SINUM2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_PB_PBHMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
YYMM,
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
TCHGCD,
CHGCD,
OPENH,
ACTCLS,
ACTMVO,
ACTMVI,
ACTSLP,
ACTSTP,
GPACT,
CDCREG,
CDCIVD,
UTFCD,
NOIBK,
OVACT,
U3VCD,
SHARID,
CURCD,
CHARCD,
IRTCD,
TAXCD,
IIRT,
BCODE,
EIDERR,
ENTPNO,
PIDERR,
PIDNO,
YDBAL,
LMBAL,
CTTBAL,
SLMT,
DAMT,
DCNT,
CAMT,
CCNT,
LASTDT,
OPDAY,
CLSDAY,
CSDAY,
CEDAY,
EXPERDAY,
EXPER,
BOOKFLG,
BOOKDAY,
GPFLAG,
GPFLAG1,
FLAG1,
FLAG2,
FLAG3,
FLAG4,
MMACD,
LIRT,
FLAG5,
RSLPDAY,
WADAY,
SBRNO,
SLMT1,
LIRTCD,
CMPENTPNO,
MANG,
PAYCYCLE,
FLAG7,
SLMT2,
SINUM2,
LSTDAY,
IRTSQ,
IRTYPE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(YYMM), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(YYMM))='0' THEN NULL ELSE YYMM END) AS YYMM,
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
TCHGCD,
CHGCD,
OPENH,
ACTCLS,
ACTMVO,
ACTMVI,
ACTSLP,
ACTSTP,
GPACT,
CDCREG,
CDCIVD,
UTFCD,
NOIBK,
OVACT,
U3VCD,
SHARID,
CURCD,
CHARCD,
IRTCD,
TAXCD,
IIRT,
BCODE,
EIDERR,
ENTPNO,
PIDERR,
PIDNO,
YDBAL,
LMBAL,
CTTBAL,
SLMT,
DAMT,
DCNT,
CAMT,
CCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPDAY))='0' THEN NULL ELSE OPDAY END) AS OPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLSDAY))='0' THEN NULL ELSE CLSDAY END) AS CLSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CSDAY))='0' THEN NULL ELSE CSDAY END) AS CSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CEDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CEDAY))='0' THEN NULL ELSE CEDAY END) AS CEDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EXPERDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EXPERDAY))='0' THEN NULL ELSE EXPERDAY END) AS EXPERDAY,
EXPER,
BOOKFLG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BOOKDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BOOKDAY))='0' THEN NULL ELSE BOOKDAY END) AS BOOKDAY,
GPFLAG,
GPFLAG1,
FLAG1,
FLAG2,
FLAG3,
FLAG4,
MMACD,
LIRT,
FLAG5,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RSLPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RSLPDAY))='0' THEN NULL ELSE RSLPDAY END) AS RSLPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(WADAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(WADAY))='0' THEN NULL ELSE WADAY END) AS WADAY,
SBRNO,
SLMT1,
LIRTCD,
CMPENTPNO,
MANG,
PAYCYCLE,
FLAG7,
SLMT2,
SINUM2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LSTDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LSTDAY))='0' THEN NULL ELSE LSTDAY END) AS LSTDAY,
IRTSQ,
IRTYPE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
