-- SQL for table: EDW_LN_AB41
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CONAMT' AS DATA_CHK_COL,
CONAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CONAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTLMT' AS DATA_CHK_COL,
NTLMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NTLMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL' AS DATA_CHK_COL,
BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTBAL' AS DATA_CHK_COL,
NTBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NTBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CMAPAMT' AS DATA_CHK_COL,
CMAPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CMAPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SGAPER' AS DATA_CHK_COL,
SGAPER AS DATA_VAL,
SDG.UFN_NUMCHECK(SGAPER) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ISCOD' AS DATA_CHK_COL,
ISCOD AS DATA_VAL,
SDG.UFN_NUMCHECK(ISCOD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NCODE' AS DATA_CHK_COL,
NCODE AS DATA_VAL,
SDG.UFN_NUMCHECK(NCODE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CACTNO' AS DATA_CHK_COL,
CACTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CACTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MNCNT' AS DATA_CHK_COL,
MNCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(MNCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SORTCD' AS DATA_CHK_COL,
SORTCD AS DATA_VAL,
SDG.UFN_NUMCHECK(SORTCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FILLER2' AS DATA_CHK_COL,
FILLER2 AS DATA_VAL,
SDG.UFN_NUMCHECK(FILLER2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AREA' AS DATA_CHK_COL,
AREA AS DATA_VAL,
SDG.UFN_NUMCHECK(AREA) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR' AS DATA_CHK_COL,
IXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPIXPR' AS DATA_CHK_COL,
SPIXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(SPIXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PERCENT' AS DATA_CHK_COL,
PERCENT AS DATA_VAL,
SDG.UFN_NUMCHECK(PERCENT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FITDIV' AS DATA_CHK_COL,
FITDIV AS DATA_VAL,
SDG.UFN_NUMCHECK(FITDIV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRURT' AS DATA_CHK_COL,
TRURT AS DATA_VAL,
SDG.UFN_NUMCHECK(TRURT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FITIRT' AS DATA_CHK_COL,
FITIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(FITIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APAMT' AS DATA_CHK_COL,
APAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(APAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BLCDT' AS DATA_CHK_COL,
BLCDT AS DATA_VAL,
SDG.UFN_NUMCHECK(BLCDT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DUAMT' AS DATA_CHK_COL,
DUAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(DUAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RVAMT' AS DATA_CHK_COL,
RVAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RVAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RVINT' AS DATA_CHK_COL,
RVINT AS DATA_VAL,
SDG.UFN_NUMCHECK(RVINT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RVFEE' AS DATA_CHK_COL,
RVFEE AS DATA_VAL,
SDG.UFN_NUMCHECK(RVFEE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AB41_3000' AS DATA_CHK_COL,
AB41_3000 AS DATA_VAL,
SDG.UFN_NUMCHECK(AB41_3000) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APPRSV' AS DATA_CHK_COL,
APPRSV AS DATA_VAL,
SDG.UFN_NUMCHECK(APPRSV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SSAPNO' AS DATA_CHK_COL,
SSAPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(SSAPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'GPAMTB' AS DATA_CHK_COL,
GPAMTB AS DATA_VAL,
SDG.UFN_NUMCHECK(GPAMTB) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DUINT' AS DATA_CHK_COL,
DUINT AS DATA_VAL,
SDG.UFN_NUMCHECK(DUINT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ASST2' AS DATA_CHK_COL,
ASST2 AS DATA_VAL,
SDG.UFN_NUMCHECK(ASST2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ASST3' AS DATA_CHK_COL,
ASST3 AS DATA_VAL,
SDG.UFN_NUMCHECK(ASST3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ASST4' AS DATA_CHK_COL,
ASST4 AS DATA_VAL,
SDG.UFN_NUMCHECK(ASST4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ASST5' AS DATA_CHK_COL,
ASST5 AS DATA_VAL,
SDG.UFN_NUMCHECK(ASST5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CPSTAMT' AS DATA_CHK_COL,
CPSTAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CPSTAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IMPSBLR' AS DATA_CHK_COL,
IMPSBLR AS DATA_VAL,
SDG.UFN_NUMCHECK(IMPSBLR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PER2' AS DATA_CHK_COL,
PER2 AS DATA_VAL,
SDG.UFN_NUMCHECK(PER2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UNLOSS' AS DATA_CHK_COL,
UNLOSS AS DATA_VAL,
SDG.UFN_NUMCHECK(UNLOSS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_LN_AB41
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BRNO,
SAPNO,
CURCD,
ACTNO,
ENTPNO,
EIDERR,
"6MONS-FLAG",
PIDNO,
PIDERR,
LNCUR,
CONAMT,
NTLMT,
BAL,
NTBAL,
CMAPAMT,
BCODE,
CHARCD,
APKIND,
"USAGE",
MANG,
CPSTCD,
CSDATE,
CEDATE,
ODDATE,
SCOP,
SGAPER,
SGAID,
TFBRNO,
BSID,
BSCD,
ISCOD,
TFCD,
NCODE,
PRDATE,
IDATE,
COMPROMISE,
FINA,
SCHCD,
CACTNO,
SQNO,
SDT,
CHGCD,
LBMNTR,
FAPNO,
FAPNOS,
BASE,
R0401CD,
MNCNT,
ODCD,
ODCD2,
AODCD,
BODCD,
SORTCD,
FILLER2,
IRDT,
IRND,
AREA,
IRID,
IXPR,
IXID,
IXND,
SPIXPR,
SPIXND,
PERCENT,
FITDIV,
PLCKIND,
TRUCD,
TRCSDATE,
TRAREA,
TRURT,
SHARID,
CYCLE,
FITIRT,
CONTYP,
IREVOCB,
APDATE,
APAMT,
EDAY,
IDAY,
BLCDT,
EDUSNO,
BKIND,
KEY,
OBUENT,
DUAMT,
RVAMT,
RVINT,
RVFEE,
AB41_3000,
BADCD,
CMPTYPE,
NEWCD,
APPRSV,
CPTYP,
CPCD,
SSAPNO,
IRCD,
PAYDT,
ODPAYDT,
GPAMTB,
DUINT,
ASST2,
ASST3,
ASST4,
ASST5,
CPSTAMT,
IMPSBLR,
NCPSTCD,
PER2,
NONUSE,
BKIND2,
CTLSUB,
UNLOSS,
CNGUAR,
CNFLG,
CNITEMCD,
CNBCODE,
CNBSCD,
FILLER3,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO,
SAPNO,
CURCD,
ACTNO,
ENTPNO,
EIDERR,
"6MONS-FLAG",
PIDNO,
PIDERR,
LNCUR,
CONAMT,
NTLMT,
BAL,
NTBAL,
CMAPAMT,
BCODE,
CHARCD,
APKIND,
"USAGE",
MANG,
CPSTCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CSDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CSDATE))='0' THEN NULL ELSE CSDATE END) AS CSDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CEDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CEDATE))='0' THEN NULL ELSE CEDATE END) AS CEDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ODDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ODDATE))='0' THEN NULL ELSE ODDATE END) AS ODDATE,
SCOP,
SGAPER,
SGAID,
TFBRNO,
BSID,
BSCD,
ISCOD,
TFCD,
NCODE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRDATE))='0' THEN NULL ELSE PRDATE END) AS PRDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IDATE))='0' THEN NULL ELSE IDATE END) AS IDATE,
COMPROMISE,
FINA,
SCHCD,
CACTNO,
SQNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SDT))='0' THEN NULL ELSE SDT END) AS SDT,
CHGCD,
LBMNTR,
FAPNO,
FAPNOS,
BASE,
R0401CD,
MNCNT,
ODCD,
ODCD2,
AODCD,
BODCD,
SORTCD,
FILLER2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IRDT))='0' THEN NULL ELSE IRDT END) AS IRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IRND), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IRND))='0' THEN NULL ELSE IRND END) AS IRND,
AREA,
IRID,
IXPR,
IXID,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IXND), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IXND))='0' THEN NULL ELSE IXND END) AS IXND,
SPIXPR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SPIXND), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SPIXND))='0' THEN NULL ELSE SPIXND END) AS SPIXND,
PERCENT,
FITDIV,
PLCKIND,
TRUCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TRCSDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TRCSDATE))='0' THEN NULL ELSE TRCSDATE END) AS TRCSDATE,
TRAREA,
TRURT,
SHARID,
CYCLE,
FITIRT,
CONTYP,
IREVOCB,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APDATE))='0' THEN NULL ELSE APDATE END) AS APDATE,
APAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY))='0' THEN NULL ELSE EDAY END) AS EDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IDAY))='0' THEN NULL ELSE IDAY END) AS IDAY,
BLCDT,
EDUSNO,
BKIND,
KEY,
OBUENT,
DUAMT,
RVAMT,
RVINT,
RVFEE,
AB41_3000,
BADCD,
CMPTYPE,
NEWCD,
APPRSV,
CPTYP,
CPCD,
SSAPNO,
IRCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PAYDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PAYDT))='0' THEN NULL ELSE PAYDT END) AS PAYDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ODPAYDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ODPAYDT))='0' THEN NULL ELSE ODPAYDT END) AS ODPAYDT,
GPAMTB,
DUINT,
ASST2,
ASST3,
ASST4,
ASST5,
CPSTAMT,
IMPSBLR,
NCPSTCD,
PER2,
NONUSE,
BKIND2,
CTLSUB,
UNLOSS,
CNGUAR,
CNFLG,
CNITEMCD,
CNBCODE,
CNBSCD,
FILLER3,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
