-- SQL for table: EDW_NCARD_ACCTBOOK
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BEG_BAL' AS DATA_CHK_COL,
BEG_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(BEG_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BEG_DUE' AS DATA_CHK_COL,
BEG_DUE AS DATA_VAL,
SDG.UFN_NUMCHECK(BEG_DUE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CURR_BAL' AS DATA_CHK_COL,
CURR_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(CURR_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OVER_PMT' AS DATA_CHK_COL,
OVER_PMT AS DATA_VAL,
SDG.UFN_NUMCHECK(OVER_PMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PMT_CTD' AS DATA_CHK_COL,
PMT_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PMT_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DB_CTD' AS DATA_CHK_COL,
DB_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(DB_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CR_CTD' AS DATA_CHK_COL,
CR_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(CR_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_CTD' AS DATA_CHK_COL,
PRIN_1_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_CTD' AS DATA_CHK_COL,
PRIN_2_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_CTD' AS DATA_CHK_COL,
PRIN_3_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_CTD' AS DATA_CHK_COL,
PRIN_4_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_CTD' AS DATA_CHK_COL,
PRIN_5_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_CTD' AS DATA_CHK_COL,
INT_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_CTD' AS DATA_CHK_COL,
LC_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_CTD' AS DATA_CHK_COL,
CASH_FEE_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_CTD' AS DATA_CHK_COL,
MEMBER_FEE_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_CTD' AS DATA_CHK_COL,
SERVICE_FEE_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_CTD' AS DATA_CHK_COL,
USER_FEE_1_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_CTD' AS DATA_CHK_COL,
USER_FEE_2_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_CTD' AS DATA_CHK_COL,
USER_FEE_3_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_CTD' AS DATA_CHK_COL,
USER_FEE_4_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_CTD' AS DATA_CHK_COL,
USER_FEE_5_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_CTD' AS DATA_CHK_COL,
USER_FEE_6_CTD AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_CTD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_BILL' AS DATA_CHK_COL,
PRIN_1_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_BILL' AS DATA_CHK_COL,
PRIN_2_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_BILL' AS DATA_CHK_COL,
PRIN_3_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_BILL' AS DATA_CHK_COL,
PRIN_4_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_BILL' AS DATA_CHK_COL,
PRIN_5_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_BILL' AS DATA_CHK_COL,
INT_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_BILL' AS DATA_CHK_COL,
LC_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_BILL' AS DATA_CHK_COL,
CASH_FEE_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_BILL' AS DATA_CHK_COL,
MEMBER_FEE_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_BILL' AS DATA_CHK_COL,
SERVICE_FEE_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_BILL' AS DATA_CHK_COL,
USER_FEE_1_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_BILL' AS DATA_CHK_COL,
USER_FEE_2_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_BILL' AS DATA_CHK_COL,
USER_FEE_3_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_BILL' AS DATA_CHK_COL,
USER_FEE_4_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_BILL' AS DATA_CHK_COL,
USER_FEE_5_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_BILL' AS DATA_CHK_COL,
USER_FEE_6_BILL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_BILL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_COLL' AS DATA_CHK_COL,
PRIN_1_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_COLL' AS DATA_CHK_COL,
PRIN_2_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_COLL' AS DATA_CHK_COL,
PRIN_3_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_COLL' AS DATA_CHK_COL,
PRIN_4_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_COLL' AS DATA_CHK_COL,
PRIN_5_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_COLL' AS DATA_CHK_COL,
INT_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_COLL' AS DATA_CHK_COL,
LC_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_COLL' AS DATA_CHK_COL,
CASH_FEE_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_COLL' AS DATA_CHK_COL,
MEMBER_FEE_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_COLL' AS DATA_CHK_COL,
SERVICE_FEE_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_COLL' AS DATA_CHK_COL,
USER_FEE_1_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_COLL' AS DATA_CHK_COL,
USER_FEE_2_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_COLL' AS DATA_CHK_COL,
USER_FEE_3_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_COLL' AS DATA_CHK_COL,
USER_FEE_4_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_COLL' AS DATA_CHK_COL,
USER_FEE_5_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_COLL' AS DATA_CHK_COL,
USER_FEE_6_COLL AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_COLL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_CHGOFF' AS DATA_CHK_COL,
PRIN_1_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_CHGOFF' AS DATA_CHK_COL,
PRIN_2_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_CHGOFF' AS DATA_CHK_COL,
PRIN_3_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_CHGOFF' AS DATA_CHK_COL,
PRIN_4_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_CHGOFF' AS DATA_CHK_COL,
PRIN_5_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INT_CHGOFF' AS DATA_CHK_COL,
INT_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(INT_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_CHGOFF' AS DATA_CHK_COL,
LC_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH_FEE_CHGOFF' AS DATA_CHK_COL,
CASH_FEE_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH_FEE_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMBER_FEE_CHGOFF' AS DATA_CHK_COL,
MEMBER_FEE_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMBER_FEE_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SERVICE_FEE_CHGOFF' AS DATA_CHK_COL,
SERVICE_FEE_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(SERVICE_FEE_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_1_CHGOFF' AS DATA_CHK_COL,
USER_FEE_1_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_1_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_2_CHGOFF' AS DATA_CHK_COL,
USER_FEE_2_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_2_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_3_CHGOFF' AS DATA_CHK_COL,
USER_FEE_3_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_3_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_4_CHGOFF' AS DATA_CHK_COL,
USER_FEE_4_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_4_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_5_CHGOFF' AS DATA_CHK_COL,
USER_FEE_5_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_5_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_FEE_6_CHGOFF' AS DATA_CHK_COL,
USER_FEE_6_CHGOFF AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_FEE_6_CHGOFF) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_1_REVOLVING' AS DATA_CHK_COL,
PRIN_1_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_1_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_2_REVOLVING' AS DATA_CHK_COL,
PRIN_2_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_2_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_3_REVOLVING' AS DATA_CHK_COL,
PRIN_3_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_3_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_4_REVOLVING' AS DATA_CHK_COL,
PRIN_4_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_4_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRIN_5_REVOLVING' AS DATA_CHK_COL,
PRIN_5_REVOLVING AS DATA_VAL,
SDG.UFN_NUMCHECK(PRIN_5_REVOLVING) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'STMT_BAL' AS DATA_CHK_COL,
STMT_BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(STMT_BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'STMT_DUE' AS DATA_CHK_COL,
STMT_DUE AS DATA_VAL,
SDG.UFN_NUMCHECK(STMT_DUE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_1' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_2' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_3' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_4' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_5' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_6' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_7' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_8' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_9' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_10' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_11' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DELQ_BUCKET_AMT_12' AS DATA_CHK_COL,
DELQ_BUCKET_AMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(DELQ_BUCKET_AMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_1' AS DATA_CHK_COL,
BAL_BUCKET_AMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_2' AS DATA_CHK_COL,
BAL_BUCKET_AMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_3' AS DATA_CHK_COL,
BAL_BUCKET_AMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_4' AS DATA_CHK_COL,
BAL_BUCKET_AMT_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_5' AS DATA_CHK_COL,
BAL_BUCKET_AMT_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_6' AS DATA_CHK_COL,
BAL_BUCKET_AMT_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_7' AS DATA_CHK_COL,
BAL_BUCKET_AMT_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_8' AS DATA_CHK_COL,
BAL_BUCKET_AMT_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_9' AS DATA_CHK_COL,
BAL_BUCKET_AMT_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_10' AS DATA_CHK_COL,
BAL_BUCKET_AMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_11' AS DATA_CHK_COL,
BAL_BUCKET_AMT_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL_BUCKET_AMT_12' AS DATA_CHK_COL,
BAL_BUCKET_AMT_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL_BUCKET_AMT_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LC_CHG_CNT' AS DATA_CHK_COL,
LC_CHG_CNT AS DATA_VAL,
SDG.UFN_NUMCHECK(LC_CHG_CNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_NCARD_ACCTBOOK
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
BEG_BAL,
BEG_DUE,
CURR_BAL,
OVER_PMT,
PMT_CTD,
DB_CTD,
CR_CTD,
PRIN_1_CTD,
PRIN_2_CTD,
PRIN_3_CTD,
PRIN_4_CTD,
PRIN_5_CTD,
INT_CTD,
LC_CTD,
CASH_FEE_CTD,
MEMBER_FEE_CTD,
SERVICE_FEE_CTD,
USER_FEE_1_CTD,
USER_FEE_2_CTD,
USER_FEE_3_CTD,
USER_FEE_4_CTD,
USER_FEE_5_CTD,
USER_FEE_6_CTD,
PRIN_1_BILL,
PRIN_2_BILL,
PRIN_3_BILL,
PRIN_4_BILL,
PRIN_5_BILL,
INT_BILL,
LC_BILL,
CASH_FEE_BILL,
MEMBER_FEE_BILL,
SERVICE_FEE_BILL,
USER_FEE_1_BILL,
USER_FEE_2_BILL,
USER_FEE_3_BILL,
USER_FEE_4_BILL,
USER_FEE_5_BILL,
USER_FEE_6_BILL,
PRIN_1_COLL,
PRIN_2_COLL,
PRIN_3_COLL,
PRIN_4_COLL,
PRIN_5_COLL,
INT_COLL,
LC_COLL,
CASH_FEE_COLL,
MEMBER_FEE_COLL,
SERVICE_FEE_COLL,
USER_FEE_1_COLL,
USER_FEE_2_COLL,
USER_FEE_3_COLL,
USER_FEE_4_COLL,
USER_FEE_5_COLL,
USER_FEE_6_COLL,
PRIN_1_CHGOFF,
PRIN_2_CHGOFF,
PRIN_3_CHGOFF,
PRIN_4_CHGOFF,
PRIN_5_CHGOFF,
INT_CHGOFF,
LC_CHGOFF,
CASH_FEE_CHGOFF,
MEMBER_FEE_CHGOFF,
SERVICE_FEE_CHGOFF,
USER_FEE_1_CHGOFF,
USER_FEE_2_CHGOFF,
USER_FEE_3_CHGOFF,
USER_FEE_4_CHGOFF,
USER_FEE_5_CHGOFF,
USER_FEE_6_CHGOFF,
PRIN_1_REVOLVING,
PRIN_2_REVOLVING,
PRIN_3_REVOLVING,
PRIN_4_REVOLVING,
PRIN_5_REVOLVING,
STMT_BAL,
STMT_DUE,
DUE_DTE,
GRACE_DTE,
LATE_DTE,
PAY_IN_FULL,
PAY_IN_MINI,
DELQ_STATUS_HIST,
PMT_STATUS_HIST,
STMT_DATE,
DELQ_BUCKET_AMT_1,
DELQ_BUCKET_AMT_2,
DELQ_BUCKET_AMT_3,
DELQ_BUCKET_AMT_4,
DELQ_BUCKET_AMT_5,
DELQ_BUCKET_AMT_6,
DELQ_BUCKET_AMT_7,
DELQ_BUCKET_AMT_8,
DELQ_BUCKET_AMT_9,
DELQ_BUCKET_AMT_10,
DELQ_BUCKET_AMT_11,
DELQ_BUCKET_AMT_12,
BAL_BUCKET_AMT_1,
BAL_BUCKET_AMT_2,
BAL_BUCKET_AMT_3,
BAL_BUCKET_AMT_4,
BAL_BUCKET_AMT_5,
BAL_BUCKET_AMT_6,
BAL_BUCKET_AMT_7,
BAL_BUCKET_AMT_8,
BAL_BUCKET_AMT_9,
BAL_BUCKET_AMT_10,
BAL_BUCKET_AMT_11,
BAL_BUCKET_AMT_12,
PAYOFF_DTE,
LC_CHG_CNT,
M0_STMT_DTE,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
BEG_BAL,
BEG_DUE,
CURR_BAL,
OVER_PMT,
PMT_CTD,
DB_CTD,
CR_CTD,
PRIN_1_CTD,
PRIN_2_CTD,
PRIN_3_CTD,
PRIN_4_CTD,
PRIN_5_CTD,
INT_CTD,
LC_CTD,
CASH_FEE_CTD,
MEMBER_FEE_CTD,
SERVICE_FEE_CTD,
USER_FEE_1_CTD,
USER_FEE_2_CTD,
USER_FEE_3_CTD,
USER_FEE_4_CTD,
USER_FEE_5_CTD,
USER_FEE_6_CTD,
PRIN_1_BILL,
PRIN_2_BILL,
PRIN_3_BILL,
PRIN_4_BILL,
PRIN_5_BILL,
INT_BILL,
LC_BILL,
CASH_FEE_BILL,
MEMBER_FEE_BILL,
SERVICE_FEE_BILL,
USER_FEE_1_BILL,
USER_FEE_2_BILL,
USER_FEE_3_BILL,
USER_FEE_4_BILL,
USER_FEE_5_BILL,
USER_FEE_6_BILL,
PRIN_1_COLL,
PRIN_2_COLL,
PRIN_3_COLL,
PRIN_4_COLL,
PRIN_5_COLL,
INT_COLL,
LC_COLL,
CASH_FEE_COLL,
MEMBER_FEE_COLL,
SERVICE_FEE_COLL,
USER_FEE_1_COLL,
USER_FEE_2_COLL,
USER_FEE_3_COLL,
USER_FEE_4_COLL,
USER_FEE_5_COLL,
USER_FEE_6_COLL,
PRIN_1_CHGOFF,
PRIN_2_CHGOFF,
PRIN_3_CHGOFF,
PRIN_4_CHGOFF,
PRIN_5_CHGOFF,
INT_CHGOFF,
LC_CHGOFF,
CASH_FEE_CHGOFF,
MEMBER_FEE_CHGOFF,
SERVICE_FEE_CHGOFF,
USER_FEE_1_CHGOFF,
USER_FEE_2_CHGOFF,
USER_FEE_3_CHGOFF,
USER_FEE_4_CHGOFF,
USER_FEE_5_CHGOFF,
USER_FEE_6_CHGOFF,
PRIN_1_REVOLVING,
PRIN_2_REVOLVING,
PRIN_3_REVOLVING,
PRIN_4_REVOLVING,
PRIN_5_REVOLVING,
STMT_BAL,
STMT_DUE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DUE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DUE_DTE))='0' THEN NULL ELSE DUE_DTE END) AS DUE_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GRACE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GRACE_DTE))='0' THEN NULL ELSE GRACE_DTE END) AS GRACE_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LATE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LATE_DTE))='0' THEN NULL ELSE LATE_DTE END) AS LATE_DTE,
PAY_IN_FULL,
PAY_IN_MINI,
DELQ_STATUS_HIST,
PMT_STATUS_HIST,
STMT_DATE,
DELQ_BUCKET_AMT_1,
DELQ_BUCKET_AMT_2,
DELQ_BUCKET_AMT_3,
DELQ_BUCKET_AMT_4,
DELQ_BUCKET_AMT_5,
DELQ_BUCKET_AMT_6,
DELQ_BUCKET_AMT_7,
DELQ_BUCKET_AMT_8,
DELQ_BUCKET_AMT_9,
DELQ_BUCKET_AMT_10,
DELQ_BUCKET_AMT_11,
DELQ_BUCKET_AMT_12,
BAL_BUCKET_AMT_1,
BAL_BUCKET_AMT_2,
BAL_BUCKET_AMT_3,
BAL_BUCKET_AMT_4,
BAL_BUCKET_AMT_5,
BAL_BUCKET_AMT_6,
BAL_BUCKET_AMT_7,
BAL_BUCKET_AMT_8,
BAL_BUCKET_AMT_9,
BAL_BUCKET_AMT_10,
BAL_BUCKET_AMT_11,
BAL_BUCKET_AMT_12,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PAYOFF_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PAYOFF_DTE))='0' THEN NULL ELSE PAYOFF_DTE END) AS PAYOFF_DTE,
LC_CHG_CNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(M0_STMT_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(M0_STMT_DTE))='0' THEN NULL ELSE M0_STMT_DTE END) AS M0_STMT_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MNT_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MNT_DT))='0' THEN NULL ELSE MNT_DT END) AS MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
