-- SQL for table: EDW_RM_RTMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'REMSNO' AS DATA_CHK_COL,
REMSNO AS DATA_VAL,
SDG.UFN_NUMCHECK(REMSNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHARGE' AS DATA_CHK_COL,
CHARGE AS DATA_VAL,
SDG.UFN_NUMCHECK(CHARGE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'REMAMT' AS DATA_CHK_COL,
REMAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(REMAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TELTIM' AS DATA_CHK_COL,
TELTIM AS DATA_VAL,
SDG.UFN_NUMCHECK(TELTIM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'POSQNO' AS DATA_CHK_COL,
POSQNO AS DATA_VAL,
SDG.UFN_NUMCHECK(POSQNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ISN' AS DATA_CHK_COL,
ISN AS DATA_VAL,
SDG.UFN_NUMCHECK(ISN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OSN' AS DATA_CHK_COL,
OSN AS DATA_VAL,
SDG.UFN_NUMCHECK(OSN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BHNO' AS DATA_CHK_COL,
BHNO AS DATA_VAL,
SDG.UFN_NUMCHECK(BHNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CNT' AS DATA_CHK_COL,
CNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TLXNO' AS DATA_CHK_COL,
TLXNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TLXNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FRTSNO' AS DATA_CHK_COL,
FRTSNO AS DATA_VAL,
SDG.UFN_NUMCHECK(FRTSNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CBNO' AS DATA_CHK_COL,
CBNO AS DATA_VAL,
SDG.UFN_NUMCHECK(CBNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRTSEQ' AS DATA_CHK_COL,
PRTSEQ AS DATA_VAL,
SDG.UFN_NUMCHECK(PRTSEQ) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FTXTNO' AS DATA_CHK_COL,
FTXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(FTXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MEMO' AS DATA_CHK_COL,
MEMO AS DATA_VAL,
SDG.UFN_NUMCHECK(MEMO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CASH' AS DATA_CHK_COL,
CASH AS DATA_VAL,
SDG.UFN_NUMCHECK(CASH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TOTAMT' AS DATA_CHK_COL,
TOTAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(TOTAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SFEE' AS DATA_CHK_COL,
SFEE AS DATA_VAL,
SDG.UFN_NUMCHECK(SFEE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'OLDFRTSNO' AS DATA_CHK_COL,
OLDFRTSNO AS DATA_VAL,
SDG.UFN_NUMCHECK(OLDFRTSNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RTBH4' AS DATA_CHK_COL,
RTBH4 AS DATA_VAL,
SDG.UFN_NUMCHECK(RTBH4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'"TIME"' AS DATA_CHK_COL,
"TIME" AS DATA_VAL,
SDG.UFN_NUMCHECK("TIME") AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO' AS DATA_CHK_COL,
TXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_RM_RTMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
REMDAY,
RECBK,
TRFBK,
REMBK,
REMTYP,
REMSNO,
CHARGE,
RECACT,
REMAMT,
TELTIM,
POSQNO,
TSTKEY,
REMNAM,
RECADR,
REMNM,
REMARK,
RCRJDY,
DWLCD,
BREMCD,
HOLD,
DECPCD,
ISN,
OSN,
POSTDT,
RECTEL,
ENTPNO,
RJCD,
RJID,
RJNO,
ENTDAY,
DLCDY,
BHNO,
CNT,
MCAT,
LSNTTM,
TLXNO,
FRTSNO,
TXTYPE,
PBRNO,
CKIND,
CBNO,
YEAR,
RTBH1,
RTBH2,
RTBH3,
INTERCD,
EDIFLG,
ACTINQ,
PECHCD,
BHPRT,
FLAG,
PRTSEQ,
FTXTNO,
KIND,
RV,
SUBTYPE,
TRMSG,
MEMO,
TLRNO,
CASH,
TOTAMT,
OPCENTER,
SFEE,
FEETYP,
OLDREMTYP,
OLDFRTSNO,
ACKFLG,
REMID,
RTBH4,
FLAG1,
R1001TLRNO,
"TIME",
ERRCD,
TXTNO,
AGENTID,
AGENTNM,
HOLDERID,
HOLDER,
R20AGTID,
R20AGENT,
AMLONOFF,
REFID,
FTPONOFF,
FTPREFID,
FTPREFID2,
REMRESULT,
RECRESULT,
AGTRESULT,
HLDRESULT,
AGTRESULT2,
EDITYPE,
BOTCUS,
REMKEY,
TRFKEY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(REMDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(REMDAY))='0' THEN NULL ELSE REMDAY END) AS REMDAY,
RECBK,
TRFBK,
REMBK,
REMTYP,
REMSNO,
CHARGE,
RECACT,
REMAMT,
TELTIM,
POSQNO,
TSTKEY,
REMNAM,
RECADR,
REMNM,
REMARK,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RCRJDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RCRJDY))='0' THEN NULL ELSE RCRJDY END) AS RCRJDY,
DWLCD,
BREMCD,
HOLD,
DECPCD,
ISN,
OSN,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(POSTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(POSTDT))='0' THEN NULL ELSE POSTDT END) AS POSTDT,
RECTEL,
ENTPNO,
RJCD,
RJID,
RJNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ENTDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ENTDAY))='0' THEN NULL ELSE ENTDAY END) AS ENTDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DLCDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DLCDY))='0' THEN NULL ELSE DLCDY END) AS DLCDY,
BHNO,
CNT,
MCAT,
LSNTTM,
TLXNO,
FRTSNO,
TXTYPE,
PBRNO,
CKIND,
CBNO,
YEAR,
RTBH1,
RTBH2,
RTBH3,
INTERCD,
EDIFLG,
ACTINQ,
PECHCD,
BHPRT,
FLAG,
PRTSEQ,
FTXTNO,
KIND,
RV,
SUBTYPE,
TRMSG,
MEMO,
TLRNO,
CASH,
TOTAMT,
OPCENTER,
SFEE,
FEETYP,
OLDREMTYP,
OLDFRTSNO,
ACKFLG,
REMID,
RTBH4,
FLAG1,
R1001TLRNO,
"TIME",
ERRCD,
TXTNO,
AGENTID,
AGENTNM,
HOLDERID,
HOLDER,
R20AGTID,
R20AGENT,
AMLONOFF,
REFID,
FTPONOFF,
FTPREFID,
FTPREFID2,
REMRESULT,
RECRESULT,
AGTRESULT,
HLDRESULT,
AGTRESULT2,
EDITYPE,
BOTCUS,
REMKEY,
TRFKEY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
