-- SQL for table: EDW_AROBO_IPMSETRBL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
RBL_LOG_ID,
CUS_CODE,
IPMSET_CODE,
ORDER_DATE,
TRAN_STATUS,
RBL_TYPE_CD,
DATA_DATE,
RBL_DUE_DATE,
ADJ_REASON,
ADJ_DESC,
RANK_CODE,
PREFERENCE_CODE,
EFFECTIVE_YN,
ADJ_TYPE_CODE,
ORG_RANK_CODE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
RBL_LOG_ID,
CUS_CODE,
IPMSET_CODE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ORDER_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ORDER_DATE))='0' THEN NULL ELSE ORDER_DATE END) AS ORDER_DATE,
TRAN_STATUS,
RBL_TYPE_CD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATA_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATA_DATE))='0' THEN NULL ELSE DATA_DATE END) AS DATA_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RBL_DUE_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RBL_DUE_DATE))='0' THEN NULL ELSE RBL_DUE_DATE END) AS RBL_DUE_DATE,
ADJ_REASON,
ADJ_DESC,
RANK_CODE,
PREFERENCE_CODE,
EFFECTIVE_YN,
ADJ_TYPE_CODE,
ORG_RANK_CODE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
