-- SQL for table: EDW_GL_GLOTCMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SEQNO' AS DATA_CHK_COL,
SEQNO AS DATA_VAL,
SDG.UFN_NUMCHECK(SEQNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DEQTYT' AS DATA_CHK_COL,
DEQTYT AS DATA_VAL,
SDG.UFN_NUMCHECK(DEQTYT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DEGRMT' AS DATA_CHK_COL,
DEGRMT AS DATA_VAL,
SDG.UFN_NUMCHECK(DEGRMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DIFFAMT' AS DATA_CHK_COL,
DIFFAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(DIFFAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHARGE' AS DATA_CHK_COL,
CHARGE AS DATA_VAL,
SDG.UFN_NUMCHECK(CHARGE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_GL_GLOTCMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
TDCCACT,
CIFKEY,
APLDAY,
SEQNO,
BRNO,
LSTKNO,
CTLBRNO,
STATUS,
DUMPFLG,
DEQTYT,
DEGRMT,
NAME,
TEL,
ZIP1,
ZIP2,
ADDR,
CREDAY,
DESDAY,
DEEDAY,
BLKDAY,
UNBLKDAY,
DEDAY,
CLSDAY,
LOSDAY,
DIFFAMT,
CHARGE,
LTXDAY,
TLRNO,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
TDCCACT,
CIFKEY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APLDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APLDAY))='0' THEN NULL ELSE APLDAY END) AS APLDAY,
SEQNO,
BRNO,
LSTKNO,
CTLBRNO,
STATUS,
DUMPFLG,
DEQTYT,
DEGRMT,
NAME,
TEL,
ZIP1,
ZIP2,
ADDR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREDAY))='0' THEN NULL ELSE CREDAY END) AS CREDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DESDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DESDAY))='0' THEN NULL ELSE DESDAY END) AS DESDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEEDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEEDAY))='0' THEN NULL ELSE DEEDAY END) AS DEEDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BLKDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BLKDAY))='0' THEN NULL ELSE BLKDAY END) AS BLKDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(UNBLKDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(UNBLKDAY))='0' THEN NULL ELSE UNBLKDAY END) AS UNBLKDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DEDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DEDAY))='0' THEN NULL ELSE DEDAY END) AS DEDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLSDAY))='0' THEN NULL ELSE CLSDAY END) AS CLSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LOSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LOSDAY))='0' THEN NULL ELSE LOSDAY END) AS LOSDAY,
DIFFAMT,
CHARGE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTXDAY))='0' THEN NULL ELSE LTXDAY END) AS LTXDAY,
TLRNO,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
