-- SQL for table: EDW_ZX_FCFPRD
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BAL' AS DATA_CHK_COL,
BAL AS DATA_VAL,
SDG.UFN_NUMCHECK(BAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTBAL' AS DATA_CHK_COL,
NTBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NTBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USBAL' AS DATA_CHK_COL,
USBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(USBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AVGBAL' AS DATA_CHK_COL,
AVGBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(AVGBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTAVGBAL' AS DATA_CHK_COL,
NTAVGBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NTAVGBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NETRT' AS DATA_CHK_COL,
NETRT AS DATA_VAL,
SDG.UFN_NUMCHECK(NETRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AMTPCD' AS DATA_CHK_COL,
AMTPCD AS DATA_VAL,
SDG.UFN_NUMCHECK(AMTPCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PAYBAL' AS DATA_CHK_COL,
PAYBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(PAYBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACCBAL' AS DATA_CHK_COL,
ACCBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ACCBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INTBAL' AS DATA_CHK_COL,
INTBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(INTBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTINTBAL' AS DATA_CHK_COL,
NTINTBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NTINTBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AMRTTM' AS DATA_CHK_COL,
AMRTTM AS DATA_VAL,
SDG.UFN_NUMCHECK(AMRTTM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MARGIN' AS DATA_CHK_COL,
MARGIN AS DATA_VAL,
SDG.UFN_NUMCHECK(MARGIN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHARCD' AS DATA_CHK_COL,
CHARCD AS DATA_VAL,
SDG.UFN_NUMCHECK(CHARCD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ACAPNO' AS DATA_CHK_COL,
ACAPNO AS DATA_VAL,
SDG.UFN_NUMCHECK(ACAPNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CGTRT' AS DATA_CHK_COL,
CGTRT AS DATA_VAL,
SDG.UFN_NUMCHECK(CGTRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INBAL' AS DATA_CHK_COL,
INBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(INBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORBAL' AS DATA_CHK_COL,
ORBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ORBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORPAYBAL' AS DATA_CHK_COL,
ORPAYBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(ORPAYBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_ZX_FCFPRD
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
GENDY,
ACTNO,
ACNO,
ISDAY,
EDAY,
BAL,
NTBAL,
USBAL,
AVGBAL,
NTAVGBAL,
NETRT,
IRTCD,
SWFNAM,
AMTPCD,
PAYBAL,
LPAYDT,
NPAYDT,
PMTFREQ,
PMTFREM,
ACCD,
ACCBAL,
LRPAYDT,
NRPAYDT,
RPMTFREQ,
RPMTFREM,
PCODE,
SBRNO,
SBRNO2,
CIFKEY,
SICCD,
INTBAL,
NTINTBAL,
CLSDAY,
AMRTTM,
AMRTTMM,
MARGIN,
CBCD,
CHARCD,
ACAPNO,
CGTRT,
INBAL,
ORBAL,
ORPAYBAL,
ITYPE,
RFLG,
TDTRT,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(GENDY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(GENDY))='0' THEN NULL ELSE GENDY END) AS GENDY,
ACTNO,
ACNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISDAY))='0' THEN NULL ELSE ISDAY END) AS ISDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY))='0' THEN NULL ELSE EDAY END) AS EDAY,
BAL,
NTBAL,
USBAL,
AVGBAL,
NTAVGBAL,
NETRT,
IRTCD,
SWFNAM,
AMTPCD,
PAYBAL,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LPAYDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LPAYDT))='0' THEN NULL ELSE LPAYDT END) AS LPAYDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NPAYDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NPAYDT))='0' THEN NULL ELSE NPAYDT END) AS NPAYDT,
PMTFREQ,
PMTFREM,
ACCD,
ACCBAL,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRPAYDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRPAYDT))='0' THEN NULL ELSE LRPAYDT END) AS LRPAYDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NRPAYDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NRPAYDT))='0' THEN NULL ELSE NRPAYDT END) AS NRPAYDT,
RPMTFREQ,
RPMTFREM,
PCODE,
SBRNO,
SBRNO2,
CIFKEY,
SICCD,
INTBAL,
NTINTBAL,
CLSDAY,
AMRTTM,
AMRTTMM,
MARGIN,
CBCD,
CHARCD,
ACAPNO,
CGTRT,
INBAL,
ORBAL,
ORPAYBAL,
ITYPE,
RFLG,
TDTRT,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
