-- SQL for table: EDW_FXB_FRCMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLAMT' AS DATA_CHK_COL,
COLAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(COLAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXCNT' AS DATA_CHK_COL,
TXCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TXCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RJTSUM' AS DATA_CHK_COL,
RJTSUM AS DATA_VAL,
SDG.UFN_NUMCHECK(RJTSUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'COLSUM' AS DATA_CHK_COL,
COLSUM AS DATA_VAL,
SDG.UFN_NUMCHECK(COLSUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECSUM' AS DATA_CHK_COL,
RECSUM AS DATA_VAL,
SDG.UFN_NUMCHECK(RECSUM) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RJTAMT' AS DATA_CHK_COL,
RJTAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RJTAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PAYAMT' AS DATA_CHK_COL,
PAYAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PAYAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BALAMT' AS DATA_CHK_COL,
BALAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(BALAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRCCNT' AS DATA_CHK_COL,
TRCCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TRCCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RECCNT' AS DATA_CHK_COL,
RECCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RECCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TRCNT' AS DATA_CHK_COL,
TRCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(TRCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'TXTNO' AS DATA_CHK_COL,
TXTNO AS DATA_VAL,
SDG.UFN_NUMCHECK(TXTNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'WSNO' AS DATA_CHK_COL,
WSNO AS DATA_VAL,
SDG.UFN_NUMCHECK(WSNO) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RJTCNT' AS DATA_CHK_COL,
RJTCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(RJTCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FXB_FRCMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CURCD,
COLAMT,
COLDAT,
RECTYP,
TXCNT,
RJTSUM,
COLSUM,
RECSUM,
RJTAMT,
PAYAMT,
BALAMT,
MAILBK,
MSWFCD,
PRCLDAT,
TRCCNT,
TRCDAT,
RECCNT,
LRECDAT,
TRCNT,
TXTNO,
WSNO,
LASTDT,
TLRNO,
RJTCNT,
LRJTDAT,
NTXDAY,
RCKIND,
CIFKEY,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
APTYPE,
BRNO,
SRNO,
OBUFG,
RBRNO,
ACBRNO,
KINBR,
BKCUR,
BKSRNO,
CURCD,
COLAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(COLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(COLDAT))='0' THEN NULL ELSE COLDAT END) AS COLDAT,
RECTYP,
TXCNT,
RJTSUM,
COLSUM,
RECSUM,
RJTAMT,
PAYAMT,
BALAMT,
MAILBK,
MSWFCD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRCLDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRCLDAT))='0' THEN NULL ELSE PRCLDAT END) AS PRCLDAT,
TRCCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(TRCDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(TRCDAT))='0' THEN NULL ELSE TRCDAT END) AS TRCDAT,
RECCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRECDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRECDAT))='0' THEN NULL ELSE LRECDAT END) AS LRECDAT,
TRCNT,
TXTNO,
WSNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
TLRNO,
RJTCNT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LRJTDAT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LRJTDAT))='0' THEN NULL ELSE LRJTDAT END) AS LRJTDAT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
RCKIND,
CIFKEY,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
