-- SQL for table: EDW_FC_FCMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBCNT' AS DATA_CHK_COL,
PBCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(PBCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CTCNT' AS DATA_CHK_COL,
CTCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CTCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MTCNT' AS DATA_CHK_COL,
MTCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(MTCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ASCNT' AS DATA_CHK_COL,
ASCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(ASCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBPAGE' AS DATA_CHK_COL,
PBPAGE AS DATA_VAL,
SDG.UFN_NUMCHECK(PBPAGE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBCOL' AS DATA_CHK_COL,
PBCOL AS DATA_VAL,
SDG.UFN_NUMCHECK(PBCOL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CTPAGE' AS DATA_CHK_COL,
CTPAGE AS DATA_VAL,
SDG.UFN_NUMCHECK(CTPAGE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CTCOL' AS DATA_CHK_COL,
CTCOL AS DATA_VAL,
SDG.UFN_NUMCHECK(CTCOL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTDPBAL' AS DATA_CHK_COL,
NTDPBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NTDPBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NTWHBAL' AS DATA_CHK_COL,
NTWHBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(NTWHBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHGAMT' AS DATA_CHK_COL,
CHGAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHGAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CHOPAMT' AS DATA_CHK_COL,
CHOPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CHOPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_1' AS DATA_CHK_COL,
IXPR_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_2' AS DATA_CHK_COL,
IXPR_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_3' AS DATA_CHK_COL,
IXPR_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_4' AS DATA_CHK_COL,
IXPR_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_5' AS DATA_CHK_COL,
IXPR_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_6' AS DATA_CHK_COL,
IXPR_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_7' AS DATA_CHK_COL,
IXPR_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_8' AS DATA_CHK_COL,
IXPR_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_9' AS DATA_CHK_COL,
IXPR_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_10' AS DATA_CHK_COL,
IXPR_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_11' AS DATA_CHK_COL,
IXPR_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_12' AS DATA_CHK_COL,
IXPR_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_13' AS DATA_CHK_COL,
IXPR_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_14' AS DATA_CHK_COL,
IXPR_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_15' AS DATA_CHK_COL,
IXPR_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_16' AS DATA_CHK_COL,
IXPR_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_17' AS DATA_CHK_COL,
IXPR_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_18' AS DATA_CHK_COL,
IXPR_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_19' AS DATA_CHK_COL,
IXPR_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_20' AS DATA_CHK_COL,
IXPR_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_21' AS DATA_CHK_COL,
IXPR_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_22' AS DATA_CHK_COL,
IXPR_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_23' AS DATA_CHK_COL,
IXPR_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_24' AS DATA_CHK_COL,
IXPR_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_25' AS DATA_CHK_COL,
IXPR_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_26' AS DATA_CHK_COL,
IXPR_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_27' AS DATA_CHK_COL,
IXPR_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_28' AS DATA_CHK_COL,
IXPR_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_29' AS DATA_CHK_COL,
IXPR_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR_30' AS DATA_CHK_COL,
IXPR_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_1' AS DATA_CHK_COL,
RIXPR_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_2' AS DATA_CHK_COL,
RIXPR_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_3' AS DATA_CHK_COL,
RIXPR_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_4' AS DATA_CHK_COL,
RIXPR_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_5' AS DATA_CHK_COL,
RIXPR_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_6' AS DATA_CHK_COL,
RIXPR_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_7' AS DATA_CHK_COL,
RIXPR_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_8' AS DATA_CHK_COL,
RIXPR_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_9' AS DATA_CHK_COL,
RIXPR_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_10' AS DATA_CHK_COL,
RIXPR_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_11' AS DATA_CHK_COL,
RIXPR_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_12' AS DATA_CHK_COL,
RIXPR_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_13' AS DATA_CHK_COL,
RIXPR_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_14' AS DATA_CHK_COL,
RIXPR_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_15' AS DATA_CHK_COL,
RIXPR_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_16' AS DATA_CHK_COL,
RIXPR_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_17' AS DATA_CHK_COL,
RIXPR_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_18' AS DATA_CHK_COL,
RIXPR_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_19' AS DATA_CHK_COL,
RIXPR_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_20' AS DATA_CHK_COL,
RIXPR_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_21' AS DATA_CHK_COL,
RIXPR_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_22' AS DATA_CHK_COL,
RIXPR_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_23' AS DATA_CHK_COL,
RIXPR_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_24' AS DATA_CHK_COL,
RIXPR_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_25' AS DATA_CHK_COL,
RIXPR_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_26' AS DATA_CHK_COL,
RIXPR_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_27' AS DATA_CHK_COL,
RIXPR_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_28' AS DATA_CHK_COL,
RIXPR_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_29' AS DATA_CHK_COL,
RIXPR_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RIXPR_30' AS DATA_CHK_COL,
RIXPR_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(RIXPR_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PNBCNT' AS DATA_CHK_COL,
PNBCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(PNBCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_1' AS DATA_CHK_COL,
PBBAL_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_2' AS DATA_CHK_COL,
PBBAL_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_3' AS DATA_CHK_COL,
PBBAL_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_4' AS DATA_CHK_COL,
PBBAL_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_5' AS DATA_CHK_COL,
PBBAL_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_6' AS DATA_CHK_COL,
PBBAL_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_7' AS DATA_CHK_COL,
PBBAL_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_8' AS DATA_CHK_COL,
PBBAL_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_9' AS DATA_CHK_COL,
PBBAL_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_10' AS DATA_CHK_COL,
PBBAL_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_11' AS DATA_CHK_COL,
PBBAL_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_12' AS DATA_CHK_COL,
PBBAL_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_13' AS DATA_CHK_COL,
PBBAL_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_14' AS DATA_CHK_COL,
PBBAL_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_15' AS DATA_CHK_COL,
PBBAL_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_16' AS DATA_CHK_COL,
PBBAL_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_17' AS DATA_CHK_COL,
PBBAL_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_18' AS DATA_CHK_COL,
PBBAL_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_19' AS DATA_CHK_COL,
PBBAL_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_20' AS DATA_CHK_COL,
PBBAL_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_21' AS DATA_CHK_COL,
PBBAL_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_22' AS DATA_CHK_COL,
PBBAL_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_23' AS DATA_CHK_COL,
PBBAL_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_24' AS DATA_CHK_COL,
PBBAL_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_25' AS DATA_CHK_COL,
PBBAL_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_26' AS DATA_CHK_COL,
PBBAL_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_27' AS DATA_CHK_COL,
PBBAL_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_28' AS DATA_CHK_COL,
PBBAL_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_29' AS DATA_CHK_COL,
PBBAL_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBBAL_30' AS DATA_CHK_COL,
PBBAL_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBBAL_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_1' AS DATA_CHK_COL,
PBMTBAL_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_2' AS DATA_CHK_COL,
PBMTBAL_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_3' AS DATA_CHK_COL,
PBMTBAL_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_4' AS DATA_CHK_COL,
PBMTBAL_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_5' AS DATA_CHK_COL,
PBMTBAL_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_6' AS DATA_CHK_COL,
PBMTBAL_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_7' AS DATA_CHK_COL,
PBMTBAL_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_8' AS DATA_CHK_COL,
PBMTBAL_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_9' AS DATA_CHK_COL,
PBMTBAL_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_10' AS DATA_CHK_COL,
PBMTBAL_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_11' AS DATA_CHK_COL,
PBMTBAL_11 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_11) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_12' AS DATA_CHK_COL,
PBMTBAL_12 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_12) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_13' AS DATA_CHK_COL,
PBMTBAL_13 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_13) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_14' AS DATA_CHK_COL,
PBMTBAL_14 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_14) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_15' AS DATA_CHK_COL,
PBMTBAL_15 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_15) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_16' AS DATA_CHK_COL,
PBMTBAL_16 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_16) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_17' AS DATA_CHK_COL,
PBMTBAL_17 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_17) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_18' AS DATA_CHK_COL,
PBMTBAL_18 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_18) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_19' AS DATA_CHK_COL,
PBMTBAL_19 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_19) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_20' AS DATA_CHK_COL,
PBMTBAL_20 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_20) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_21' AS DATA_CHK_COL,
PBMTBAL_21 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_21) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_22' AS DATA_CHK_COL,
PBMTBAL_22 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_22) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_23' AS DATA_CHK_COL,
PBMTBAL_23 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_23) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_24' AS DATA_CHK_COL,
PBMTBAL_24 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_24) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_25' AS DATA_CHK_COL,
PBMTBAL_25 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_25) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_26' AS DATA_CHK_COL,
PBMTBAL_26 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_26) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_27' AS DATA_CHK_COL,
PBMTBAL_27 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_27) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_28' AS DATA_CHK_COL,
PBMTBAL_28 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_28) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_29' AS DATA_CHK_COL,
PBMTBAL_29 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_29) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PBMTBAL_30' AS DATA_CHK_COL,
PBMTBAL_30 AS DATA_VAL,
SDG.UFN_NUMCHECK(PBMTBAL_30) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CNBCNT' AS DATA_CHK_COL,
CNBCNT AS DATA_VAL,
SDG.UFN_NUMCHECK(CNBCNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ERPASSW' AS DATA_CHK_COL,
ERPASSW AS DATA_VAL,
SDG.UFN_NUMCHECK(ERPASSW) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'NCHOPAMT' AS DATA_CHK_COL,
NCHOPAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(NCHOPAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_FC_FCMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
MACTNO,
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
MO_ACTNO,
MO_BRNO,
MO_APNO,
MO_SRNO,
MO_CHKDG,
MI_ACTNO,
MI_BRNO,
MI_APNO,
MI_SRNO,
MI_CHKDG,
MRERR,
NBCD,
ACTSTP,
HIDENCD,
ACTSLP,
REMAIND,
ACTMVO,
ACTMVI,
MRTGE,
MAILCD,
ADVCD,
ACTCLS,
CHOP,
UNINO,
CORPNO,
PIDNO,
BCODE,
TAXCD,
RBRNO,
CHARCD,
PASWD,
PBCNT,
CTCNT,
MTCNT,
ASCNT,
PBVER,
PBPAGE,
PBCOL,
CTPAGE,
CTCOL,
OPDAY,
MODAY,
MIDAY,
LTXDAY,
BOOKDAY,
NTDPBAL,
NTWHBAL,
CHGAMT,
CHOPAMT,
CSDAY,
CEDAY,
LCURCD_1,
LCURCD_2,
LCURCD_3,
LCURCD_4,
LCURCD_5,
LCURCD_6,
LCURCD_7,
LCURCD_8,
LCURCD_9,
LCURCD_10,
LCURCD_11,
LCURCD_12,
LCURCD_13,
LCURCD_14,
LCURCD_15,
LCURCD_16,
LCURCD_17,
LCURCD_18,
LCURCD_19,
LCURCD_20,
LCURCD_21,
LCURCD_22,
LCURCD_23,
LCURCD_24,
LCURCD_25,
LCURCD_26,
LCURCD_27,
LCURCD_28,
LCURCD_29,
LCURCD_30,
IXPR_1,
IXPR_2,
IXPR_3,
IXPR_4,
IXPR_5,
IXPR_6,
IXPR_7,
IXPR_8,
IXPR_9,
IXPR_10,
IXPR_11,
IXPR_12,
IXPR_13,
IXPR_14,
IXPR_15,
IXPR_16,
IXPR_17,
IXPR_18,
IXPR_19,
IXPR_20,
IXPR_21,
IXPR_22,
IXPR_23,
IXPR_24,
IXPR_25,
IXPR_26,
IXPR_27,
IXPR_28,
IXPR_29,
IXPR_30,
RCSDAY,
RCEDAY,
RLCURCD_1,
RLCURCD_2,
RLCURCD_3,
RLCURCD_4,
RLCURCD_5,
RLCURCD_6,
RLCURCD_7,
RLCURCD_8,
RLCURCD_9,
RLCURCD_10,
RLCURCD_11,
RLCURCD_12,
RLCURCD_13,
RLCURCD_14,
RLCURCD_15,
RLCURCD_16,
RLCURCD_17,
RLCURCD_18,
RLCURCD_19,
RLCURCD_20,
RLCURCD_21,
RLCURCD_22,
RLCURCD_23,
RLCURCD_24,
RLCURCD_25,
RLCURCD_26,
RLCURCD_27,
RLCURCD_28,
RLCURCD_29,
RLCURCD_30,
RIXPR_1,
RIXPR_2,
RIXPR_3,
RIXPR_4,
RIXPR_5,
RIXPR_6,
RIXPR_7,
RIXPR_8,
RIXPR_9,
RIXPR_10,
RIXPR_11,
RIXPR_12,
RIXPR_13,
RIXPR_14,
RIXPR_15,
RIXPR_16,
RIXPR_17,
RIXPR_18,
RIXPR_19,
RIXPR_20,
RIXPR_21,
RIXPR_22,
RIXPR_23,
RIXPR_24,
RIXPR_25,
RIXPR_26,
RIXPR_27,
RIXPR_28,
RIXPR_29,
RIXPR_30,
PNBERR,
PNBDAY,
PNBSEQ,
PNBCNT,
PNBNSEQ,
PLNBDAY,
PBBAL_1,
PBBAL_2,
PBBAL_3,
PBBAL_4,
PBBAL_5,
PBBAL_6,
PBBAL_7,
PBBAL_8,
PBBAL_9,
PBBAL_10,
PBBAL_11,
PBBAL_12,
PBBAL_13,
PBBAL_14,
PBBAL_15,
PBBAL_16,
PBBAL_17,
PBBAL_18,
PBBAL_19,
PBBAL_20,
PBBAL_21,
PBBAL_22,
PBBAL_23,
PBBAL_24,
PBBAL_25,
PBBAL_26,
PBBAL_27,
PBBAL_28,
PBBAL_29,
PBBAL_30,
PBMTBAL_1,
PBMTBAL_2,
PBMTBAL_3,
PBMTBAL_4,
PBMTBAL_5,
PBMTBAL_6,
PBMTBAL_7,
PBMTBAL_8,
PBMTBAL_9,
PBMTBAL_10,
PBMTBAL_11,
PBMTBAL_12,
PBMTBAL_13,
PBMTBAL_14,
PBMTBAL_15,
PBMTBAL_16,
PBMTBAL_17,
PBMTBAL_18,
PBMTBAL_19,
PBMTBAL_20,
PBMTBAL_21,
PBMTBAL_22,
PBMTBAL_23,
PBMTBAL_24,
PBMTBAL_25,
PBMTBAL_26,
PBMTBAL_27,
PBMTBAL_28,
PBMTBAL_29,
PBMTBAL_30,
CNBERR,
CNBDAY,
CNBSEQ,
CNBCNT,
CNBNSEQ,
CLNBDAY,
ERPASSW,
RGBNO,
EIDERR,
PIDERR,
IRTCD,
CURFG,
NOIBK,
CBRNO,
OBRNO,
ODAY,
SLPBRNO1,
SLPDAY1,
SLPBRNO2,
SLPDAY2,
PRTCD,
NCHOPAMT,
SBRNO,
SLPFLG,
AOUNINO,
AGE,
UKIND,
UMARK,
UACNO,
Q60ERR,
UIDNO,
Q60ERDAY,
BK30DAY,
LSTDAY,
OBULN,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
MBRNO||MAPNO||MSRNO||MCHKDG,
MBRNO,
MAPNO,
MSRNO,
MCHKDG,
MO_BRNO||MO_APNO||MO_SRNO||MO_CHKDG,
MO_BRNO,
MO_APNO,
MO_SRNO,
MO_CHKDG,
MI_BRNO||MI_APNO||MI_SRNO||MI_CHKDG,
MI_BRNO,
MI_APNO,
MI_SRNO,
MI_CHKDG,
MRERR,
NBCD,
ACTSTP,
HIDENCD,
ACTSLP,
REMAIND,
ACTMVO,
ACTMVI,
MRTGE,
MAILCD,
ADVCD,
ACTCLS,
CHOP,
UNINO,
CORPNO,
PIDNO,
BCODE,
TAXCD,
RBRNO,
CHARCD,
PASWD,
PBCNT,
CTCNT,
MTCNT,
ASCNT,
PBVER,
PBPAGE,
PBCOL,
CTPAGE,
CTCOL,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPDAY))='0' THEN NULL ELSE OPDAY END) AS OPDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MODAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MODAY))='0' THEN NULL ELSE MODAY END) AS MODAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MIDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MIDAY))='0' THEN NULL ELSE MIDAY END) AS MIDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LTXDAY))='0' THEN NULL ELSE LTXDAY END) AS LTXDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BOOKDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BOOKDAY))='0' THEN NULL ELSE BOOKDAY END) AS BOOKDAY,
NTDPBAL,
NTWHBAL,
CHGAMT,
CHOPAMT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CSDAY))='0' THEN NULL ELSE CSDAY END) AS CSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CEDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CEDAY))='0' THEN NULL ELSE CEDAY END) AS CEDAY,
LCURCD_1,
LCURCD_2,
LCURCD_3,
LCURCD_4,
LCURCD_5,
LCURCD_6,
LCURCD_7,
LCURCD_8,
LCURCD_9,
LCURCD_10,
LCURCD_11,
LCURCD_12,
LCURCD_13,
LCURCD_14,
LCURCD_15,
LCURCD_16,
LCURCD_17,
LCURCD_18,
LCURCD_19,
LCURCD_20,
LCURCD_21,
LCURCD_22,
LCURCD_23,
LCURCD_24,
LCURCD_25,
LCURCD_26,
LCURCD_27,
LCURCD_28,
LCURCD_29,
LCURCD_30,
IXPR_1,
IXPR_2,
IXPR_3,
IXPR_4,
IXPR_5,
IXPR_6,
IXPR_7,
IXPR_8,
IXPR_9,
IXPR_10,
IXPR_11,
IXPR_12,
IXPR_13,
IXPR_14,
IXPR_15,
IXPR_16,
IXPR_17,
IXPR_18,
IXPR_19,
IXPR_20,
IXPR_21,
IXPR_22,
IXPR_23,
IXPR_24,
IXPR_25,
IXPR_26,
IXPR_27,
IXPR_28,
IXPR_29,
IXPR_30,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RCSDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RCSDAY))='0' THEN NULL ELSE RCSDAY END) AS RCSDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(RCEDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(RCEDAY))='0' THEN NULL ELSE RCEDAY END) AS RCEDAY,
RLCURCD_1,
RLCURCD_2,
RLCURCD_3,
RLCURCD_4,
RLCURCD_5,
RLCURCD_6,
RLCURCD_7,
RLCURCD_8,
RLCURCD_9,
RLCURCD_10,
RLCURCD_11,
RLCURCD_12,
RLCURCD_13,
RLCURCD_14,
RLCURCD_15,
RLCURCD_16,
RLCURCD_17,
RLCURCD_18,
RLCURCD_19,
RLCURCD_20,
RLCURCD_21,
RLCURCD_22,
RLCURCD_23,
RLCURCD_24,
RLCURCD_25,
RLCURCD_26,
RLCURCD_27,
RLCURCD_28,
RLCURCD_29,
RLCURCD_30,
RIXPR_1,
RIXPR_2,
RIXPR_3,
RIXPR_4,
RIXPR_5,
RIXPR_6,
RIXPR_7,
RIXPR_8,
RIXPR_9,
RIXPR_10,
RIXPR_11,
RIXPR_12,
RIXPR_13,
RIXPR_14,
RIXPR_15,
RIXPR_16,
RIXPR_17,
RIXPR_18,
RIXPR_19,
RIXPR_20,
RIXPR_21,
RIXPR_22,
RIXPR_23,
RIXPR_24,
RIXPR_25,
RIXPR_26,
RIXPR_27,
RIXPR_28,
RIXPR_29,
RIXPR_30,
PNBERR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PNBDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PNBDAY))='0' THEN NULL ELSE PNBDAY END) AS PNBDAY,
PNBSEQ,
PNBCNT,
PNBNSEQ,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PLNBDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PLNBDAY))='0' THEN NULL ELSE PLNBDAY END) AS PLNBDAY,
PBBAL_1,
PBBAL_2,
PBBAL_3,
PBBAL_4,
PBBAL_5,
PBBAL_6,
PBBAL_7,
PBBAL_8,
PBBAL_9,
PBBAL_10,
PBBAL_11,
PBBAL_12,
PBBAL_13,
PBBAL_14,
PBBAL_15,
PBBAL_16,
PBBAL_17,
PBBAL_18,
PBBAL_19,
PBBAL_20,
PBBAL_21,
PBBAL_22,
PBBAL_23,
PBBAL_24,
PBBAL_25,
PBBAL_26,
PBBAL_27,
PBBAL_28,
PBBAL_29,
PBBAL_30,
PBMTBAL_1,
PBMTBAL_2,
PBMTBAL_3,
PBMTBAL_4,
PBMTBAL_5,
PBMTBAL_6,
PBMTBAL_7,
PBMTBAL_8,
PBMTBAL_9,
PBMTBAL_10,
PBMTBAL_11,
PBMTBAL_12,
PBMTBAL_13,
PBMTBAL_14,
PBMTBAL_15,
PBMTBAL_16,
PBMTBAL_17,
PBMTBAL_18,
PBMTBAL_19,
PBMTBAL_20,
PBMTBAL_21,
PBMTBAL_22,
PBMTBAL_23,
PBMTBAL_24,
PBMTBAL_25,
PBMTBAL_26,
PBMTBAL_27,
PBMTBAL_28,
PBMTBAL_29,
PBMTBAL_30,
CNBERR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CNBDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CNBDAY))='0' THEN NULL ELSE CNBDAY END) AS CNBDAY,
CNBSEQ,
CNBCNT,
CNBNSEQ,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CLNBDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CLNBDAY))='0' THEN NULL ELSE CLNBDAY END) AS CLNBDAY,
ERPASSW,
RGBNO,
EIDERR,
PIDERR,
IRTCD,
CURFG,
NOIBK,
CBRNO,
OBRNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ODAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ODAY))='0' THEN NULL ELSE ODAY END) AS ODAY,
SLPBRNO1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SLPDAY1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SLPDAY1))='0' THEN NULL ELSE SLPDAY1 END) AS SLPDAY1,
SLPBRNO2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SLPDAY2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SLPDAY2))='0' THEN NULL ELSE SLPDAY2 END) AS SLPDAY2,
PRTCD,
NCHOPAMT,
SBRNO,
SLPFLG,
AOUNINO,
AGE,
UKIND,
UMARK,
UACNO,
Q60ERR,
UIDNO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(Q60ERDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(Q60ERDAY))='0' THEN NULL ELSE Q60ERDAY END) AS Q60ERDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(BK30DAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(BK30DAY))='0' THEN NULL ELSE BK30DAY END) AS BK30DAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LSTDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LSTDAY))='0' THEN NULL ELSE LSTDAY END) AS LSTDAY,
OBULN,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
