-- SQL for table: EDW_AROBO_CUSFUNDS
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INV_AMT_FC' AS DATA_CHK_COL,
INV_AMT_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(INV_AMT_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'INV_AMT_LC' AS DATA_CHK_COL,
INV_AMT_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(INV_AMT_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'BUY_PRICE' AS DATA_CHK_COL,
BUY_PRICE AS DATA_VAL,
SDG.UFN_NUMCHECK(BUY_PRICE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UNIT' AS DATA_CHK_COL,
UNIT AS DATA_VAL,
SDG.UFN_NUMCHECK(UNIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PRICE' AS DATA_CHK_COL,
PRICE AS DATA_VAL,
SDG.UFN_NUMCHECK(PRICE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FX_RATE' AS DATA_CHK_COL,
FX_RATE AS DATA_VAL,
SDG.UFN_NUMCHECK(FX_RATE) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MKT_AMT_FC' AS DATA_CHK_COL,
MKT_AMT_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(MKT_AMT_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MKT_AMT_LC' AS DATA_CHK_COL,
MKT_AMT_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(MKT_AMT_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UPL_FC' AS DATA_CHK_COL,
UPL_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(UPL_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UPL_DIVIDEND_FC' AS DATA_CHK_COL,
UPL_DIVIDEND_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(UPL_DIVIDEND_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UPL_LC' AS DATA_CHK_COL,
UPL_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(UPL_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'UPL_DIVIDEND_LC' AS DATA_CHK_COL,
UPL_DIVIDEND_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(UPL_DIVIDEND_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'URETURN_FC' AS DATA_CHK_COL,
URETURN_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(URETURN_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'URETURN_DIVIDEND_FC' AS DATA_CHK_COL,
URETURN_DIVIDEND_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(URETURN_DIVIDEND_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'URETURN_LC' AS DATA_CHK_COL,
URETURN_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(URETURN_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'URETURN_DIVIDEND_LC' AS DATA_CHK_COL,
URETURN_DIVIDEND_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(URETURN_DIVIDEND_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DIV_AMT_FC' AS DATA_CHK_COL,
DIV_AMT_FC AS DATA_VAL,
SDG.UFN_NUMCHECK(DIV_AMT_FC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DIV_AMT_LC' AS DATA_CHK_COL,
DIV_AMT_LC AS DATA_VAL,
SDG.UFN_NUMCHECK(DIV_AMT_LC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ONWAY_AMT' AS DATA_CHK_COL,
ONWAY_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ONWAY_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ONWAY_UNIT' AS DATA_CHK_COL,
ONWAY_UNIT AS DATA_VAL,
SDG.UFN_NUMCHECK(ONWAY_UNIT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ONWAY_INV_AMT' AS DATA_CHK_COL,
ONWAY_INV_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(ONWAY_INV_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'ORDER_YN' AS DATA_CHK_COL,
ORDER_YN AS DATA_VAL,
SDG.UFN_NUMCHECK(ORDER_YN) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_AROBO_CUSFUNDS
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUS_CODE,
IPMSET_CODE,
BANK_PRO_CODE,
PRO_CODE,
PRO_CUR_CODE,
FIRST_BUY_DATE,
INV_TYPE,
INV_CUR_CODE,
INV_AMT_FC,
INV_AMT_LC,
BUY_PRICE,
UNIT,
PRICE,
PRICE_DATE,
FX_RATE,
FX_DATE,
MKT_AMT_FC,
MKT_AMT_LC,
UPL_FC,
UPL_DIVIDEND_FC,
UPL_LC,
UPL_DIVIDEND_LC,
URETURN_FC,
URETURN_DIVIDEND_FC,
URETURN_LC,
URETURN_DIVIDEND_LC,
DIV_AMT_FC,
DIV_AMT_LC,
ONWAY_AMT,
ONWAY_UNIT,
ONWAY_INV_AMT,
ORDER_YN,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUS_CODE,
IPMSET_CODE,
BANK_PRO_CODE,
PRO_CODE,
PRO_CUR_CODE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(FIRST_BUY_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(FIRST_BUY_DATE))='0' THEN NULL ELSE FIRST_BUY_DATE END) AS FIRST_BUY_DATE,
INV_TYPE,
INV_CUR_CODE,
INV_AMT_FC,
INV_AMT_LC,
BUY_PRICE,
UNIT,
PRICE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRICE_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRICE_DATE))='0' THEN NULL ELSE PRICE_DATE END) AS PRICE_DATE,
FX_RATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(FX_DATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(FX_DATE))='0' THEN NULL ELSE FX_DATE END) AS FX_DATE,
MKT_AMT_FC,
MKT_AMT_LC,
UPL_FC,
UPL_DIVIDEND_FC,
UPL_LC,
UPL_DIVIDEND_LC,
URETURN_FC,
URETURN_DIVIDEND_FC,
URETURN_LC,
URETURN_DIVIDEND_LC,
DIV_AMT_FC,
DIV_AMT_LC,
ONWAY_AMT,
ONWAY_UNIT,
ONWAY_INV_AMT,
ORDER_YN,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
