-- SQL for table: EDW_WMS_SFAFCAREAMON
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DATA_YEAR' AS DATA_CHK_COL,
DATA_YEAR AS DATA_VAL,
SDG.UFN_NUMCHECK(DATA_YEAR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'DATA_MONTH' AS DATA_CHK_COL,
DATA_MONTH AS DATA_VAL,
SDG.UFN_NUMCHECK(DATA_MONTH) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'VERSION' AS DATA_CHK_COL,
VERSION AS DATA_VAL,
SDG.UFN_NUMCHECK(VERSION) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_WMS_SFAFCAREAMON
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SOU_DATE,
DATA_YEAR,
DATA_MONTH,
EMP_TYPE,
EMP_ID,
BRANCH_NBR,
STATUS,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SOU_DATE), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SOU_DATE))='0' THEN '0001-01-01' ELSE SOU_DATE END) AS SOU_DATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(DATA_YEAR), '')='' THEN '0001-01-01' WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(DATA_YEAR))='0' THEN '0001-01-01' ELSE DATA_YEAR END) AS DATA_YEAR,
DATA_MONTH,
EMP_TYPE,
EMP_ID,
BRANCH_NBR,
STATUS,
VERSION,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREATETIME), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREATETIME))='0' THEN NULL ELSE CREATETIME END) AS CREATETIME,
CREATOR,
MODIFIER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTUPDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTUPDATE))='0' THEN NULL ELSE LASTUPDATE END) AS LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
