-- SQL for table: EDW_WMS_SFACUSTAOTXN_HIS
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
SEQ_NO,
CUST_ID,
CUST_NAME,
INV_AUM,
TOTAL_AUM,
OLD_BRANCH_NBR,
OLD_BRANCH_NAME,
OLD_AO_CODE,
OLD_AO_NAME,
OLD_AO_TYPE,
OLD_AO_NOTE,
SERVICE_DAY,
NEW_BRANCH_NBR,
NEW_BRANCH_NAME,
NEW_AO_CODE,
NEW_AO_NAME,
NEW_AO_TYPE,
TXN_CODE,
REASON_CODE,
REASON,
AO_EFFECT_DATE,
VERIFIER_ID,
VERIFIER_NAME,
VERIFIER_DATE,
SEQ_NUM,
APPLY_ID,
BR_TARGET_ADJ,
EXAMINEID_OUT,
EXAMINENAME_OUT,
EXAMINEID_IN,
EXAMINENAME_IN,
MOVEDATE_IN,
TRANSTYPE,
ALTERDT,
VERSION,
CREATETIME,
CREATOR,
MODIFIER,
LASTUPDATE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
