-- SQL for table: EDW_LNL_LLMR
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'APAMT' AS DATA_CHK_COL,
APAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(APAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SQBAL' AS DATA_CHK_COL,
SQBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(SQBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FITIRT' AS DATA_CHK_COL,
FITIRT AS DATA_VAL,
SDG.UFN_NUMCHECK(FITIRT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'AMOUNT' AS DATA_CHK_COL,
AMOUNT AS DATA_VAL,
SDG.UFN_NUMCHECK(AMOUNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'XRATEC' AS DATA_CHK_COL,
XRATEC AS DATA_VAL,
SDG.UFN_NUMCHECK(XRATEC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CURBAL' AS DATA_CHK_COL,
CURBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(CURBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'CURAMT' AS DATA_CHK_COL,
CURAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(CURAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RICAMT' AS DATA_CHK_COL,
RICAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RICAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'SPREAD' AS DATA_CHK_COL,
SPREAD AS DATA_VAL,
SDG.UFN_NUMCHECK(SPREAD) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FXRATEC' AS DATA_CHK_COL,
FXRATEC AS DATA_VAL,
SDG.UFN_NUMCHECK(FXRATEC) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSKAMT' AS DATA_CHK_COL,
RSKAMT AS DATA_VAL,
SDG.UFN_NUMCHECK(RSKAMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'RSKBAL' AS DATA_CHK_COL,
RSKBAL AS DATA_VAL,
SDG.UFN_NUMCHECK(RSKBAL) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IRID' AS DATA_CHK_COL,
IRID AS DATA_VAL,
SDG.UFN_NUMCHECK(IRID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXPR' AS DATA_CHK_COL,
IXPR AS DATA_VAL,
SDG.UFN_NUMCHECK(IXPR) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'IXID' AS DATA_CHK_COL,
IXID AS DATA_VAL,
SDG.UFN_NUMCHECK(IXID) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MININT' AS DATA_CHK_COL,
MININT AS DATA_VAL,
SDG.UFN_NUMCHECK(MININT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'FITDIV' AS DATA_CHK_COL,
FITDIV AS DATA_VAL,
SDG.UFN_NUMCHECK(FITDIV) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'LKBKDAYS' AS DATA_CHK_COL,
LKBKDAYS AS DATA_VAL,
SDG.UFN_NUMCHECK(LKBKDAYS) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_LNL_LLMR
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACTNO,
BRNO,
APNO,
SRNO,
CHKDG,
SQNO,
TRUHD,
SAPNO,
CURCD,
APAMT,
SQBAL,
TFCD,
ACTCLS,
APKIND,
APDATE,
ISDAY,
EDAY,
LASTDT,
NUMEDT,
FITIRT,
SQICD,
OIDATE,
IDATE,
OPRDT,
PRDATE,
IPNO,
APNUM,
APCUR,
AMOUNT,
XRATEC,
CURBAL,
OSQNO,
TFBRNO,
CURAMT,
RICAMT,
CURMICD,
LSBRCD,
SPREAD,
LFLC,
CBNO,
FXRATEC,
RSKAMT,
RSKBAL,
NTXDAY,
FLOWCHK,
IRCD,
IRID,
IXPR,
IXID,
MININT,
SUBSIDY,
FITDIV,
LKBKDAYS,
COMPOUND,
REFNO,
DEUSE,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
BRNO||APNO||SRNO||CHKDG,
BRNO,
APNO,
SRNO,
CHKDG,
SQNO,
TRUHD,
SAPNO,
CURCD,
APAMT,
SQBAL,
TFCD,
ACTCLS,
APKIND,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(APDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(APDATE))='0' THEN NULL ELSE APDATE END) AS APDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(ISDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(ISDAY))='0' THEN NULL ELSE ISDAY END) AS ISDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(EDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(EDAY))='0' THEN NULL ELSE EDAY END) AS EDAY,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(LASTDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(LASTDT))='0' THEN NULL ELSE LASTDT END) AS LASTDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NUMEDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NUMEDT))='0' THEN NULL ELSE NUMEDT END) AS NUMEDT,
FITIRT,
SQICD,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OIDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OIDATE))='0' THEN NULL ELSE OIDATE END) AS OIDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(IDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(IDATE))='0' THEN NULL ELSE IDATE END) AS IDATE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(OPRDT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(OPRDT))='0' THEN NULL ELSE OPRDT END) AS OPRDT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PRDATE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PRDATE))='0' THEN NULL ELSE PRDATE END) AS PRDATE,
IPNO,
APNUM,
APCUR,
AMOUNT,
XRATEC,
CURBAL,
OSQNO,
TFBRNO,
CURAMT,
RICAMT,
CURMICD,
LSBRCD,
SPREAD,
LFLC,
CBNO,
FXRATEC,
RSKAMT,
RSKBAL,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(NTXDAY), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(NTXDAY))='0' THEN NULL ELSE NTXDAY END) AS NTXDAY,
FLOWCHK,
IRCD,
IRID,
IXPR,
IXID,
MININT,
SUBSIDY,
FITDIV,
LKBKDAYS,
COMPOUND,
REFNO,
DEUSE,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
