-- SQL for table: EDW_NCARD_ACQTXBILL
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PROCESS_CNT' AS DATA_CHK_COL,
PROCESS_CNT AS DATA_VAL,
SDG.UFN_NUMCHECK(PROCESS_CNT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'PROCESS_AMT' AS DATA_CHK_COL,
PROCESS_AMT AS DATA_VAL,
SDG.UFN_NUMCHECK(PROCESS_AMT) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_AMT_1' AS DATA_CHK_COL,
USER_AMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_AMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_AMT_2' AS DATA_CHK_COL,
USER_AMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_AMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_AMT_3' AS DATA_CHK_COL,
USER_AMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_AMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_AMT_4' AS DATA_CHK_COL,
USER_AMT_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_AMT_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'USER_AMT_5' AS DATA_CHK_COL,
USER_AMT_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(USER_AMT_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_NCARD_ACQTXBILL
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACQ_BU,
MER_NBR,
POS_NBR,
SETTLE_DTE,
POSTING_DTE,
STMT_DTE,
FILE_BATCH_NO,
PMT_DTE_EST,
PMT_DTE,
PMT_SEQ,
SEQ,
CARD_TYPE,
ONUS_CARD_FLAG,
DOMESTIC_CARD_FLAG,
MT_TYPE,
CODE,
SOURCE_CODE,
CARD_NBR,
DESCR,
MEMO,
STMT_INVISIBLE,
PROCESS_CNT,
PROCESS_AMT,
PROGRAM,
USER_CHAR_1,
USER_CHAR_2,
USER_CHAR_3,
USER_CHAR_4,
USER_CHAR_5,
USER_AMT_1,
USER_AMT_2,
USER_AMT_3,
USER_AMT_4,
USER_AMT_5,
USER_DATE_1,
USER_DATE_2,
USER_DATE_3,
USER_DATE_4,
USER_DATE_5,
POST_RESULT,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ACQ_BU,
MER_NBR,
POS_NBR,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(SETTLE_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(SETTLE_DTE))='0' THEN NULL ELSE SETTLE_DTE END) AS SETTLE_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(POSTING_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(POSTING_DTE))='0' THEN NULL ELSE POSTING_DTE END) AS POSTING_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(STMT_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(STMT_DTE))='0' THEN NULL ELSE STMT_DTE END) AS STMT_DTE,
FILE_BATCH_NO,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PMT_DTE_EST), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PMT_DTE_EST))='0' THEN NULL ELSE PMT_DTE_EST END) AS PMT_DTE_EST,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(PMT_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(PMT_DTE))='0' THEN NULL ELSE PMT_DTE END) AS PMT_DTE,
PMT_SEQ,
SEQ,
CARD_TYPE,
ONUS_CARD_FLAG,
DOMESTIC_CARD_FLAG,
MT_TYPE,
CODE,
SOURCE_CODE,
CARD_NBR,
DESCR,
MEMO,
STMT_INVISIBLE,
PROCESS_CNT,
PROCESS_AMT,
PROGRAM,
USER_CHAR_1,
USER_CHAR_2,
USER_CHAR_3,
USER_CHAR_4,
USER_CHAR_5,
USER_AMT_1,
USER_AMT_2,
USER_AMT_3,
USER_AMT_4,
USER_AMT_5,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(USER_DATE_1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(USER_DATE_1))='0' THEN NULL ELSE USER_DATE_1 END) AS USER_DATE_1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(USER_DATE_2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(USER_DATE_2))='0' THEN NULL ELSE USER_DATE_2 END) AS USER_DATE_2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(USER_DATE_3), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(USER_DATE_3))='0' THEN NULL ELSE USER_DATE_3 END) AS USER_DATE_3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(USER_DATE_4), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(USER_DATE_4))='0' THEN NULL ELSE USER_DATE_4 END) AS USER_DATE_4,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(USER_DATE_5), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(USER_DATE_5))='0' THEN NULL ELSE USER_DATE_5 END) AS USER_DATE_5,
POST_RESULT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MNT_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MNT_DT))='0' THEN NULL ELSE MNT_DT END) AS MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
