-- SQL for table: EDW_NCARD_ACCTLINK
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
CUST_SEQ,
BU,
ACCT_NBR,
PRODUCT,
CURRENCY,
CUST_ID_BEF,
FILE_SEQ,
PROCESS_SEQ,
RIGHTS_GROUP_DATA,
CUST_ID,
CARD_FLAG,
USER_NBR_1,
USER_NBR_2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MNT_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MNT_DT))='0' THEN NULL ELSE MNT_DT END) AS MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
;

.export @LOAD_ROWCNT updatecnt;
