-- SQL for table: EDW_NCARD_ACQSTOREINFEX
/* CHECK_DATA */

-- Trinity SQL Script
INSERT INTO ${TARGET_SCHEMA}.${TASK_NAME}_CHK
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_1' AS DATA_CHK_COL,
MER_EX_USER_AMT_1 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_1) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_2' AS DATA_CHK_COL,
MER_EX_USER_AMT_2 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_2) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_3' AS DATA_CHK_COL,
MER_EX_USER_AMT_3 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_3) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_4' AS DATA_CHK_COL,
MER_EX_USER_AMT_4 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_4) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_5' AS DATA_CHK_COL,
MER_EX_USER_AMT_5 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_5) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_6' AS DATA_CHK_COL,
MER_EX_USER_AMT_6 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_6) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_7' AS DATA_CHK_COL,
MER_EX_USER_AMT_7 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_7) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_8' AS DATA_CHK_COL,
MER_EX_USER_AMT_8 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_8) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_9' AS DATA_CHK_COL,
MER_EX_USER_AMT_9 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_9) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0'
UNION ALL
SELECT *
FROM (
SELECT
CAST(ROWID AS VARCHAR2(100)) AS CHK_ID,
'num_err' AS DATA_CHK_TP,
'MER_EX_USER_AMT_10' AS DATA_CHK_COL,
MER_EX_USER_AMT_10 AS DATA_VAL,
SDG.UFN_NUMCHECK(MER_EX_USER_AMT_10) AS CHECK_RESULT
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE} 
WHERE DATA_EXCH_DATE = TO_DATE('${TXDATE}', 'YYYY-MM-DD')
) S1
WHERE S1.CHECK_RESULT = '0';

/* need to modify above 記得要有;號*/
DELETE FROM SDG.SDG_DATA_ERR_TBL WHERE TAB_NM='${TARGET_TABLE}' AND GROUP_CD='${EXEC_GCD}' AND BD_EXCH_DATE=TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd') AND BD_EXCH_TIME='${BD_EXCH_TIME}';

INSERT INTO SDG.SDG_DATA_ERR_TBL
SELECT
'${TARGET_TABLE}' AS TAB_NM,
'${EXEC_GCD}' AS GROUP_CD,
TO_DATE('${BD_EXCH_DATE}', 'YYYY-MM-DD') AS BD_EXCH_DATE,
'${BD_EXCH_TIME}' AS BD_EXCH_TIME,
C1.DATA_CHK_TP,
C1.DATA_CHK_COL,
C1.DATA_VAL,
S1.SRC_PK,
CURRENT_TIMESTAMP AS UPDATE_DATETIME
FROM
(
SELECT * FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK
) C1
LEFT JOIN 
(
SELECT CAST(ROWID AS VARCHAR2(100)) AS CHK_ID , ${SQL_STMT} AS SRC_PK FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
) S1
ON C1.CHK_ID=S1.CHK_ID
;

-- SQL for table: EDW_NCARD_ACQSTOREINFEX
/* TRANSFORM_DATA */

-- 異動方式待補/待調整，以下目前為公版
/* 1. 刪除Base DATA_EXCH_DATE='#資料交換期別#' 之資料 */
DELETE FROM ${TARGET_SCHEMA}.${TARGET_TABLE} WHERE DATA_EXCH_DATE = TO_DATE('${BD_EXCH_DATE}', 'yyyy-MM-dd');

-- Trinity SQL Script
/* 2. 抽取Stage DATA_EXCH_DATE = '#資料交換期別#'之資料進行新增 */
INSERT INTO ${TARGET_SCHEMA}.${TARGET_TABLE}
(
ACQ_BU,
MER_NBR,
MER_BAR_FLAG,
MER_QRC_DTE,
MER_BAR_DTE,
MER_EX_USER_CHAR_1,
MER_EX_USER_CHAR_2,
MER_EX_USER_CHAR_3,
MER_EX_USER_CHAR_4,
MER_EX_USER_CHAR_5,
MER_EX_USER_CHAR_6,
MER_EX_USER_CHAR_7,
MER_EX_USER_CHAR_8,
MER_EX_USER_CHAR_9,
MER_EX_USER_CHAR_10,
MER_EX_USER_DTE_1,
MER_EX_USER_DTE_2,
MER_EX_USER_DTE_3,
MER_EX_USER_DTE_4,
MER_EX_USER_DTE_5,
MER_EX_USER_DTE_6,
MER_EX_USER_DTE_7,
MER_EX_USER_DTE_8,
MER_EX_USER_DTE_9,
MER_EX_USER_DTE_10,
MER_EX_USER_AMT_1,
MER_EX_USER_AMT_2,
MER_EX_USER_AMT_3,
MER_EX_USER_AMT_4,
MER_EX_USER_AMT_5,
MER_EX_USER_AMT_6,
MER_EX_USER_AMT_7,
MER_EX_USER_AMT_8,
MER_EX_USER_AMT_9,
MER_EX_USER_AMT_10,
POST_RESULT,
CREATE_DT,
CREATE_USER,
MNT_DT,
MNT_USER,
DATA_UPDATE_TIME,
DATA_EXCH_DATE
)
SELECT
ACQ_BU,
MER_NBR,
MER_BAR_FLAG,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_QRC_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_QRC_DTE))='0' THEN NULL ELSE MER_QRC_DTE END) AS MER_QRC_DTE,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_BAR_DTE), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_BAR_DTE))='0' THEN NULL ELSE MER_BAR_DTE END) AS MER_BAR_DTE,
MER_EX_USER_CHAR_1,
MER_EX_USER_CHAR_2,
MER_EX_USER_CHAR_3,
MER_EX_USER_CHAR_4,
MER_EX_USER_CHAR_5,
MER_EX_USER_CHAR_6,
MER_EX_USER_CHAR_7,
MER_EX_USER_CHAR_8,
MER_EX_USER_CHAR_9,
MER_EX_USER_CHAR_10,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_1), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_1))='0' THEN NULL ELSE MER_EX_USER_DTE_1 END) AS MER_EX_USER_DTE_1,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_2), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_2))='0' THEN NULL ELSE MER_EX_USER_DTE_2 END) AS MER_EX_USER_DTE_2,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_3), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_3))='0' THEN NULL ELSE MER_EX_USER_DTE_3 END) AS MER_EX_USER_DTE_3,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_4), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_4))='0' THEN NULL ELSE MER_EX_USER_DTE_4 END) AS MER_EX_USER_DTE_4,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_5), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_5))='0' THEN NULL ELSE MER_EX_USER_DTE_5 END) AS MER_EX_USER_DTE_5,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_6), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_6))='0' THEN NULL ELSE MER_EX_USER_DTE_6 END) AS MER_EX_USER_DTE_6,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_7), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_7))='0' THEN NULL ELSE MER_EX_USER_DTE_7 END) AS MER_EX_USER_DTE_7,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_8), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_8))='0' THEN NULL ELSE MER_EX_USER_DTE_8 END) AS MER_EX_USER_DTE_8,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_9), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_9))='0' THEN NULL ELSE MER_EX_USER_DTE_9 END) AS MER_EX_USER_DTE_9,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MER_EX_USER_DTE_10), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MER_EX_USER_DTE_10))='0' THEN NULL ELSE MER_EX_USER_DTE_10 END) AS MER_EX_USER_DTE_10,
MER_EX_USER_AMT_1,
MER_EX_USER_AMT_2,
MER_EX_USER_AMT_3,
MER_EX_USER_AMT_4,
MER_EX_USER_AMT_5,
MER_EX_USER_AMT_6,
MER_EX_USER_AMT_7,
MER_EX_USER_AMT_8,
MER_EX_USER_AMT_9,
MER_EX_USER_AMT_10,
POST_RESULT,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(CREATE_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(CREATE_DT))='0' THEN NULL ELSE CREATE_DT END) AS CREATE_DT,
CREATE_USER,
SDG.UFN_NORM_DATE(CASE WHEN NVL(TRIM(MNT_DT), '')='' THEN NULL WHEN SDG.UFN_ADDATECHECK_DATE(TRIM(MNT_DT))='0' THEN NULL ELSE MNT_DT END) AS MNT_DT,
MNT_USER,
CURRENT_TIMESTAMP,
to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
FROM ${SOURCE_TABLE_OWNER}.${SOURCE_TABLE}
WHERE DATA_EXCH_DATE = to_date('${BD_EXCH_DATE}', 'yyyy-MM-dd')
AND CAST(ROWID AS VARCHAR2(100)) NOT IN (SELECT DISTINCT CHK_ID FROM ${TARGET_SCHEMA}.${TASK_NAME}_CHK WHERE DATA_CHK_TP LIKE '%err');

.export @LOAD_ROWCNT updatecnt;
